const STAT_LABELS={scoring:'Scoring',dunks:'Dunking',three:'3PT',freeThrows:'Free Throws',rebounding:'Rebounding',passing:'Passing',blocks:'Blocks',steals:'Steals'};
const CARD_LABELS={scoring:'SCO',dunks:'DNK',three:'3PT',freeThrows:'FT',rebounding:'REB',passing:'PAS',blocks:'BLK',steals:'STL'};
const STAT_KEYS=['scoring','dunks','three','freeThrows','rebounding','passing','blocks','steals'];
const RAW_STAT_KEYS=['scoring','rebounding','passing','three','dunks','steals','blocks','freeThrows'];
const ART_STORAGE_KEY='nbaCourtsideArtStudioV1';
const TEAM_THEMES={'1610612747':{a:'#552583',b:'#FDB927',c:'#1d0f33'},'1610612744':{a:'#1D428A',b:'#FFC72C',c:'#07192f'},'1610612749':{a:'#00471B',b:'#EEE1C6',c:'#001e0e'},'1610612738':{a:'#007A33',b:'#BA9653',c:'#022d18'},'1610612759':{a:'#C4CED4',b:'#ffffff',c:'#242b31'},'1610612743':{a:'#0E2240',b:'#FEC524',c:'#081426'},'1610612760':{a:'#007AC1',b:'#EF3B24',c:'#10264b'},'1610612750':{a:'#0C2340',b:'#78BE20',c:'#071524'},'1610612745':{a:'#CE1141',b:'#C4CED4',c:'#3b0714'}};
const TEAM_SHORT={'1610612747':'Lakers','1610612744':'Warriors','1610612749':'Bucks','1610612738':'Celtics','1610612759':'Spurs','1610612743':'Nuggets','1610612760':'Thunder','1610612750':'Timberwolves','1610612745':'Rockets'};
const RAW_PLAYERS=[
['LeBron James','Los Angeles Lakers','2025–26','1610612747','2544',[29,25,29,23,28,22,20,21],'lebron-james',{x:'58%',y:'100%',s:.72,r:0}],
['Stephen Curry','Golden State Warriors','2025–26','1610612744','201939',[29,17,27,30,8,23,8,30],'stephen-curry',{x:'58%',y:'100%',s:.70,r:0}],
['Giannis Antetokounmpo','Milwaukee Bucks','2025–26','1610612749','203507',[30,29,25,15,30,23,26,19],'giannis-antetokounmpo',{x:'58%',y:'100%',s:.72,r:0}],
['Jayson Tatum','Boston Celtics','2024–25','1610612738','1628369',[28,25,24,27,24,22,17,27],'jayson-tatum',{x:'58%',y:'100%',s:.78,r:0}],
['Victor Wembanyama','San Antonio Spurs','2025–26','1610612759','1641705',[28,28,22,25,29,22,30,26],'victor-wembanyama',{x:'59%',y:'100%',s:.76,r:0}],
['Nikola Jokić','Denver Nuggets','2025–26','1610612743','203999',[29,29,30,26,20,22,18,27],'nikola-jokic',{x:'58%',y:'100%',s:.78,r:0}],
['Shai Gilgeous-Alexander','Oklahoma City Thunder','2025–26','1610612760','1628983',[30,20,26,24,25,28,19,29],'shai-gilgeous-alexander',{x:'59%',y:'100%',s:.76,r:0}],
['Anthony Edwards','Minnesota Timberwolves','2025–26','1610612750','1630162',[28,22,23,27,29,24,18,25],'anthony-edwards',{x:'58%',y:'100%',s:.76,r:0}],
['Kevin Durant','Houston Rockets','2025–26','1610612745','201142',[29,23,24,28,25,20,23,29],'kevin-durant',{x:'59%',y:'100%',s:.76,r:0}],
['Luka Dončić','Los Angeles Lakers','2025–26','1610612747','1629029',[29,26,30,27,18,22,12,25],'luka-doncic',{x:'58%',y:'100%',s:.77,r:0}]];
const players=RAW_PLAYERS.map((p,i)=>({id:'p'+i,name:p[0],team:p[1],teamShort:TEAM_SHORT[p[3]]||p[1],season:p[2],teamId:p[3],playerId:p[4],stats:Object.fromEntries(RAW_STAT_KEYS.map((k,j)=>[k,p[5][j]])),artSlug:p[6],art:p[7],theme:TEAM_THEMES[p[3]]||{a:'#384154',b:'#f5f7fb',c:'#0f131b'}}));
const userTeam=players.slice(0,5),cpuTeam=players.slice(5);let state;const $=s=>document.querySelector(s);
function logoUrl(p){return `https://cdn.nba.com/logos/nba/${p.teamId}/global/L/logo.svg`}
function readArtStudio(){try{return JSON.parse(localStorage.getItem(ART_STORAGE_KEY)||'{}')}catch{return {}}}
function artConfig(p){const s=readArtStudio()[p.artSlug]||{};return{x:Number.isFinite(+s.x)?+s.x:parseFloat(p.art.x),y:Number.isFinite(+s.y)?+s.y:parseFloat(p.art.y),scale:(Number.isFinite(+s.scale)?+s.scale:p.art.s)*1.8,rotation:Number.isFinite(+s.rotation)?+s.rotation:(p.art.r||0),url:s.url||''}}
function artUrl(p,ext='png'){const c=artConfig(p);return c.url||`assets/player-art/${p.artSlug}.${ext}?v=0.6.0`}
function artError(slug){return `if(!this.dataset.localFallback&&this.src.startsWith('http')){this.dataset.localFallback='1';this.src='assets/player-art/${slug}.png?v=0.6.0'}else if(!this.dataset.webp){this.dataset.webp='1';this.src='assets/player-art/${slug}.webp?v=0.6.0'}else{this.onerror=null;this.style.display='none';this.parentElement.classList.add('art-missing')}`}
function cardMarkup(p,o={}){const {activeStat=null,used=false}=o,c=artConfig(p);const style=`--team-a:${p.theme.a};--team-b:${p.theme.b};--team-c:${p.theme.c};--art-x:${c.x}%;--art-y:${c.y}%;--art-scale:${c.scale};--art-rotation:${c.rotation}deg`;const long=p.name.length>18?' name-long':'';return `<article class="player-card ${used?'used':''}" data-id="${p.id}" style="${style}">
<div class="card-backdrop"></div><div class="holo-grid"></div><div class="rarity-burst"></div><div class="prism prism-a"></div><div class="prism prism-b"></div><div class="beam beam-one"></div><div class="beam beam-two"></div><div class="team-mark"><img src="${logoUrl(p)}" alt=""></div><div class="player-aura"></div>
<div class="art-stage"><img class="photo cutout-art" src="${artUrl(p)}" alt="${p.name}" onerror="${artError(p.artSlug)}"><div class="art-vignette"></div></div>
<div class="foreground-energy energy-a"></div><div class="foreground-energy energy-b"></div><div class="foil-field"></div><div class="spark spark-a"></div><div class="spark spark-b"></div><div class="spark spark-c"></div><div class="frame frame-outer"></div><div class="frame frame-mid"></div><div class="frame frame-inner"></div><div class="edge-glow"></div>
<div class="stats">${STAT_KEYS.map(k=>`<div class="stat ${activeStat===k?'active':''}"><span class="stat-circle"><b>${p.stats[k]}</b></span><span class="stat-label">${CARD_LABELS[k]}</span></div>`).join('')}</div>
<div class="identity${long}"><h3>${p.name}</h3><p>${p.teamShort} · ${p.season}</p></div><img class="team-logo" src="${logoUrl(p)}" alt="${p.teamShort}"></article>`}
function renderStarterFive(){$('#starterFive').innerHTML=userTeam.map(p=>{const c=artConfig(p);return `<div class="mini-card" style="--team-a:${p.theme.a};--team-b:${p.theme.b}"><img src="${c.url||`assets/player-art/${p.artSlug}.png?v=0.6.0`}" onerror="${artError(p.artSlug)}" alt="${p.name}"><span>${p.name}</span></div>`}).join('')}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active')}
function resetGame(){state={quarter:1,userScore:0,cpuScore:0,usedUser:new Set(),usedCpu:new Set(),category:null,history:[]};showScreen('game');beginQuarter()}
function beginQuarter(){state.category=STAT_KEYS[Math.floor(Math.random()*STAT_KEYS.length)];$('#quarterLabel').textContent='Q'+state.quarter;$('#categoryLabel').textContent=STAT_LABELS[state.category].toUpperCase();$('#userScore').textContent=state.userScore;$('#cpuScore').textContent=state.cpuScore;$('#instruction').textContent='Choose one unused player for '+STAT_LABELS[state.category];$('#revealPanel').classList.add('hidden');$('#lineup').innerHTML=userTeam.map(p=>cardMarkup(p,{activeStat:state.category,used:state.usedUser.has(p.id)})).join('');document.querySelectorAll('#lineup .player-card').forEach(c=>{if(!state.usedUser.has(c.dataset.id))c.onclick=()=>playQuarter(c.dataset.id)})}
function pickCpu(){const a=cpuTeam.filter(p=>!state.usedCpu.has(p.id));return a[Math.floor(Math.random()*a.length)]}
function playQuarter(id){const uP=userTeam.find(p=>p.id===id);if(!uP||state.usedUser.has(id))return;const cP=pickCpu(),u=uP.stats[state.category],c=cP.stats[state.category];state.usedUser.add(uP.id);state.usedCpu.add(cP.id);state.userScore+=u;state.cpuScore+=c;state.history.push({quarter:state.quarter,category:state.category,user:uP,cpu:cP,userPts:u,cpuPts:c});$('#userScore').textContent=state.userScore;$('#cpuScore').textContent=state.cpuScore;$('#lineup').innerHTML=userTeam.map(p=>cardMarkup(p,{activeStat:state.category,used:state.usedUser.has(p.id)})).join('');$('#userReveal').innerHTML=cardMarkup(uP,{activeStat:state.category});$('#cpuReveal').innerHTML=cardMarkup(cP,{activeStat:state.category});$('#quarterResult').innerHTML=`<span class="big">${u} – ${c}</span>${u===c?'Quarter tied':u>c?uP.name+' wins the quarter':cP.name+' wins the quarter'}`;$('#nextQuarterBtn').textContent=state.quarter===4?'Final Score':'Start Q'+(state.quarter+1);$('#revealPanel').classList.remove('hidden');$('#instruction').textContent=STAT_LABELS[state.category]+' result'}
function nextQuarter(){if(state.quarter===4)return finishGame();state.quarter++;beginQuarter();window.scrollTo({top:0,behavior:'smooth'})}
function finishGame(){showScreen('final');$('#finalUser').textContent=state.userScore;$('#finalCpu').textContent=state.cpuScore;$('#finalResult').textContent=state.userScore===state.cpuScore?'Overtime Needed':state.userScore>state.cpuScore?'Courtside Victory':'Defeat';$('#quarterSummary').innerHTML=state.history.map(h=>`<div class="summary-row"><strong>Q${h.quarter}</strong><span>${STAT_LABELS[h.category]} · ${h.user.name} vs ${h.cpu.name}</span><b>${h.userPts}–${h.cpuPts}</b></div>`).join('');window.scrollTo({top:0})}
$('#startBtn').onclick=resetGame;$('#playAgainBtn').onclick=resetGame;$('#newGameBtn').onclick=()=>showScreen('intro');$('#nextQuarterBtn').onclick=nextQuarter;renderStarterFive();