const STORAGE_KEY='nbaCourtsideArtStudioV1';
const DB_NAME='nbaCourtsideStudioFS',DB_STORE='handles',DB_KEY='repo-root';
const STAT_LABELS={scoring:'Scoring',dunks:'Dunking',three:'3PT',freeThrows:'Free Throws',rebounding:'Rebounding',passing:'Passing',blocks:'Blocks',steals:'Steals'};
const CARD_LABELS={scoring:'SCO',dunks:'DNK',three:'3PT',freeThrows:'FT',rebounding:'REB',passing:'PAS',blocks:'BLK',steals:'STL'};
const STAT_KEYS=['scoring','dunks','three','freeThrows','rebounding','passing','blocks','steals'];
const RAW_STAT_KEYS=['scoring','rebounding','passing','three','dunks','steals','blocks','freeThrows'];
const TEAM_THEMES={'1610612747':{a:'#552583',b:'#FDB927',c:'#1d0f33'},'1610612744':{a:'#1D428A',b:'#FFC72C',c:'#07192f'},'1610612749':{a:'#00471B',b:'#EEE1C6',c:'#001e0e'},'1610612738':{a:'#007A33',b:'#BA9653',c:'#022d18'},'1610612759':{a:'#C4CED4',b:'#ffffff',c:'#242b31'},'1610612743':{a:'#0E2240',b:'#FEC524',c:'#081426'},'1610612760':{a:'#007AC1',b:'#EF3B24',c:'#10264b'},'1610612750':{a:'#0C2340',b:'#78BE20',c:'#071524'},'1610612745':{a:'#CE1141',b:'#C4CED4',c:'#3b0714'}};
const RAW=[
['LeBron James','Los Angeles Lakers','2025–26','1610612747','Legend',[29,25,29,23,28,22,20,21],'lebron-james',{x:58,y:100,s:.72,r:0}],
['Stephen Curry','Golden State Warriors','2025–26','1610612744','Legend',[29,17,27,30,8,23,8,30],'stephen-curry',{x:58,y:100,s:.70,r:0}],
['Giannis Antetokounmpo','Milwaukee Bucks','2025–26','1610612749','Legend',[30,29,25,15,30,23,26,19],'giannis-antetokounmpo',{x:58,y:100,s:.72,r:0}],
['Jayson Tatum','Boston Celtics','2024–25','1610612738','Elite',[28,25,24,27,24,22,17,27],'jayson-tatum',{x:58,y:100,s:.78,r:0}],
['Victor Wembanyama','San Antonio Spurs','2025–26','1610612759','Legend',[28,28,22,25,29,22,30,26],'victor-wembanyama',{x:59,y:100,s:.76,r:0}],
['Nikola Jokić','Denver Nuggets','2025–26','1610612743','Legend',[29,29,30,26,20,22,18,27],'nikola-jokic',{x:58,y:100,s:.78,r:0}],
['Shai Gilgeous-Alexander','Oklahoma City Thunder','2025–26','1610612760','Legend',[30,20,26,24,25,28,19,29],'shai-gilgeous-alexander',{x:59,y:100,s:.76,r:0}],
['Anthony Edwards','Minnesota Timberwolves','2025–26','1610612750','Elite',[28,22,23,27,29,24,18,25],'anthony-edwards',{x:58,y:100,s:.76,r:0}],
['Kevin Durant','Houston Rockets','2025–26','1610612745','Legend',[29,23,24,28,25,20,23,29],'kevin-durant',{x:59,y:100,s:.76,r:0}],
['Luka Dončić','Los Angeles Lakers','2025–26','1610612747','Legend',[29,26,30,27,18,22,12,25],'luka-doncic',{x:58,y:100,s:.77,r:0}]
];
const players=RAW.map((p,i)=>({id:'p'+i,name:p[0],team:p[1],season:p[2],teamId:p[3],tier:p[4],stats:Object.fromEntries(RAW_STAT_KEYS.map((k,j)=>[k,p[5][j]])),slug:p[6],base:p[7],theme:TEAM_THEMES[p[3]]}));
const $=s=>document.querySelector(s);let current=players[0],previewObjectUrl=null,selectedFile=null,repoDirectory=null,assetDirectory=null;
function readStore(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}}function writeStore(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}function savedFor(p){return readStore()[p.slug]||{}}function configFor(p){const s=savedFor(p);return{x:Number.isFinite(+s.x)?+s.x:p.base.x,y:Number.isFinite(+s.y)?+s.y:p.base.y,s:Number.isFinite(+s.scale)?+s.scale:p.base.s,r:Number.isFinite(+s.rotation)?+s.rotation:p.base.r,url:s.url||''}}
function logoUrl(p){return `https://cdn.nba.com/logos/nba/${p.teamId}/global/L/logo.svg`}function defaultArt(p){return `assets/player-art/${p.slug}.png?v=0.5.3`}function artSrc(p,c){return previewObjectUrl||c.url||defaultArt(p)}function artFail(p){return `if(!this.dataset.webp&&!this.src.includes('blob:')){this.dataset.webp='1';this.src='assets/player-art/${p.slug}.webp?v=0.5.3'}else{this.onerror=null;this.style.display='none';this.parentElement.classList.add('art-missing')}`}
function cardMarkup(p,c){const long=p.name.length>18?' name-long':'';const style=`--team-a:${p.theme.a};--team-b:${p.theme.b};--team-c:${p.theme.c};--art-x:${c.x}%;--art-y:${c.y}%;--art-scale:${c.s};--art-rotation:${c.r}deg`;return `<article class="player-card tier-${p.tier.toLowerCase()}" style="${style}"><div class="card-backdrop"></div><div class="holo-grid"></div><div class="rarity-burst"></div><div class="prism prism-a"></div><div class="prism prism-b"></div><div class="beam beam-one"></div><div class="beam beam-two"></div><div class="team-mark"><img src="${logoUrl(p)}" alt=""></div><div class="player-aura"></div><div class="art-stage"><img class="photo cutout-art" src="${artSrc(p,c)}" alt="${p.name}" onerror="${artFail(p)}"><div class="art-vignette"></div></div><div class="foreground-energy energy-a"></div><div class="foreground-energy energy-b"></div><div class="foil-field"></div><div class="spark spark-a"></div><div class="spark spark-b"></div><div class="spark spark-c"></div><div class="frame frame-outer"></div><div class="frame frame-mid"></div><div class="frame frame-inner"></div><div class="edge-glow"></div><div class="tier-name">${p.tier}</div><div class="stats">${STAT_KEYS.map(k=>`<div class="stat"><span class="stat-circle"><b>${p.stats[k]}</b></span><span class="stat-label">${CARD_LABELS[k]}</span></div>`).join('')}</div><div class="identity${long}"><span class="identity-kicker">NBA COURTSIDE · ${p.tier}</span><h3>${p.name}</h3><p>${p.team} · ${p.season}</p></div><img class="team-logo" src="${logoUrl(p)}" alt="${p.team}"></article>`}
function uiConfig(){return{x:+$('#xRange').value,y:+$('#yRange').value,s:+$('#scaleRange').value,r:+$('#rotationRange').value,url:$('#artUrlInput').value.trim()}}function render(){const c=uiConfig();$('#studioCard').innerHTML=cardMarkup(current,c);$('#xValue').textContent=c.x+'%';$('#yValue').textContent=c.y+'%';$('#scaleValue').textContent=c.s.toFixed(2)+'×';$('#rotationValue').textContent=c.r+'°';$('#studioCard').classList.toggle('hide-safe',!$('#safeToggle').checked);$('#studioCard').classList.toggle('hide-effects',!$('#effectsToggle').checked)}
function loadPlayer(){if(previewObjectUrl){URL.revokeObjectURL(previewObjectUrl);previewObjectUrl=null}selectedFile=null;$('#fileInput').value='';current=players.find(p=>p.slug===$('#playerSelect').value)||players[0];const c=configFor(current);$('#xRange').value=c.x;$('#yRange').value=c.y;$('#scaleRange').value=c.s;$('#rotationRange').value=c.r;$('#artUrlInput').value=c.url;render();setStatus(c.url?'Saved custom artwork loaded.':'Using repository artwork.')}function setStatus(t,cls=''){const el=$('#status');el.textContent=t;el.className='status '+cls}
function extensionFor(file){const name=(file?.name||'').toLowerCase();if(name.endsWith('.webp')||file?.type==='image/webp')return'webp';if(name.endsWith('.jpg')||name.endsWith('.jpeg')||file?.type==='image/jpeg')return'jpg';return'png'}async function ensureWritePermission(handle,request=false){if(!handle)return false;const opts={mode:'readwrite'};if((await handle.queryPermission?.(opts))==='granted')return true;if(request)return(await handle.requestPermission?.(opts))==='granted';return false}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(DB_STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}async function dbPut(handle){const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(handle,DB_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}async function dbGet(){const db=await openDB();const value=await new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readonly');const r=tx.objectStore(DB_STORE).get(DB_KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)});db.close();return value}
async function deriveAssetDirectory(root){const assets=await root.getDirectoryHandle('assets',{create:false});return await assets.getDirectoryHandle('player-art',{create:false})}async function connectRoot(root,requestPermission=false){if(!(await ensureWritePermission(root,requestPermission)))return false;const assets=await deriveAssetDirectory(root);repoDirectory=root;assetDirectory=assets;await dbPut(root);$('#folderStatus').textContent=`Connected: ${root.name} → assets/player-art`;$('#folderStatus').classList.add('ready');$('#chooseFolderBtn').textContent='Change Repository';return true}
async function restoreRepository(){if(!window.showDirectoryPicker){$('#folderStatus').textContent='Desktop Chrome or Edge required for direct folder saving.';return}try{const saved=await dbGet();if(saved&&await connectRoot(saved,false)){setStatus('Saved NBA Courtside repository reconnected automatically.','success')}else{$('#folderStatus').textContent=saved?'Repository remembered — click Reconnect Repository once to restore permission.':'First use: connect your nba-courtside repository folder.';if(saved)$('#chooseFolderBtn').textContent='Reconnect Repository'}}catch{$('#folderStatus').textContent='Connect your nba-courtside repository folder.'}}
async function writeFileToDirectory(name,data){const handle=await assetDirectory.getFileHandle(name,{create:true});const writable=await handle.createWritable();await writable.write(data);await writable.close()}async function blobFromCurrentSource(){if(selectedFile)return selectedFile;const url=$('#artUrlInput').value.trim();if(!url)throw new Error('Choose a local image first, or enter an image URL.');const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error('Could not download that image URL.');return await response.blob()}function saveLocalStore(assetPath=''){const c=uiConfig(),store=readStore();store[current.slug]={x:c.x,y:c.y,scale:c.s,rotation:c.r,url:assetPath||c.url};writeStore(store)}
$('#playerSelect').innerHTML=players.map(p=>`<option value="${p.slug}">${p.name} — ${p.team}</option>`).join('');$('#playerSelect').addEventListener('change',loadPlayer);['xRange','yRange','scaleRange','rotationRange'].forEach(id=>$('#'+id).addEventListener('input',render));['effectsToggle','safeToggle'].forEach(id=>$('#'+id).addEventListener('change',render));$('#loadUrlBtn').onclick=()=>{if(previewObjectUrl){URL.revokeObjectURL(previewObjectUrl);previewObjectUrl=null}selectedFile=null;render();setStatus($('#artUrlInput').value.trim()?'URL loaded in preview.':'Repository artwork restored in preview.','success')};$('#fileInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;selectedFile=f;if(previewObjectUrl)URL.revokeObjectURL(previewObjectUrl);previewObjectUrl=URL.createObjectURL(f);render();setStatus(`${f.name} loaded. It will save automatically as ${current.slug}.${extensionFor(f)}.`,'success')};
$('#chooseFolderBtn').onclick=async()=>{if(!window.showDirectoryPicker){setStatus('Direct folder saving requires desktop Chrome or Edge.','warn');return}try{const previous=await dbGet();if(previous&&await connectRoot(previous,true)){setStatus('Repository reconnected. assets/player-art is selected automatically.','success');return}const root=await window.showDirectoryPicker({id:'nba-courtside-repository',mode:'readwrite',startIn:previous||'documents'});if(root.name!=='nba-courtside'&&!confirm(`You selected “${root.name}”. Continue only if this is your NBA Courtside repository.`))return;if(!(await connectRoot(root,true)))throw new Error('Write permission was not granted.');setStatus('Repository connected. assets/player-art is now automatic and will be remembered.','success')}catch(e){if(e.name!=='AbortError')setStatus(e.message||'Could not access that repository.','warn')}};
$('#saveAssetBtn').onclick=async()=>{if(!assetDirectory){setStatus('Connect the NBA Courtside repository first. You only need to do this once.','warn');return}try{if(!(await ensureWritePermission(repoDirectory,true)))throw new Error('Repository write permission is required.');const blob=await blobFromCurrentSource();const ext=selectedFile?extensionFor(selectedFile):(blob.type==='image/webp'?'webp':blob.type==='image/jpeg'?'jpg':'png');const assetName=`${current.slug}.${ext}`,assetPath=`assets/player-art/${assetName}`;await writeFileToDirectory(assetName,blob);const c=uiConfig(),composition={slug:current.slug,name:current.name,asset:assetPath,art:{x:c.x,y:c.y,scale:c.s,rotation:c.r},updatedAt:new Date().toISOString()};await writeFileToDirectory(`${current.slug}.composition.json`,JSON.stringify(composition,null,2));$('#artUrlInput').value=assetPath;saveLocalStore(assetPath);render();setStatus(`Saved automatically as ${assetPath} plus ${current.slug}.composition.json. Commit/push in GitHub Desktop when ready.`,'success')}catch(e){setStatus(e.message||'Could not save the player artwork.','warn')}};
$('#saveBtn').onclick=()=>{saveLocalStore();setStatus('Saved to the game on this device.','success')};$('#resetBtn').onclick=()=>{const store=readStore();delete store[current.slug];writeStore(store);if(previewObjectUrl){URL.revokeObjectURL(previewObjectUrl);previewObjectUrl=null}selectedFile=null;loadPlayer();setStatus('Player reset to production defaults.','success')};$('#copyBtn').onclick=async()=>{const c=uiConfig(),payload={slug:current.slug,art:{x:c.x+'%',y:c.y+'%',s:c.s,r:c.r},url:c.url||`assets/player-art/${current.slug}.png`};try{await navigator.clipboard.writeText(JSON.stringify(payload,null,2));setStatus('Composition JSON copied.','success')}catch{setStatus(JSON.stringify(payload),'warn')}};
loadPlayer();restoreRepository();