/* NBA Starting5 Dream Team v0.14.0 — five-card, 140-cap, five-match run mode. */
(()=>{
if(window.__starting5DreamTeamV0140)return;window.__starting5DreamTeamV0140=true;
const CAP=140,POS=['PG','SG','SF','PF','C'],KEY='nbaStarting5DreamTeamV1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const overall=p=>Math.max(1,Math.min(30,Number(window.courtsideOverall?.(p)||p?.overall||Math.round(Object.values(p?.stats||{}).filter(Number.isFinite).reduce((a,b)=>a+b,0)/7)||1)));
const cardId=p=>String(p?.id||p?.playerId||'');
const teamLogo=id=>/^161/.test(String(id||''))?`https://cdn.nba.com/logos/nba/${id}/global/L/logo.svg`:'';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
let profile=load(),run=null,dreamActive=false,standardDeal=dealTeams;
function allCards(){const seen=new Set(),out=[];const add=p=>{if(!p||!p.position||!POS.includes(p.position))return;const k=cardId(p);if(!k||seen.has(k))return;seen.add(k);out.push(p)};(players||[]).forEach(add);(window.NBA_STARTING5_SEASON_FREE_AGENTS||[]).forEach(f=>add({...f,team:f.sourceTeam,teamShort:'Free Agent',season:'2026–27',teamId:'free-agent',playerId:f.id,artSlug:String(f.name).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-'),art:{x:'50%',y:'100%',s:.78,r:0},theme:{a:'#343b46',b:'#f7b928',c:'#0b0e13'},set:'Current Free Agents'}));return out}
const byId=id=>allCards().find(p=>cardId(p)===String(id));const roster=()=>profile?.roster?.map(byId).filter(Boolean)||[];const capTotal=r=>r.reduce((n,p)=>n+overall(p),0);
function ensureScreens(){if(document.getElementById('dreamTeamHome'))return;const shell=document.querySelector('.app-shell');['dreamTeamSetup','dreamTeamHome','dreamTeamRoster','dreamTeamLegacy','dreamTeamRewards'].forEach(id=>{const s=document.createElement('section');s.id=id;s.className='screen';shell.appendChild(s)});let b=document.getElementById('dreamTeamBtn');if(!b){b=document.createElement('button');b.id='dreamTeamBtn';b.type='button';b.className='catalogue-launch-btn';b.textContent='Dream Team';document.getElementById('catalogueBtn')?.insertAdjacentElement('afterend',b)}
}
function show(id){showScreen(id);window.scrollTo(0,0)}
function currentTeams(){const map=new Map();(window.COURTSIDE_FOUNDATION_PLAYERS||[]).filter(p=>!p.classicTeam&&/^161/.test(String(p.teamId))).forEach(p=>{if(!map.has(p.teamId))map.set(p.teamId,{id:p.teamId,name:p.team,players:[]});map.get(p.teamId).players.push(p)});return [...map.values()]}
function teamSix(t){const fa=(window.NBA_STARTING5_SEASON_FREE_AGENTS||[]).find(p=>p.sourceTeam===t.name);return [...t.players,...(fa?[allCards().find(x=>x.id===fa.id)].filter(Boolean):[])]}
function setup(){const root=document.getElementById('dreamTeamSetup');root.innerHTML=`<div class="dt-head"><div><div class="dt-kicker">DREAM TEAM</div><h1 class="dt-title">CHOOSE YOUR TEAM</h1></div><button class="dt-back" data-dt-exit>Back</button></div><p class="dt-copy">Your NBA team sets the branding. Three of your first five cards come randomly from its six-player current pool.</p><div class="dt-team-grid">${currentTeams().map(t=>`<button class="dt-team-pick" data-dt-team="${t.id}"><img src="${teamLogo(t.id)}" alt=""><span>${esc(t.name)}</span></button>`).join('')}</div>`;show('dreamTeamSetup')}
function makeOpening(tid){const t=currentTeams().find(x=>x.id===tid);if(!t)return;let first=[];for(const p of shuffle(teamSix(t))){if(!first.some(x=>x.position===p.position))first.push(p);if(first.length===3)break}const missing=POS.filter(pos=>!first.some(p=>p.position===pos));const used=new Set(first.map(cardId));for(const pos of missing){const candidates=shuffle(allCards().filter(p=>p.position===pos&&!used.has(cardId(p))));if(candidates[0]){first.push(candidates[0]);used.add(cardId(candidates[0]))}}if(first.length!==5)return;profile={teamId:t.id,teamName:t.name,roster:first.map(cardId),legacy:{},wins:0,losses:0,runs:0,perfectRuns:0};first.forEach(p=>legacy(p));save(profile);home()}
function legacy(p){const id=cardId(p);if(!profile.legacy[id])profile.legacy[id]={id,name:p.name,season:p.season,team:p.team,position:p.position,games:0,wins:0,losses:0,matchupWins:0,matchupLosses:0,plusMinus:0,runs:0,stints:1,current:true};return profile.legacy[id]}
function home(){const r=roster(),root=document.getElementById('dreamTeamHome'),logo=teamLogo(profile.teamId);root.innerHTML=`<div class="dt-home-brand">${logo?`<img src="${logo}" alt="">`:''}<div class="dt-kicker">DREAM TEAM</div><h1>${esc(profile.teamName)}</h1><div class="dt-cap">CAP ${capTotal(r)} / ${CAP}</div></div><button class="dt-play" data-dt-play>PLAY NOW<small>5 MATCHES · ${profile.wins||0}-${profile.losses||0} ALL-TIME</small></button><div class="dt-secondary-grid"><button class="dt-secondary" data-dt-roster>MY DREAM TEAM<small>5 CARDS · CAP ${capTotal(r)}/${CAP}</small></button><button class="dt-secondary" data-dt-legacy>TEAM LEGACY<small>RECORDS & PLAYER HISTORY</small></button></div>`;show('dreamTeamHome')}
function rosterScreen(){const r=roster(),root=document.getElementById('dreamTeamRoster');root.innerHTML=`<div class="dt-head"><div><div class="dt-kicker">DREAM TEAM</div><h1 class="dt-title">MY DREAM TEAM</h1></div><button class="dt-back" data-dt-home>Back</button></div><div class="dt-cap" style="margin-bottom:14px">SALARY CAP ${capTotal(r)} / ${CAP}</div><div class="dt-roster-list">${POS.map(pos=>{const p=r.find(x=>x.position===pos);return p?row(p,true):''}).join('')}</div>`;show('dreamTeamRoster')}
function row(p,current=false){const l=profile.legacy[cardId(p)]||{};return `<div class="dt-player-row"><div class="dt-pos">${p.position}</div><div><strong>${esc(p.name)}</strong><small>${esc(p.teamShort||p.team)} · ${esc(p.season)}${current?' · CURRENT':''}</small></div><div class="dt-ovr">${overall(p)}</div></div>`}
function legacyScreen(){const list=Object.values(profile.legacy||{}).sort((a,b)=>b.wins-a.wins||b.games-a.games),root=document.getElementById('dreamTeamLegacy');root.innerHTML=`<div class="dt-head"><div><div class="dt-kicker">DREAM TEAM</div><h1 class="dt-title">TEAM LEGACY</h1></div><button class="dt-back" data-dt-home>Back</button></div><div class="dt-record-cards"><div class="dt-record"><b>${profile.wins||0}</b><span>WINS</span></div><div class="dt-record"><b>${profile.losses||0}</b><span>LOSSES</span></div><div class="dt-record"><b>${profile.perfectRuns||0}</b><span>5–0 RUNS</span></div></div><div class="dt-legacy-list">${list.map(l=>`<div class="dt-player-row"><div class="dt-pos">${l.position}</div><div><strong>${esc(l.name)} ${l.current?'<span class="dt-current">· ACTIVE</span>':''}</strong><small>${esc(l.team)} · ${esc(l.season)} · ${l.wins}-${l.losses} · Matchups ${l.matchupWins}-${l.matchupLosses} · +/- ${l.plusMinus>=0?'+':''}${l.plusMinus}</small></div><div class="dt-ovr">${l.games}</div></div>`).join('')||'<div class="dt-empty">No games played yet.</div>'}</div>`;show('dreamTeamLegacy')}
function cpuFive(){const pool=allCards();if(Math.random()<.08){const names={};pool.forEach(p=>(names[p.name]||(names[p.name]=[])).push(p));const multi=shuffle(Object.values(names).filter(a=>a.length>=3))[0];if(multi){const x=[];while(x.length<5)x.push(multi[Math.floor(Math.random()*multi.length)]);return x.map((p,i)=>({...p,id:`${p.id}-special-${i}`}))}}return POS.map(pos=>shuffle(pool.filter(p=>p.position===pos))[0]).filter(Boolean)}
function installDeal(){dealTeams=function(){if(!dreamActive)return standardDeal();userTeam=roster();cpuTeam=cpuFive()}}
function startRun(){run={match:1,wins:0,losses:0};dreamActive=true;installDeal();strip();resetGame()}
function strip(){let x=document.getElementById('dtRunStrip');if(!x){x=document.createElement('div');x.id='dtRunStrip';x.className='dt-run-strip';document.body.appendChild(x)}x.textContent=`DREAM TEAM · MATCH ${run.match} OF 5 · ${run.wins}-${run.losses}`}
function recordGame(d){if(!dreamActive||!run)return;const won=d.userScore>d.cpuScore;won?run.wins++:run.losses++;won?profile.wins++:profile.losses++;const r=roster();r.forEach(p=>{const l=legacy(p);l.games++;won?l.wins++:l.losses++});(d.history||[]).forEach(h=>{const l=legacy(h.user);if(h.userPts>h.cpuPts)l.matchupWins++;else if(h.userPts<h.cpuPts)l.matchupLosses++;l.plusMinus+=(Number(h.userPts)||0)-(Number(h.cpuPts)||0)});save(profile);strip();if(run.match<5){setTimeout(()=>{run.match++;strip();resetGame()},1350)}else setTimeout(rewards,900)}
function weightedPick(pool,wins){if(!pool.length)return null;const exp=.55+wins*.28,weights=pool.map(p=>Math.pow(Math.max(1,overall(p)),exp)),total=weights.reduce((a,b)=>a+b,0);let n=Math.random()*total;for(let i=0;i<pool.length;i++){n-=weights[i];if(n<=0)return pool[i]}return pool.at(-1)}
function rewards(){dreamActive=false;document.getElementById('dtRunStrip')?.remove();profile.runs=(profile.runs||0)+1;if(run.wins===5)profile.perfectRuns=(profile.perfectRuns||0)+1;roster().forEach(p=>legacy(p).runs++);const r=roster(),total=capTotal(r),currentIds=new Set(r.map(cardId));let legal=allCards().filter(p=>!currentIds.has(cardId(p))&&r.some(old=>old.position===p.position&&total-overall(old)+overall(p)<=CAP));const choices=[];while(choices.length<3&&legal.length){const p=weightedPick(legal,run.wins);choices.push(p);legal=legal.filter(x=>cardId(x)!==cardId(p))}profile.pendingRewards=choices.map(cardId);profile.lastRun={wins:run.wins,losses:run.losses};save(profile);const root=document.getElementById('dreamTeamRewards');root.innerHTML=`<div class="dt-head"><div><div class="dt-kicker">${run.wins}-${run.losses} COMPLETE</div><h1 class="dt-title">CHOOSE ONE</h1></div></div><p class="dt-copy">Every card shown is a legal one-for-one swap under the ${CAP}-point cap. Choose one or keep your five.</p><div class="dt-reward-grid">${choices.map(p=>`<button class="dt-reward" data-dt-reward="${esc(cardId(p))}"><div class="dt-pos">${p.position}</div><strong>${esc(p.name)}</strong><div class="dt-ovr">${overall(p)}</div><small>${esc(p.teamShort||p.team)} · ${esc(p.season)}</small></button>`).join('')}</div><button class="dt-pass" data-dt-pass>PASS — KEEP MY TEAM</button>`;show('dreamTeamRewards')}
function take(id){const incoming=byId(id),r=roster();if(!incoming)return;const i=r.findIndex(p=>p.position===incoming.position);if(i<0||capTotal(r)-overall(r[i])+overall(incoming)>CAP)return;const old=r[i],oldL=legacy(old);oldL.current=false;const was=profile.legacy[cardId(incoming)];const inL=legacy(incoming);if(was&&!was.current)inL.stints=(inL.stints||1)+1;inL.current=true;profile.roster[i]=cardId(incoming);delete profile.pendingRewards;save(profile);run=null;home()}
window.addEventListener('s5:game-finished',e=>recordGame(e.detail));
document.addEventListener('click',e=>{const q=s=>e.target.closest(s);if(q('#dreamTeamBtn')){e.preventDefault();profile?home():setup()}else if(q('[data-dt-exit]'))show('intro');else if(q('[data-dt-team]'))makeOpening(q('[data-dt-team]').dataset.dtTeam);else if(q('[data-dt-home]'))home();else if(q('[data-dt-roster]'))rosterScreen();else if(q('[data-dt-legacy]'))legacyScreen();else if(q('[data-dt-play]'))startRun();else if(q('[data-dt-pass]')){delete profile.pendingRewards;save(profile);run=null;home()}else if(q('[data-dt-reward]'))take(q('[data-dt-reward]').dataset.dtReward)},true);
function boot(){ensureScreens();installDeal();if(profile?.pendingRewards?.length){const saved=profile.pendingRewards.map(byId).filter(Boolean);if(saved.length){run={wins:profile.lastRun?.wins||0,losses:profile.lastRun?.losses||0,match:5};rewards()}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.NBA_STARTING5_DREAM_TEAM={CAP,allCards,overall};
})();