(() => {
'use strict';
const D=window.NBA_COURTSIDE_DATA;
const basePlayers=[...D.players];
const teams=[...D.league.teams].sort((a,b)=>a.name.localeCompare(b.name));
const teamMap=new Map(teams.map(t=>[t.abbr,t]));
const $=s=>document.querySelector(s);
function storageGet(k){try{return window.localStorage?.getItem(k)??window.sessionStorage?.getItem(k)??null}catch(e){try{return window.sessionStorage?.getItem(k)??null}catch(_){return null}}}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const initials=n=>(n||'?').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const team=a=>teamMap.get(a);
const prettyPeriod=n=>n===1?'1ST':n===2?'2ND':n===3?'3RD':n===4?'4TH':`OT${n===5?'':n-4}`;
const fmtClock=s=>`${Math.floor(Math.max(0,s)/60)}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
const pct=v=>Math.round(clamp(v,0,100));

function readSave(){for(const key of ['nbaCourtsideSaveV25','nbaCourtsideSaveV24','nbaCourtsideSaveV23','nbaCourtsideSaveV22','nbaCourtsideSaveV21','nbaCourtsideSaveV20','nbaCourtsideSaveV19','nbaCourtsideSaveV18','nbaCourtsideSaveV17','nbaCourtsideSaveV16','nbaCourtsideSaveV15','nbaCourtsideSaveV14','nbaCourtsideSaveV13','nbaCourtsideSaveV12','nbaCourtsideSaveV11','nbaCourtsideSaveV10','nbaCourtsideSaveV09','nbaCourtsideSaveV08','nbaCourtsideSaveV07','nbaCourtsideSaveV05','nbaCourtsideSaveV04']){try{const x=JSON.parse(storageGet(key)||'null');if(x)return x}catch(e){}}return null}
const save=readSave();
let players=[...basePlayers,...(save?.generatedPlayers||[])];
if(save?.playerOverrides){for(const p of players){const o=save.playerOverrides[p.id];if(o){if(o.age!=null)p.age=o.age;if(o.ratings)p.ratings=structuredClone(o.ratings);if(o.development_profile)p.development_profile={...(p.development_profile||{}),...o.development_profile}}}}
const byId=new Map(players.map(p=>[p.id,p]));
function currentTeam(p){if(save?.assignments&&Object.prototype.hasOwnProperty.call(save.assignments,p.id))return save.assignments[p.id];return p.roster_status==='restricted_free_agent_unsigned'?null:p.team}
function currentStatus(p){return save?.statusOverrides?.[p.id]||p.roster_status}
function teamPlayers(a){return players.filter(p=>currentTeam(p)===a&&currentStatus(p)==='active')}
function salaryOf(p){if(save?.salaryOverrides&&Object.prototype.hasOwnProperty.call(save.salaryOverrides,p.id))return save.salaryOverrides[p.id];return p.contract?.years?.find(y=>y.season_start===(save?.seasonYear||2026))?.amount??p.contract?.years?.[0]?.amount??0}
function projectedOverall(p){if(p?.draft_projection?.current_overall)return p.draft_projection.current_overall;const s=salaryOf(p)/1e6;return p.age<=22?Math.round(68+clamp((s-4)/12,0,1)*10):66}
function overall(p){return p?.ratings?.overall??projectedOverall(p)}
function rating(p,key){if(p?.ratings?.[key]!=null)return p.ratings[key];const o=overall(p);if(key==='offense')return o+(p.positions?.some(x=>['PG','SG'].includes(x))?2:0);if(key==='defense')return o+(p.positions?.includes('C')?2:0);if(key==='three_pt')return clamp(o+(p.positions?.includes('C')?-7:1),45,92);if(key==='playmaking')return clamp(o+(p.positions?.includes('PG')?5:-1),45,95);if(key==='interior_defense')return clamp(o+(p.positions?.includes('C')?6:-2),45,95);if(key==='perimeter_defense')return clamp(o+(p.positions?.includes('C')?-4:1),45,95);if(key==='offensive_rebounding'||key==='defensive_rebounding')return clamp(o+(p.positions?.includes('C')?6:-2),45,95);if(key==='stamina')return clamp(o+5,50,96);return o}
function img(p,cls=''){if(!p?.headshot_url)return `<div class="${cls}" style="display:grid;place-items:center;font-weight:1000">${initials(p?.name)}</div>`;return `<img class="${cls}" src="${p.headshot_url}" alt="${p.name}" loading="lazy" decoding="async" onerror="this.style.visibility='hidden'">`}
function logo(t,cls=''){return `<img class="${cls}" src="${t.logo_url}" alt="${t.name||t.abbr} logo" decoding="async">`}
function lastName(p){return p.name.split(' ').slice(-1)[0]}
function setColors(){const h=team(homeTeam),a=team(awayTeam);document.documentElement.style.setProperty('--home',h.primary_color);document.documentElement.style.setProperty('--home2',h.secondary_color);document.documentElement.style.setProperty('--away',a.primary_color);document.documentElement.style.setProperty('--away2',a.secondary_color)}
function topPlayers(a,n=2){return teamPlayers(a).sort((x,y)=>overall(y)-overall(x)).slice(0,n)}

let homeTeam=storageGet('nbaCourtsideTeam')||save?.userTeam||'TOR';
if(!teamMap.has(homeTeam))homeTeam='TOR';
let awayTeam=homeTeam==='BOS'?'PHI':'BOS';
let pickerSide='home';
let conf='All';
let stage='select';
let rotationMode='balanced';
let rotations=null;
let game=null;
let boxSide='home';
let liveTimer=null;
let speed=1;
setColors();

function fitScore(p,pos){const o=overall(p);if(p.positions?.includes(pos))return o+45;const grp={PG:['SG'],SG:['PG','SF'],SF:['SG','PF'],PF:['SF','C'],C:['PF']}[pos]||[];if(grp.some(x=>p.positions?.includes(x)))return o+18;return o-12}
function startingFive(a){const pool=teamPlayers(a).slice(),used=new Set(),out=[];for(const pos of ['PG','SG','SF','PF','C']){const cand=pool.filter(p=>!used.has(p.id)).sort((x,y)=>fitScore(y,pos)-fitScore(x,pos))[0];if(cand){used.add(cand.id);out.push({pos,p:cand})}}return out}
function allocateMinutes(rotation,starterIds,mode){const cfg={tight:{smin:32,smax:40,bmin:8,bmax:25},balanced:{smin:28,smax:38,bmin:8,bmax:27},deep:{smin:25,smax:36,bmin:6,bmax:23}}[mode];const mins=new Map(),maxs=new Map(),weights=new Map();const avg=rotation.reduce((s,p)=>s+overall(p),0)/rotation.length;for(const p of rotation){const starter=starterIds.has(p.id);mins.set(p.id,starter?cfg.smin:cfg.bmin);maxs.set(p.id,starter?cfg.smax:cfg.bmax);weights.set(p.id,(starter?1.35:.8)*clamp(1+(overall(p)-avg)*.045,.55,1.65))}let remaining=240-[...mins.values()].reduce((a,b)=>a+b,0);while(remaining>0){const eligible=rotation.filter(p=>mins.get(p.id)<maxs.get(p.id));if(!eligible.length)break;eligible.sort((a,b)=>(weights.get(b.id)/(mins.get(b.id)+1))-(weights.get(a.id)/(mins.get(a.id)+1))||overall(b)-overall(a));mins.set(eligible[0].id,mins.get(eligible[0].id)+1);remaining--}while(remaining<0){const eligible=rotation.filter(p=>mins.get(p.id)>(starterIds.has(p.id)?cfg.smin:cfg.bmin));if(!eligible.length)break;eligible.sort((a,b)=>(weights.get(a.id)/(mins.get(a.id)+1))-(weights.get(b.id)/(mins.get(b.id)+1)));mins.set(eligible[0].id,mins.get(eligible[0].id)-1);remaining++}return mins}
function buildSchedule(rot){const remaining=new Map(rot.players.map(p=>[p.id,rot.targets.get(p.id)]));const schedule=[];let prev=[],streak={};const top5=[...rot.players].sort((a,b)=>overall(b)-overall(a)).slice(0,5).map(p=>p.id);for(let minute=0;minute<48;minute++){const used=new Set(),line=[];for(const pos of ['PG','SG','SF','PF','C']){let cand=rot.players.filter(p=>!used.has(p.id)&&remaining.get(p.id)>0);if(!cand.length)cand=rot.players.filter(p=>!used.has(p.id));cand.sort((a,b)=>{const score=p=>{const rem=remaining.get(p.id)||0;const must=rem>=(48-minute)?120:0;const close=minute>=42&&top5.includes(p.id)?24:0;const open=minute<=3&&rot.starterIds.has(p.id)?18:0;const st=(streak[p.id]||0)>7?-18:0;const rest=!prev.includes(p.id)?5:0;return rem*8+fitScore(p,pos)+overall(p)*.35+must+close+open+st+rest};return score(b)-score(a)});const pick=cand[0];if(pick){used.add(pick.id);line.push({pos,id:pick.id});remaining.set(pick.id,Math.max(0,(remaining.get(pick.id)||0)-1))}}schedule.push(line);const ids=line.map(x=>x.id);const ns={};for(const id of ids)ns[id]=prev.includes(id)?(streak[id]||0)+1:1;streak=ns;prev=ids}return schedule}
function buildRotation(a,mode='balanced'){const roster=teamPlayers(a).sort((x,y)=>overall(y)-overall(x));const five=startingFive(a);const starterIds=new Set(five.map(x=>x.p.id));const size=mode==='tight'?8:mode==='deep'?Math.min(11,roster.length):Math.min(10,roster.length);const selected=[...five.map(x=>x.p)];for(const p of roster)if(!starterIds.has(p.id)&&selected.length<size)selected.push(p);const targets=allocateMinutes(selected,starterIds,mode);const slotMap=new Map(five.map(x=>[x.p.id,x.pos]));const rot={team:a,mode,players:selected,starters:five,starterIds,targets,slotMap};rot.schedule=buildSchedule(rot);return rot}
function rotationForSide(side){return side==='home'?rotations.home:rotations.away}

function selectScreen(){const h=team(homeTeam),a=team(awayTeam),af=topPlayers(awayTeam),hf=topPlayers(homeTeam);const filtered=teams.filter(t=>conf==='All'||t.conference===conf);return `<a class="backLink" href="index.html?v=0.43">← GM OFFICE</a><header class="topbar"><div><div class="brand">NBA COURTSIDE</div><div class="topTitle">EXHIBITION</div></div><button class="iconBtn" id="swapTeams">⇄</button></header><section class="matchHero">${logo(a,'sideLogo away')}${logo(h,'sideLogo home')}<div class="matchNames"><h1>${a.name.toUpperCase()}</h1><em>VS</em><h1 class="homeName">${h.name.toUpperCase()}</h1></div><div class="heroFaces"><div class="faceSide away">${af.map(p=>img(p)).join('')}</div><div class="faceSide home">${hf.map(p=>img(p)).join('')}</div></div><div class="selectorHint"><button id="pickAway" class="${pickerSide==='away'?'active':''}">AWAY · ${a.abbr}</button><button id="pickHome" class="${pickerSide==='home'?'active':''}">HOME · ${h.abbr}</button></div></section><div class="sectionHead"><h2>Choose Teams</h2><span>ALL 30 NBA TEAMS</span></div><div class="confTabs"><button data-conf="All" class="${conf==='All'?'active':''}">ALL</button><button data-conf="East" class="${conf==='East'?'active':''}">EAST</button><button data-conf="West" class="${conf==='West'?'active':''}">WEST</button></div><div class="logoGrid">${filtered.map(t=>`<button class="teamLogoBtn ${t.abbr===awayTeam?'selectedAway':''} ${t.abbr===homeTeam?'selectedHome':''}" data-team="${t.abbr}">${logo(t)}<small>${t.abbr}</small></button>`).join('')}</div><div class="notice"><strong>${save?'Current franchise universe loaded.':'Frozen 19 Aug 2026 rosters loaded.'}</strong> Exhibition uses the same player ratings and roster database as the GM mode${save?' — including saved trades, signings and generated players on this browser.':''}</div><button class="primary" id="setRotations">SET DEPTH CHARTS</button>`}
function rotRow(rot,p,i){const starter=rot.starterIds.has(p.id),slot=starter?(rot.slotMap.get(p.id)||'ST'):('B'+(i-[...rot.starterIds].length+1));return `<div class="rotRow ${rot.targets.get(p.id)===0?'dnp':''}"><div class="rotSlot">${slot}</div>${img(p)}<div><div class="rotName">${p.name}</div><div class="rotMeta">${p.positions.join('/')} · OVR ${overall(p)}${starter?' · STARTER':''}</div></div><div class="rotMin"><b>${rot.targets.get(p.id)}</b><span>TARGET MIN</span></div></div>`}
function rotationCard(rot,side){const t=team(rot.team);return `<section class="rotationTeam" style="--rot:${t.primary_color}"><div class="rotHead">${logo(t)}<div><strong>${t.name}</strong><span>${side==='home'?'YOUR ROTATION':'CPU ROTATION'} · ${rot.players.length} ACTIVE</span></div></div><div class="rotRows">${rot.players.map((p,i)=>rotRow(rot,p,i)).join('')}</div></section>`}
function pregameScreen(){const h=team(homeTeam),a=team(awayTeam);return `<a class="backLink" href="#" id="backSelect">← CHANGE MATCHUP</a><header class="topbar"><div><div class="brand">NBA COURTSIDE</div><div class="topTitle">GAME NIGHT</div></div><div class="subtle">${a.abbr} @ ${h.abbr}</div></header><div class="sectionHead"><h2>Depth Charts</h2><span>240 MINUTES PER TEAM</span></div><div class="rotationSwitch"><button data-mode="tight" class="${rotationMode==='tight'?'active':''}">TIGHT · 8</button><button data-mode="balanced" class="${rotationMode==='balanced'?'active':''}">BALANCED · 10</button><button data-mode="deep" class="${rotationMode==='deep'?'active':''}">DEEP · 11</button></div>${rotationCard(rotations.home,'home')}${rotationCard(rotations.away,'away')}<div class="notice"><strong>Substitutions are automatic.</strong> The game follows these depth charts and target minutes, keeps five players on court at all times, manages fatigue, and tightens toward the best available lineup late.</div><button class="primary" id="tipOff">TIP OFF · ${a.abbr} @ ${h.abbr}</button>`}

function initStat(p){return {id:p.id,min:0,pts:0,reb:0,ast:0,stl:0,blk:0,tov:0,fgm:0,fga:0,tpm:0,tpa:0,ftm:0,fta:0,pf:0}}
function startGame(){rotations.home=buildRotation(homeTeam,rotationMode);rotations.away=buildRotation(awayTeam,'balanced');const stat={};for(const p of [...rotations.home.players,...rotations.away.players])stat[p.id]=initStat(p);const energy={};for(const id of Object.keys(stat))energy[id]=100;game={period:1,clock:720,homeScore:0,awayScore:0,possession:Math.random()<.5?'home':'away',stats:stat,energy,feed:[],moment:null,lastMinute:-1,lineups:{home:[],away:[]},final:false,possessions:0};syncLineups(true);stage='game';render()}
function minuteIndex(){if(game.period>4)return 47;return clamp((game.period-1)*12+Math.floor((720-game.clock)/60),0,47)}
function lineup(side){return game.lineups[side].map(id=>byId.get(id)).filter(Boolean)}
function scheduledLineup(side){const rot=rotationForSide(side);if(game.period>4)return [...rot.players].sort((a,b)=>overall(b)-overall(a)).slice(0,5).map((p,i)=>({pos:['PG','SG','SF','PF','C'][i],id:p.id}));return rot.schedule[minuteIndex()]||rot.schedule[47]}
function addFeed(text,side,score=true){game.feed.unshift({period:game.period,clock:fmtClock(game.clock),text,side,score:score?`${game.awayScore}–${game.homeScore}`:''});game.feed=game.feed.slice(0,18)}
function syncLineups(initial=false){const idx=minuteIndex();if(!initial&&idx===game.lastMinute&&game.period<=4)return;for(const side of ['away','home']){const next=scheduledLineup(side).map(x=>x.id),old=game.lineups[side]||[];if(!initial&&old.length){const incoming=next.filter(id=>!old.includes(id)).map(id=>lastName(byId.get(id))),outgoing=old.filter(id=>!next.includes(id)).map(id=>lastName(byId.get(id)));if(incoming.length)addFeed(`SUBS — ${incoming.join(', ')} in${outgoing.length?` for ${outgoing.join(', ')}`:''}.`,side,false)}game.lineups[side]=next}game.lastMinute=idx}
function simProfile(p,key,fallback=0){return p.simulation_profile?.[key]??fallback}
function shotUsage(p){return Math.max(5,simProfile(p,'fga_per36',10)+(rating(p,'shot_creation')-65)*.08)}
function weightedPick(arr,weight){let total=0;const ws=arr.map(x=>{const w=Math.max(.01,weight(x));total+=w;return w});let r=Math.random()*total;for(let i=0;i<arr.length;i++){r-=ws[i];if(r<=0)return arr[i]}return arr[arr.length-1]}
function teamAvg(side,key){const a=lineup(side);return a.reduce((s,p)=>s+rating(p,key),0)/Math.max(1,a.length)}
function energyAdjusted(p,key){return rating(p,key)-Math.max(0,72-(game.energy[p.id]||100))*.11}
function chooseRebounder(side,offensive=false){const arr=lineup(side);return weightedPick(arr,p=>offensive?rating(p,'offensive_rebounding'):rating(p,'defensive_rebounding'))}
function chooseDefender(side,interior=false){const arr=lineup(side);return weightedPick(arr,p=>interior?rating(p,'interior_defense'):rating(p,'perimeter_defense'))}
function chooseAssister(side,shooter){const arr=lineup(side).filter(p=>p.id!==shooter.id);return weightedPick(arr,p=>simProfile(p,'ast_per36',Math.max(1,(rating(p,'playmaking')-50)/8))+rating(p,'playmaking')/30)}
function currentScores(){return {home:game.homeScore,away:game.awayScore}}
function score(side,n){if(side==='home')game.homeScore+=n;else game.awayScore+=n}
function setMoment(p,title,sub,side){game.moment={id:p.id,title,sub,side}}
function turnoverRate(p,defSide){const sim=p.simulation_profile||{};const denom=Math.max(8,(sim.fga_per36||12)+.44*(sim.fta_per36||3)+(sim.ast_per36||3));const raw=(sim.tov_per36||2.1)/denom*.72;return clamp(raw+(75-energyAdjusted(p,'ball_security'))*.0011+(teamAvg(defSide,'perimeter_defense')-75)*.00055,.075,.18)}
function threePct(p,defSide){let base=p.stats_2025_26?.three_pct;if(base==null)base=.29+(energyAdjusted(p,'three_pt')-50)*.003;return clamp(base-(teamAvg(defSide,'perimeter_defense')-75)*.0011+(game.energy[p.id]-80)*.00025,.25,.49)}
function twoPct(p,defSide){const s=p.stats_2025_26;let base=null;if(s?.fga>0){const fgm=s.fg_pct*s.fga,tm=(s.three_pct||0)*(s.three_pa||0),ta=Math.max(.1,s.fga-(s.three_pa||0));base=(fgm-tm)/ta}if(!Number.isFinite(base))base=.42+(energyAdjusted(p,'finishing')-50)*.0032;return clamp(base-(teamAvg(defSide,'interior_defense')-75)*.0012+(game.energy[p.id]-80)*.00025,.39,.72)}
function ftPct(p){return clamp(p.stats_2025_26?.ft_pct??(.55+(rating(p,'free_throw')-50)*.005),.5,.97)}
function threeRate(p){return clamp(p.tendencies?.three_point_rate??(p.positions.includes('C')?.18:.38),.08,.72)}
function freeThrowRate(p){return clamp(p.tendencies?.free_throw_rate??.25,.08,.65)}
function advanceMinutes(duration){for(const side of ['home','away']){const on=new Set(game.lineups[side]),rot=rotationForSide(side);for(const p of rot.players){if(on.has(p.id)){game.stats[p.id].min+=duration/60;const drain=duration/60*(2.15+Math.max(0,82-rating(p,'stamina'))*.015);game.energy[p.id]=clamp(game.energy[p.id]-drain,28,100)}else game.energy[p.id]=clamp(game.energy[p.id]+duration/60*3.1,28,100)}}}
function possessionEvent(){if(game.final)return;syncLineups();const off=game.possession,def=off==='home'?'away':'home',offLine=lineup(off);if(!offLine.length){finishGame();return}const duration=Math.min(game.clock,Math.floor(8+Math.random()*12));const handler=weightedPick(offLine,p=>shotUsage(p)+simProfile(p,'ast_per36',3)*.55);let text='',moment=null,keep=false;
 if(Math.random()<turnoverRate(handler,def)){
   game.stats[handler.id].tov++;const steal=chooseDefender(def,false);if(Math.random()<.62&&steal){game.stats[steal.id].stl++;text=`${handler.name} turns it over — ${steal.name} takes it.`;moment={p:steal,title:'STEAL',sub:`${team(currentTeam(steal)).abbr} forces the turnover.`}}else text=`${handler.name} loses possession.`;
 } else {
   const shooter=weightedPick(offLine,p=>shotUsage(p));const isThree=Math.random()<threeRate(shooter);const foulChance=clamp(.055+freeThrowRate(shooter)*.18,.065,.16);
   if(Math.random()<foulChance){const shots=isThree&&Math.random()<.28?3:2;game.stats[shooter.id].fta+=shots;let made=0;for(let i=0;i<shots;i++)if(Math.random()<ftPct(shooter))made++;game.stats[shooter.id].ftm+=made;game.stats[shooter.id].pts+=made;score(off,made);const defender=chooseDefender(def,true);if(defender)game.stats[defender.id].pf++;text=`${shooter.name} draws the foul and hits ${made}/${shots} FT.`;moment={p:shooter,title:made===shots?'AT THE LINE':'FREE THROWS',sub:`${made} point${made===1?'':'s'} from the stripe.`};
   } else {
     const makePct=isThree?threePct(shooter,def):twoPct(shooter,def);game.stats[shooter.id].fga++;if(isThree)game.stats[shooter.id].tpa++;
     const blockChance=!isThree?clamp(.028+(teamAvg(def,'interior_defense')-72)*.0014,.02,.095):.006;const blocked=Math.random()<blockChance;const made=!blocked&&Math.random()<makePct;
     if(blocked){const blocker=chooseDefender(def,true);if(blocker)game.stats[blocker.id].blk++;const reb=chooseRebounder(def,false);if(reb)game.stats[reb.id].reb++;text=`${blocker?.name||'Defense'} BLOCKS ${shooter.name} at the rim.`;moment={p:blocker||shooter,title:'BLOCK',sub:`${team(rotationForSide(def).team).abbr} shuts the door.`};
     } else if(made){const val=isThree?3:2;game.stats[shooter.id].fgm++;if(isThree)game.stats[shooter.id].tpm++;game.stats[shooter.id].pts+=val;score(off,val);let assist=null;const astChance=clamp(.48+(teamAvg(off,'playmaking')-65)*.004,.43,.76);if(Math.random()<astChance){assist=chooseAssister(off,shooter);if(assist)game.stats[assist.id].ast++}text=`${shooter.name} ${isThree?'buries a THREE':'scores'}${assist?` — assist ${assist.name}`:''}.`;moment={p:shooter,title:isThree?'THREE':'BUCKET',sub:`${val} points for ${team(rotationForSide(off).team).abbr}.`};
     } else {const oRebChance=clamp(.225+(teamAvg(off,'offensive_rebounding')-teamAvg(def,'defensive_rebounding'))*.0017,.14,.36);if(Math.random()<oRebChance){const reb=chooseRebounder(off,true);if(reb)game.stats[reb.id].reb++;text=`${shooter.name} misses — ${reb?.name||'offense'} keeps it alive.`;keep=true}else{const reb=chooseRebounder(def,false);if(reb)game.stats[reb.id].reb++;text=`${shooter.name} misses. ${reb?.name||'Defense'} clears the glass.`}}
   }
 }
 advanceMinutes(duration);game.clock=Math.max(0,game.clock-duration);game.possessions++;if(!keep)game.possession=def;if(moment?.p)setMoment(moment.p,moment.title,moment.sub,off);addFeed(text,off,true);
 if(game.clock<=0)endPeriod();else syncLineups();
}
function endPeriod(){if(game.period<4){addFeed(`END ${prettyPeriod(game.period)} — ${game.awayScore}–${game.homeScore}.`,'home',true);game.period++;game.clock=720;game.lastMinute=-1;syncLineups(true);game.possession=game.possession==='home'?'away':'home';setMoment(topPlayers(game.possession==='home'?homeTeam:awayTeam,1)[0],'NEXT QUARTER',`${prettyPeriod(game.period)} ready.`,game.possession)}else if(game.homeScore===game.awayScore){game.period++;game.clock=300;game.lastMinute=-1;syncLineups(true);addFeed(`OVERTIME — tied ${game.homeScore}–${game.awayScore}.`,'home',true)}else finishGame()}
function finishGame(){game.final=true;stopLive();stage='final';render()}
function runUntil(predicate,max=900){stopLive();let n=0;while(!game.final&&!predicate()&&n++<max)possessionEvent();render()}
function simMinute(){const p=game.period,target=Math.max(0,game.clock-60);runUntil(()=>game.period!==p||game.clock<=target)}
function simQuarter(){const p=game.period;runUntil(()=>game.period!==p||game.final)}
function simGame(){runUntil(()=>game.final,1400)}
function startLive(){if(liveTimer){stopLive();render();return}const delay=()=>speed===1?700:speed===2?360:190;liveTimer=setInterval(()=>{if(game.final){stopLive();return}possessionEvent();render(false)},delay());render()}
function stopLive(){if(liveTimer){clearInterval(liveTimer);liveTimer=null}}

function livePlayer(p,side,pos){const st=game.stats[p.id],en=game.energy[p.id]||100;return `<div class="liveCard"><div class="livePhoto">${img(p)}<span class="livePos">${pos}</span><span class="liveOvr">${overall(p)}</span></div><div class="liveName">${lastName(p)}</div><div class="liveMin">${st.min.toFixed(1)} MIN · ${st.pts} PTS</div><div class="energy"><i style="width:${pct(en)}%"></i></div></div>`}
function courtPanel(side){const rot=rotationForSide(side),t=team(rot.team),scheduled=scheduledLineup(side),ids=new Set(game.lineups[side]),bench=rot.players.filter(p=>!ids.has(p.id));return `<section class="courtPanel"><div class="courtHead"><div><span>${side==='home'?'HOME':'AWAY'} · ${t.abbr}</span><strong>${t.name}</strong></div><span>AUTO SUBS · TARGET MIN</span></div><div class="fiveLive">${scheduled.map(x=>{const p=byId.get(x.id);return livePlayer(p,side,x.pos)}).join('')}</div><div class="benchStrip">${bench.map(p=>`<div class="benchChip">${img(p)}<div><b>${lastName(p)}</b><span>${game.stats[p.id].min.toFixed(1)} / ${rot.targets.get(p.id)} MIN · ${pct(game.energy[p.id])}%</span></div></div>`).join('')}</div></section>`}
function momentCard(){const m=game.moment,p=m?byId.get(m.id):null;if(!p)return `<div class="moment" style="--moment:#333"><div></div><div><strong>TIP OFF</strong><span>${team(awayTeam).abbr} at ${team(homeTeam).abbr}</span></div><em>LIVE</em></div>`;const t=team(currentTeam(p))||team(m.side==='home'?homeTeam:awayTeam);return `<div class="moment" style="--moment:${t.primary_color}">${img(p)}<div><strong>${m.title} · ${p.name}</strong><span>${m.sub}</span></div><em>${game.awayScore}–${game.homeScore}</em></div>`}
function feedView(){return `<div class="feed">${game.feed.slice(0,10).map(x=>`<div class="feedItem"><div class="feedClock">${prettyPeriod(x.period)} ${x.clock}</div><div class="feedText">${x.text}</div><div class="feedScore">${x.score}</div></div>`).join('')}</div>`}
function statRows(side){const rot=rotationForSide(side);return rot.players.map(p=>({p,s:game.stats[p.id]})).sort((a,b)=>b.s.min-a.s.min).map(x=>`<div class="boxRow"><div class="boxPlayer">${img(x.p)}<b>${lastName(x.p)}</b></div><span>${x.s.min.toFixed(1)}</span><span>${x.s.pts}</span><span>${x.s.reb}</span><span>${x.s.ast}</span><span>${x.s.fgm}-${x.s.fga}</span></div>`).join('')}
function boxPanel(){const t=team(boxSide==='home'?homeTeam:awayTeam);return `<section class="boxPanel"><div class="boxTabs"><button data-box="away" class="${boxSide==='away'?'active':''}">${team(awayTeam).abbr}</button><button data-box="home" class="${boxSide==='home'?'active':''}">${team(homeTeam).abbr}</button></div><div class="boxRow head"><div>PLAYER</div><span>MIN</span><span>PTS</span><span>REB</span><span>AST</span><span>FG</span></div>${statRows(boxSide)}</section>`}
function gameScreen(){const h=team(homeTeam),a=team(awayTeam);return `<div class="scoreboard"><div class="scoreInner"><div class="scoreSide">${logo(a)}<div><span>${a.abbr}</span><b>${game.awayScore}</b></div></div><div class="clock"><span>${prettyPeriod(game.period)}</span><strong>${fmtClock(game.clock)}</strong><small>${game.possession==='home'?h.abbr:a.abbr} BALL · ${game.possessions} POS</small></div><div class="scoreSide home"><div><span>${h.abbr}</span><b>${game.homeScore}</b></div>${logo(h)}</div></div></div>${momentCard()}${courtPanel('away')}${courtPanel('home')}<div class="gameControls"><button class="${liveTimer?'':'live'}" id="liveBtn">${liveTimer?'PAUSE':'WATCH LIVE'}</button><button id="simMinute">SIM 1 MIN</button><button id="simQuarter">TO QTR</button></div><button class="secondary" id="finishGame">SIM FINAL</button><div class="speedRow"><button data-speed="1" class="${speed===1?'active':''}">1× LIVE</button><button data-speed="2" class="${speed===2?'active':''}">2×</button><button data-speed="4" class="${speed===4?'active':''}">4×</button></div><div class="sectionHead"><h2>Game Feed</h2><span>AUTO ROTATIONS ACTIVE</span></div>${feedView()}<div class="sectionHead"><h2>Box Score</h2><span>LIVE MINUTES</span></div>${boxPanel()}`}
function topStat(side){const rot=rotationForSide(side);return rot.players.map(p=>({p,s:game.stats[p.id]})).sort((a,b)=>b.s.pts-a.s.pts||b.s.ast-a.s.ast)[0]}
function leaderCard(x){return `<div class="leader">${img(x.p)}<div><strong>${x.p.name}</strong><span>${x.s.pts} PTS · ${x.s.reb} REB · ${x.s.ast} AST · ${x.s.min.toFixed(1)} MIN</span></div><b>${x.s.pts}</b></div>`}
function finalScreen(){const h=team(homeTeam),a=team(awayTeam),winner=game.homeScore>game.awayScore?h:a;return `<a class="backLink" href="#" id="newExhibition">← NEW EXHIBITION</a><section class="finalHero"><div class="finalTag">FINAL · ${prettyPeriod(game.period)}</div><div class="finalScore">${game.awayScore}<br>${game.homeScore}</div><div class="finalWinner">${winner.name.toUpperCase()} WIN.</div></section><div class="sectionHead"><h2>Game Leaders</h2><span>${game.possessions} POSSESSIONS SIMULATED</span></div><div class="leaders">${leaderCard(topStat('away'))}${leaderCard(topStat('home'))}</div><div class="sectionHead"><h2>Final Box Score</h2><span>ACTUAL MINUTES</span></div>${boxPanel()}<button class="primary" id="runBack">RUN IT BACK</button>`}

function render(scrollTop=false){setColors();const root=$('#app');if(stage==='select')root.innerHTML=selectScreen();else if(stage==='pregame')root.innerHTML=pregameScreen();else if(stage==='game')root.innerHTML=gameScreen();else root.innerHTML=finalScreen();bind();if(scrollTop)window.scrollTo({top:0,behavior:'smooth'})}
function bind(){if(stage==='select'){
 $('#pickAway').onclick=()=>{pickerSide='away';render()};$('#pickHome').onclick=()=>{pickerSide='home';render()};$('#swapTeams').onclick=()=>{[homeTeam,awayTeam]=[awayTeam,homeTeam];render()};document.querySelectorAll('[data-conf]').forEach(b=>b.onclick=()=>{conf=b.dataset.conf;render()});document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{const v=b.dataset.team;if(pickerSide==='home'){if(v===awayTeam)awayTeam=homeTeam;homeTeam=v}else{if(v===homeTeam)homeTeam=awayTeam;awayTeam=v}setColors();render()});$('#setRotations').onclick=()=>{rotations={home:buildRotation(homeTeam,rotationMode),away:buildRotation(awayTeam,'balanced')};stage='pregame';render(true)};
 }else if(stage==='pregame'){
 $('#backSelect').onclick=e=>{e.preventDefault();stage='select';render(true)};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{rotationMode=b.dataset.mode;rotations.home=buildRotation(homeTeam,rotationMode);render()});$('#tipOff').onclick=startGame;
 }else if(stage==='game'){
 $('#liveBtn').onclick=startLive;$('#simMinute').onclick=simMinute;$('#simQuarter').onclick=simQuarter;$('#finishGame').onclick=simGame;document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{speed=+b.dataset.speed;if(liveTimer){stopLive();startLive()}else render()});document.querySelectorAll('[data-box]').forEach(b=>b.onclick=()=>{boxSide=b.dataset.box;render()});
 }else{
 $('#newExhibition').onclick=e=>{e.preventDefault();stage='select';game=null;rotations=null;render(true)};$('#runBack').onclick=()=>{rotations={home:buildRotation(homeTeam,rotationMode),away:buildRotation(awayTeam,'balanced')};stage='pregame';game=null;render(true)};document.querySelectorAll('[data-box]').forEach(b=>b.onclick=()=>{boxSide=b.dataset.box;render()});
 }}
window.addEventListener('beforeunload',stopLive);
render();
})();
