/* NBA Starting5 v0.13.0 — matchup ticker and scoreboard colour presentation only. */
(()=>{
  if(window.__starting5GameInfoBarV01300)return;window.__starting5GameInfoBarV01300=true;
  const labels={scoring:'SCORING',dunks:'DUNKS',three:'3PT',rebounding:'REBOUNDS',passing:'ASSISTS',blocks:'BLOCKS',steals:'STEALS'};
  const label=k=>labels[k]||String(k||'MATCHUP').toUpperCase();
  const ensureBar=()=>{const game=document.getElementById('game'),board=game?.querySelector('.scoreboard');if(!game||!board)return null;let bar=document.getElementById('gameInfoBar');if(!bar){bar=document.createElement('section');bar.id='gameInfoBar';bar.className='game-info-bar is-category';bar.setAttribute('aria-live','polite');bar.innerHTML='<strong></strong>';board.insertAdjacentElement('afterend',bar)}return bar};
  const showCurrent=()=>{let s=null;try{s=state}catch{};const bar=ensureBar();if(!bar)return;const strong=bar.querySelector('strong');if(strong)strong.textContent=!s?'MATCHUP':s.overtime?`OVERTIME · ${label(s.category)}`:`MATCHUP IS ${label(s.category)}`};
  const teamPlayer=side=>{try{const arr=side==='home'?userTeam:cpuTeam;return Array.isArray(arr)&&arr.length?arr[0]:null}catch{return null}};
  const paintScoreboard=()=>{const sb=document.querySelector('#game .scoreboard');if(!sb)return;let sides=[...sb.querySelectorAll('.score-side')];if(sides.length<2)sides=[...sb.children].filter(el=>!el.classList.contains('quarter-badge'));if(sides.length<2)return;const apply=(el,p)=>{if(!el||!p)return;const a=p?.theme?.a||'#1d428a',b=p?.theme?.b||'#fff',c=p?.theme?.c||'#07111d';el.style.setProperty('background',`linear-gradient(135deg,${a} 0%,${a} 58%,${c} 100%)`,'important');el.style.setProperty('border-color',b,'important')};apply(sides[0],teamPlayer('home'));apply(sides[sides.length-1],teamPlayer('away'))};
  const start=()=>{ensureBar();showCurrent();paintScoreboard();const cat=document.getElementById('categoryLabel');if(cat)new MutationObserver(()=>{showCurrent();paintScoreboard()}).observe(cat,{childList:true,subtree:true,characterData:true});const game=document.getElementById('game');if(game)new MutationObserver(()=>{if(game.classList.contains('active'))requestAnimationFrame(()=>{showCurrent();paintScoreboard()})}).observe(game,{attributes:true,attributeFilter:['class']})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();