/* NBA Courtside v0.9.27 — Foundation + PNG-only art pass + runtime PNG authority + cross-size art sync + editable background team watermark size/position/rotation */
(()=>{
  const t=window.COURTSIDE_ASSET_TOKEN||Date.now();
  document.write('<link rel="stylesheet" href="layout-v0.8.75.css?t='+t+'">');
  document.write('<script src="foundation-v0.9.0.js?t='+t+'"><\/script>');
  document.write('<script src="foundation-png-art-v0.9.8.js?t='+t+'"><\/script>');
  document.write('<script src="foundation-detroit-positions-v0.9.11.js?t='+t+'"><\/script>');
  document.write('<link rel="stylesheet" href="foundation-rail-v0.9.9.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-rail-start-padding-v0.9.12.css?t='+t+'">');
  document.write('<script src="foundation-team-deal-v0.9.2.js?t='+t+'"><\/script>');
  document.write('<link rel="stylesheet" href="foundation-card-corner-v0.9.4.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-card-unified-v0.9.6.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-rating-center-v0.9.13.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-art-edge-v0.9.14.css?t='+t+'">');
  document.write('<script src="foundation-art-editor-compat-v0.9.3.js?t='+t+'"><\/script>');
  document.write('<script src="art-editor-v0.8.64.js?t='+t+'"><\/script>');
  document.write('<script src="foundation-editor-plaque-v0.9.7.js?t='+t+'"><\/script>');
  document.write('<link rel="stylesheet" href="unslashed-zero-v0.9.10.css?t='+t+'">');
  document.write('<script src="foundation-art-runtime-v0.9.16.js?t='+t+'"><\/script>');
  document.write('<script src="foundation-art-scale-sync-v0.9.17.js?t='+t+'"><\/script>');
  document.write('<link rel="stylesheet" href="foundation-background-team-logo-v0.9.18.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-background-team-logo-v0.9.19.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-background-team-logo-v0.9.20.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-background-team-logo-v0.9.21.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-background-team-logo-v0.9.22.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-background-team-logo-v0.9.23.css?t='+t+'">');
  document.write('<link rel="stylesheet" href="foundation-background-team-logo-v0.9.24.css?t='+t+'">');
  document.write('<script src="foundation-background-team-logo-v0.9.18.js?t='+t+'"><\/script>');
  document.write('<script src="foundation-bg-logo-editor-v0.9.27.js?t='+t+'"><\/script>');
})();
