/* NBA Starting5 v0.13.0 — presentation only. No gameplay wrappers. */
(()=>{
  const teamFromCard=p=>{if(!p)return null;const t=TEAM_DATA[p.teamId]||['Team','#384154','#f5f7fb','#0f131b'];return{name:p.teamShort,full:p.team,id:p.teamId,logo:`https://cdn.nba.com/logos/nba/${p.teamId}/global/L/logo.svg`,primary:t[1],secondary:t[2],dark:t[3]}};
  function ensureScoreboardTeams(){
    if(!Array.isArray(userTeam)||!Array.isArray(cpuTeam)||!userTeam[0]||!cpuTeam[0])return;
    const game=document.getElementById('game');if(!game?.classList.contains('active'))return;
    if(game.classList.contains('s5-all-star-standard-game')||game.classList.contains('s5-rising-stars-game'))return;
    const board=game.querySelector('.scoreboard'),sides=board?.querySelectorAll('.score-side');if(!board||!sides||sides.length<2)return;
    const home=teamFromCard(userTeam[0]),away=teamFromCard(cpuTeam[0]);if(!home||!away)return;
    [[sides[0],home],[sides[1],away]].forEach(([side,team])=>{side.style.setProperty('--score-primary',team.primary);side.style.setProperty('--score-secondary',team.secondary);side.style.setProperty('--score-dark',team.dark)});
    sides[0].innerHTML=`<div class="score-team"><div class="score-logo-wrap"><img src="${home.logo}" alt="${home.name}"></div><div class="score-number"><strong id="userScore">${Number(state?.userScore)||0}</strong></div><div class="score-name">${home.name.toUpperCase()}</div></div>`;
    sides[1].innerHTML=`<div class="score-team away-team"><div class="score-number"><strong id="cpuScore">${Number(state?.cpuScore)||0}</strong></div><div class="score-logo-wrap"><img src="${away.logo}" alt="${away.name}"></div><div class="score-name">${away.name.toUpperCase()}</div></div>`;
  }
  function categoryVerb(h){const winner=h.userPts>=h.cpuPts?h.user:h.cpu,loser=h.userPts>=h.cpuPts?h.cpu:h.user;switch(h.category){case'rebounding':return`${winner.name} outrebounded ${loser.name}`;case'passing':return`${winner.name} found the better passing lanes against ${loser.name}`;case'blocks':return`${winner.name} protected the rim against ${loser.name}`;case'steals':return`${winner.name} stole the ball away from ${loser.name}`;case'dunks':return`${winner.name} dominated above the rim against ${loser.name}`;case'three':return`${winner.name} beat ${loser.name} from beyond the arc`;default:return`${winner.name} won the matchup against ${loser.name}`}}
  function renderFinalPresentation(){
    const final=document.querySelector('#final.active .final-card');if(!final||!state||!Array.isArray(userTeam)||!Array.isArray(cpuTeam)||!userTeam[0]||!cpuTeam[0])return;
    const game=document.getElementById('game');if(game?.classList.contains('s5-all-star-standard-game')||game?.classList.contains('s5-rising-stars-game'))return;
    const home=teamFromCard(userTeam[0]),away=teamFromCard(cpuTeam[0]);if(!home||!away)return;const tied=state.userScore===state.cpuScore,winner=state.userScore>state.cpuScore?home:away;
    const rows=(state.history||[]).map(h=>`<div class="story-row"><span class="story-q">${h.quarter==='OT'?'OT':'Q'+h.quarter}</span><div><strong>${categoryVerb(h)}</strong><small>${STAT_LABELS[h.category]} · ${h.user.name} ${h.userPts}–${h.cpuPts} ${h.cpu.name}</small></div></div>`).join('');
    final.innerHTML=`<span class="kicker">FINAL</span><div class="final-matchup"><div class="final-team"><img src="${home.logo}" alt="${home.name}"><span>${home.name}</span><strong>${state.userScore}</strong></div><div class="final-center"><b>FINAL</b><span>—</span></div><div class="final-team"><img src="${away.logo}" alt="${away.name}"><span>${away.name}</span><strong>${state.cpuScore}</strong></div></div><h2 class="final-winner">${tied?'Deadlocked':winner.name+' Win!'}</h2><div class="story-summary">${rows}</div><button id="playAgainBtn" class="primary-btn" type="button">Play Again</button>`;
    document.getElementById('playAgainBtn')?.addEventListener('click',()=>resetGame(),{once:true});
  }
  const game=document.getElementById('game');if(game)new MutationObserver(()=>{if(game.classList.contains('active'))requestAnimationFrame(ensureScoreboardTeams)}).observe(game,{attributes:true,attributeFilter:['class']});
  const final=document.getElementById('final');if(final)new MutationObserver(()=>{if(final.classList.contains('active'))requestAnimationFrame(renderFinalPresentation)}).observe(final,{attributes:true,attributeFilter:['class']});

  window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{
    const screen=document.getElementById('catalogue'),launch=document.getElementById('catalogueBtn'),back=document.getElementById('closeCatalogueBtn'),filter=document.getElementById('catalogueSetFilter'),browser=document.querySelector('.catalogue-team-browser'),grid=document.getElementById('catalogueGrid');if(!screen||!launch||!filter||!browser||!grid)return;
    const prev=document.getElementById('cataloguePrevTeam'),next=document.getElementById('catalogueNextTeam'),logo=document.getElementById('catalogueTeamLogo'),name=document.getElementById('catalogueTeamName'),meta=document.getElementById('catalogueTeamMeta');
    const teams=[...new Map(players.map(p=>[p.teamId,{id:p.teamId,name:p.teamShort}])).values()].sort((a,b)=>a.name.localeCompare(b.name));const sets=[...new Set(players.map(p=>p.set))];let teamIndex=0,activeSet='ALL';
    const renderFilters=()=>{filter.innerHTML=['ALL',...sets].map(s=>`<button class="catalogue-set-btn ${activeSet===s?'active':''}" data-set="${s}">${s==='ALL'?'All Sets':s}</button>`).join('');filter.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>{activeSet=b.dataset.set;renderFilters();render()})};
    const render=()=>{const cards=activeSet==='ALL'?players.filter(p=>p.teamId===teams[teamIndex].id):players.filter(p=>p.set===activeSet);if(activeSet==='ALL'){const team=teams[teamIndex];if(logo){logo.style.display='block';logo.src=`https://cdn.nba.com/logos/nba/${team.id}/global/L/logo.svg`;logo.alt=team.name}name.textContent=team.name;meta.textContent=`${cards.length} ${cards.length===1?'CARD':'CARDS'} · ALL SETS`}else{if(logo)logo.style.display='none';name.textContent=activeSet;meta.textContent=`${cards.length} CARDS · COMPLETE SET`}grid.innerHTML=cards.map(p=>cardMarkup(p,{})).join('');window.scrollTo({top:0})};
    if(prev)prev.onclick=()=>{if(activeSet==='ALL'){teamIndex=(teamIndex-1+teams.length)%teams.length;render()}};if(next)next.onclick=()=>{if(activeSet==='ALL'){teamIndex=(teamIndex+1)%teams.length;render()}};launch.onclick=()=>{showScreen('catalogue');renderFilters();render()};if(back)back.onclick=()=>{showScreen('intro');window.scrollTo({top:0})};renderFilters();render();
  },0));

  window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{
    const intro=document.getElementById('intro'),actions=intro?.querySelector('.brand-launch-actions'),play=document.getElementById('startBtn'),catalogue=document.getElementById('catalogueBtn'),topOptions=document.getElementById('optionsBtn'),topNewGame=document.getElementById('newGameBtn');if(!intro||!actions||!play||!catalogue)return;
    play.textContent='Play';play.classList.add('main-menu-btn','main-menu-play');catalogue.classList.add('main-menu-btn');let menuOptions=document.getElementById('mainMenuOptionsBtn');if(!menuOptions){menuOptions=document.createElement('button');menuOptions.id='mainMenuOptionsBtn';menuOptions.type='button';menuOptions.className='catalogue-launch-btn main-menu-btn';menuOptions.textContent='Options';catalogue.insertAdjacentElement('afterend',menuOptions)}menuOptions.onclick=()=>topOptions?.click();if(topNewGame){topNewGame.textContent='Menu';topNewGame.onclick=()=>{showScreen('intro');window.scrollTo({top:0})}}
    const style=document.createElement('style');style.id='starting5-main-menu-v01300';style.textContent=`#intro.brand-intro{min-height:calc(100dvh - 96px);display:none;flex-direction:column;justify-content:center;padding:16px 0 28px}#intro.brand-intro.active{display:flex}#intro .brand-launch-wordmark{margin-bottom:34px}#intro .brand-launch-actions{width:min(100%,420px);margin:0 auto;display:grid!important;grid-template-columns:1fr;gap:12px}#intro .main-menu-btn{width:100%;min-height:58px;margin:0!important;border-radius:17px!important;font-size:17px!important;font-weight:1000!important;letter-spacing:.035em!important}#intro .main-menu-play{background:linear-gradient(180deg,#ffd45c,#f7b928)!important;color:#080a0d!important;border-color:#ffe287!important;box-shadow:0 12px 28px rgba(247,185,40,.18)}#intro .brand-version{margin-top:10px;text-align:center}body.starting5-main-menu .topbar{display:none!important}body.starting5-main-menu .app-shell{padding-top:max(18px,env(safe-area-inset-top))}`;document.head.appendChild(style);const sync=()=>document.body.classList.toggle('starting5-main-menu',intro.classList.contains('active'));sync();new MutationObserver(sync).observe(intro,{attributes:true,attributeFilter:['class']});
  },0));
})();