/* NBA Starting5 v0.13.0-dev.2 — All-Star Weekend selection/presentation adapter only. */
(()=>{
  if(window.__starting5AllStarWeekendV01302)return;
  window.__starting5AllStarWeekendV01302=true;
  const SAVE_KEY='nbaStarting5SeasonV2';
  const EAST=new Set(['1610612737','1610612738','1610612751','1610612766','1610612741','1610612739','1610612765','1610612754','1610612748','1610612749','1610612752','1610612753','1610612755','1610612761','1610612764']);
  const POS=['PG','SG','SF','PF','C'],CATS=['scoring','dunks','three','rebounding','passing','blocks','steals'];
  const LABEL={scoring:'Scoring',dunks:'Dunking',three:'3PT',rebounding:'Rebounding',passing:'Passing',blocks:'Blocks',steals:'Steals'};
  const read=()=>{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch{return null}},write=s=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(s))}catch{}};
  const pool=()=>{try{return Array.isArray(players)?players.filter(p=>!p.classicTeam):[]}catch{return []}},key=p=>String(p?.id||p?.playerId||`${p?.teamId}|${p?.name}|${p?.position}`),stat=(p,k)=>Number(p?.stats?.[k]??0)||0;
  const logo=id=>`https://cdn.nba.com/logos/nba/${id}/global/L/logo.svg`,short=id=>{try{return window.TEAM_SHORT?.[id]||TEAM_SHORT?.[id]||pool().find(p=>String(p.teamId)===String(id))?.teamShort||'Team'}catch{return 'Team'}},activate=id=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');window.scrollTo(0,0)};
  const teamPlayers=id=>pool().filter(p=>String(p.teamId)===String(id));
  function gameMap(s){const m=new Map();for(const round of s?.schedule||[])for(const g of round||[])m.set(g.id,g);return m}
  function first41Ids(s){const ids=new Set();for(let i=0;i<Math.min(41,s?.schedule?.length||0);i++)for(const g of s.schedule[i]||[])if(s.results?.[g.id])ids.add(g.id);return ids}
  function categoryRows(s){if(window.STARTING5_MATCHUP_PLUS?.categoryRows)return window.STARTING5_MATCHUP_PLUS.categoryRows(s);const gm=gameMap(s),ids=first41Ids(s),rows=new Map(),ensure=p=>{const k=key(p);if(!rows.has(k))rows.set(k,{key:k,p,plus:Object.fromEntries(CATS.map(c=>[c,0])),total:0,games:0});return rows.get(k)};for(const id of ids){const g=gm.get(id);if(!g)continue;const hp=teamPlayers(g.home),ap=teamPlayers(g.away);for(const pos of POS){const h=hp.find(p=>p.position===pos),a=ap.find(p=>p.position===pos);if(!h||!a)continue;const hr=ensure(h),ar=ensure(a);for(const c of CATS){const d=stat(h,c)-stat(a,c);hr.plus[c]+=d;ar.plus[c]-=d;hr.total+=d;ar.total-=d}hr.games++;ar.games++}}return[...rows.values()]}
  function selectChampions(s){const rows=categoryRows(s),three=[...rows].sort((a,b)=>b.plus.three-a.plus.three||b.games-a.games||a.p.name.localeCompare(b.p.name))[0],dunk=[...rows].sort((a,b)=>b.plus.dunks-a.plus.dunks||b.games-a.games||a.p.name.localeCompare(b.p.name))[0];return{three,dunk,rows}}
  function selectAllStars(s){const rows=categoryRows(s),choose=(east,pos)=>rows.filter(r=>EAST.has(String(r.p.teamId))===east&&r.p.position===pos).sort((a,b)=>b.total-a.total||b.games-a.games||a.p.name.localeCompare(b.p.name))[0];return{east:POS.map(p=>choose(true,p)).filter(Boolean),west:POS.map(p=>choose(false,p)).filter(Boolean)}}

  const css=document.createElement('style');css.id='s5-allstar-weekend-style';css.textContent=`#seasonAllStarWeekend{padding-bottom:34px}.s5-asw-hero{border:1px solid rgba(255,255,255,.12);border-radius:22px;background:linear-gradient(180deg,#172131,#090d13);padding:18px;margin-bottom:12px;text-align:center}.s5-asw-kicker{font-size:10px;color:#f7b928;font-weight:1000;letter-spacing:.16em;text-transform:uppercase}.s5-asw-hero h2{font-size:28px;margin:5px 0}.s5-asw-hero p{margin:0;color:#9aa5b4;font-size:11px;line-height:1.4}.s5-asw-awards,.s5-as-rosters{display:grid;grid-template-columns:1fr 1fr;gap:10px}.s5-asw-award,.s5-as-team{border:1px solid rgba(255,255,255,.1);border-radius:18px;background:#0d131b;padding:12px}.s5-asw-award{text-align:center;padding:14px}.s5-asw-award img.team{width:58px;height:58px;object-fit:contain}.s5-asw-award h3{font-size:12px;color:#f7b928;text-transform:uppercase;letter-spacing:.08em;margin:6px 0}.s5-asw-award b{display:block;font-size:16px}.s5-asw-award small,.s5-as-row small{display:block;color:#8e98a7;font-size:8px;margin-top:4px}.s5-asw-score,.s5-as-plus{color:#f7b928;font-weight:1000}.s5-asw-score{font-size:12px;margin-top:6px}.s5-asw-play{width:100%;min-height:50px;border:0;border-radius:14px;background:#f7b928;color:#090b0f;font-weight:1000;font-size:15px;margin-top:12px}.s5-as-team h3{margin:0 0 8px;font-size:15px}.s5-as-row{display:grid;grid-template-columns:26px 1fr auto;gap:7px;align-items:center;padding:7px 0;border-top:1px solid rgba(255,255,255,.06)}.s5-as-row:first-of-type{border-top:0}.s5-as-row img{width:24px;height:24px;object-fit:contain}.s5-as-row b{display:block;font-size:10px}.s5-as-plus{font-size:10px}@media(max-width:430px){.s5-asw-awards,.s5-as-rosters{grid-template-columns:1fr 1fr}}`;document.head.appendChild(css);
  function ensureScreen(){let s=document.getElementById('seasonAllStarWeekend');if(s)return s;const shell=document.querySelector('.app-shell');if(!shell)return null;s=document.createElement('section');s.id='seasonAllStarWeekend';s.className='screen s5-season-screen';s.innerHTML='<div class="s5-season-head"><div><div class="s5-season-kicker">All-Star Weekend</div><h2>All-Star Weekend</h2></div><button class="ghost-btn" data-asw-back>← Season</button></div><div id="s5AllStarWeekendContent"></div>';shell.appendChild(s);s.querySelector('[data-asw-back]').addEventListener('click',()=>activate('seasonHub'));return s}
  function awardBox(title,r,cat){if(!r)return`<section class="s5-asw-award"><h3>${title}</h3><b>—</b></section>`;return`<section class="s5-asw-award"><img class="team" src="${logo(r.p.teamId)}" alt=""><h3>${title}</h3><b>${r.p.name}</b><small>${r.p.position} · ${short(r.p.teamId)}</small><div class="s5-asw-score">${r.plus[cat]>=0?'+':''}${r.plus[cat]} ${LABEL[cat]} matchup differential</div></section>`}
  function roster(title,list){return`<section class="s5-as-team"><h3>${title}</h3>${list.map(r=>`<div class="s5-as-row"><img src="${logo(r.p.teamId)}" alt=""><div><b>${r.p.name}</b><small>${r.p.position} · ${short(r.p.teamId)}</small></div><span class="s5-as-plus">${r.total>=0?'+':''}${r.total}</span></div>`).join('')}</section>`}
  function openChampions(){const s=read(),screen=ensureScreen();if(!s||!screen)return;const ch=selectChampions(s);s.allStarWeekend=s.allStarWeekend||{};s.allStarWeekend.skillChampions={complete:true,threePoint:{playerKey:ch.three?.key,name:ch.three?.p.name,teamId:ch.three?.p.teamId,plus:ch.three?.plus.three},slamDunk:{playerKey:ch.dunk?.key,name:ch.dunk?.p.name,teamId:ch.dunk?.p.teamId,plus:ch.dunk?.plus.dunks}};write(s);const host=screen.querySelector('#s5AllStarWeekendContent');host.innerHTML=`<section class="s5-asw-hero"><div class="s5-asw-kicker">First-Half Stat Leaders</div><h2>All-Star Weekend</h2><p>Leaders are based on actual matchup +/- through Game 41.</p></section><div class="s5-asw-awards">${awardBox('3PT Champion',ch.three,'three')}${awardBox('Dunk Champion',ch.dunk,'dunks')}</div><button class="s5-asw-play" data-as-next>Continue to All-Star Game</button>`;host.querySelector('[data-as-next]')?.addEventListener('click',openAllStarIntro);activate('seasonAllStarWeekend')}
  function openAllStarIntro(){const s=read(),screen=ensureScreen();if(!s||!screen)return;const r=selectAllStars(s),host=screen.querySelector('#s5AllStarWeekendContent');host.innerHTML=`<section class="s5-asw-hero"><div class="s5-asw-kicker">All-Star Game</div><h2>East vs West</h2><p>The highest cumulative matchup +/- player at each position through Game 41 represents each conference.</p></section><div class="s5-as-rosters">${roster('Eastern Conference',r.east)}${roster('Western Conference',r.west)}</div><button class="s5-asw-play" data-as-start>Play All-Star Game</button>`;activate('seasonAllStarWeekend')}
  window.STARTING5_ALLSTAR_WEEKEND={selectChampions,selectAllStars,openChampions,openAllStarIntro};
})();