/* NBA Starting5 v0.11.74 — All-Star Weekend driven by actual matchup +/- ledger. */
(()=>{
  if(window.__starting5AllStarWeekendV01158)return;
  window.__starting5AllStarWeekendV01158=true;
  const SAVE_KEY='nbaStarting5SeasonV2';
  const EAST=new Set(['1610612737','1610612738','1610612751','1610612766','1610612741','1610612739','1610612765','1610612754','1610612748','1610612749','1610612752','1610612753','1610612755','1610612761','1610612764']);
  const POS=['PG','SG','SF','PF','C'];
  const CATS=['scoring','dunks','three','rebounding','passing','blocks','steals'];
  const LABEL={scoring:'Scoring',dunks:'Dunking',three:'3PT',rebounding:'Rebounding',passing:'Passing',blocks:'Blocks',steals:'Steals'};
  const read=()=>{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch{return null}};
  const write=s=>localStorage.setItem(SAVE_KEY,JSON.stringify(s));
  const pool=()=>{try{return Array.isArray(players)?players.filter(p=>!p.classicTeam):[]}catch{return []}};
  const key=p=>String(p?.id||p?.playerId||`${p?.teamId}|${p?.name}|${p?.position}`);
  const stat=(p,k)=>Number(p?.stats?.[k]??0)||0;
  const logo=id=>`https://cdn.nba.com/logos/nba/${id}/global/L/logo.svg`;
  const short=id=>{try{return window.TEAM_SHORT?.[id]||TEAM_SHORT?.[id]||pool().find(p=>String(p.teamId)===String(id))?.teamShort||'Team'}catch{return 'Team'}};
  const played=s=>{const r=s?.records?.[s?.teamId]||{w:0,l:0};return (+r.w||0)+(+r.l||0)};
  const activate=id=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');window.scrollTo(0,0)};
  const teamPlayers=id=>pool().filter(p=>String(p.teamId)===String(id));
  function gameMap(s){const m=new Map();for(const round of s?.schedule||[])for(const g of round||[])m.set(g.id,g);return m}
  function first41Ids(s){const ids=new Set();for(let i=0;i<Math.min(41,s?.schedule?.length||0);i++)for(const g of s.schedule[i]||[])if(s.results?.[g.id])ids.add(g.id);return ids}
  function categoryRows(s){
    if(window.STARTING5_MATCHUP_PLUS?.categoryRows)return window.STARTING5_MATCHUP_PLUS.categoryRows(s);
    const gm=gameMap(s),ids=first41Ids(s),rows=new Map();
    const ensure=p=>{const k=key(p);if(!rows.has(k))rows.set(k,{key:k,p,plus:Object.fromEntries(CATS.map(c=>[c,0])),total:0,games:0});return rows.get(k)};
    for(const id of ids){const g=gm.get(id);if(!g)continue;const hp=teamPlayers(g.home),ap=teamPlayers(g.away);for(const pos of POS){const h=hp.find(p=>p.position===pos),a=ap.find(p=>p.position===pos);if(!h||!a)continue;const hr=ensure(h),ar=ensure(a);for(const c of CATS){const d=stat(h,c)-stat(a,c);hr.plus[c]+=d;ar.plus[c]-=d;hr.total+=d;ar.total-=d}hr.games++;ar.games++;}}
    return [...rows.values()];
  }
  function selectChampions(s){const rows=categoryRows(s);const three=[...rows].sort((a,b)=>b.plus.three-a.plus.three||b.games-a.games||a.p.name.localeCompare(b.p.name))[0];const dunk=[...rows].sort((a,b)=>b.plus.dunks-a.plus.dunks||b.games-a.games||a.p.name.localeCompare(b.p.name))[0];return {three,dunk,rows}}
  function selectAllStars(s){const rows=categoryRows(s);const choose=(east,pos)=>rows.filter(r=>EAST.has(String(r.p.teamId))===east&&r.p.position===pos).sort((a,b)=>b.total-a.total||b.games-a.games||a.p.name.localeCompare(b.p.name))[0];return {east:POS.map(p=>choose(true,p)).filter(Boolean),west:POS.map(p=>choose(false,p)).filter(Boolean)};}
  const css=document.createElement('style');css.id='s5-allstar-weekend-style';css.textContent=`
    #seasonAllStarWeekend{padding-bottom:34px}.s5-asw-hero{border:1px solid rgba(255,255,255,.12);border-radius:22px;background:linear-gradient(180deg,#172131,#090d13);padding:18px;margin-bottom:12px;text-align:center}.s5-asw-kicker{font-size:10px;color:#f7b928;font-weight:1000;letter-spacing:.16em;text-transform:uppercase}.s5-asw-hero h2{font-size:28px;margin:5px 0}.s5-asw-hero p{margin:0;color:#9aa5b4;font-size:11px;line-height:1.4}.s5-asw-awards{display:grid;grid-template-columns:1fr 1fr;gap:10px}.s5-asw-award{border:1px solid rgba(255,255,255,.1);border-radius:18px;background:#0d131b;padding:14px;text-align:center}.s5-asw-award img.team{width:58px;height:58px;object-fit:contain}.s5-asw-award h3{font-size:12px;color:#f7b928;text-transform:uppercase;letter-spacing:.08em;margin:6px 0}.s5-asw-award b{display:block;font-size:16px}.s5-asw-award small{display:block;color:#8e98a7;font-size:8px;margin-top:4px}.s5-asw-score{font-size:12px;color:#f7b928;font-weight:1000;margin-top:6px}.s5-asw-play{width:100%;min-height:50px;border:0;border-radius:14px;background:#f7b928;color:#090b0f;font-weight:1000;font-size:15px;margin-top:12px}
    .s5-as-rosters{display:grid;grid-template-columns:1fr 1fr;gap:10px}.s5-as-team{border:1px solid rgba(255,255,255,.1);border-radius:18px;background:#0d131b;padding:12px}.s5-as-team h3{margin:0 0 8px;font-size:15px}.s5-as-row{display:grid;grid-template-columns:26px 1fr auto;gap:7px;align-items:center;padding:7px 0;border-top:1px solid rgba(255,255,255,.06)}.s5-as-row:first-of-type{border-top:0}.s5-as-row img{width:24px;height:24px;object-fit:contain}.s5-as-row b{display:block;font-size:10px}.s5-as-row small{display:block;color:#7f8998;font-size:7.5px;margin-top:2px}.s5-as-plus{color:#f7b928;font-size:10px;font-weight:1000}
    .s5-as-gamehead{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:8px;border:1px solid rgba(255,255,255,.11);border-radius:18px;background:#0c121a;padding:12px;margin-bottom:10px}.s5-as-score{text-align:center}.s5-as-score strong{display:block;font-size:28px}.s5-as-score span{font-size:8px;color:#8f99a8;font-weight:1000;text-transform:uppercase}.s5-as-cat{text-align:center}.s5-as-cat b{display:block;color:#f7b928;font-size:14px}.s5-as-cat span{font-size:8px;color:#8f99a8}.s5-as-cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.s5-as-card{min-width:0;cursor:pointer}.s5-as-card .player-card{width:100%!important;margin:0!important;max-width:none!important}.s5-as-card.used{opacity:.35;pointer-events:none}.s5-as-result{margin-top:10px;border:1px solid rgba(255,255,255,.09);border-radius:15px;background:#0d131b;padding:12px;text-align:center;font-size:11px}.s5-as-final{text-align:center;border:1px solid rgba(247,185,40,.35);border-radius:20px;background:linear-gradient(180deg,#171f2b,#090d13);padding:22px 16px}.s5-as-final h2{font-size:28px;margin:5px 0}.s5-as-final p{color:#9aa5b4;font-size:11px}.s5-as-mvp{margin:16px auto 0;max-width:280px;border-top:1px solid rgba(255,255,255,.08);padding-top:14px}.s5-as-mvp img{width:54px;height:54px;object-fit:contain}.s5-as-mvp b{display:block;font-size:18px;margin-top:5px}.s5-as-mvp span{display:block;color:#f7b928;font-size:10px;font-weight:1000;margin-top:4px}
    @media(max-width:430px){.s5-asw-awards,.s5-as-rosters{grid-template-columns:1fr 1fr}.s5-as-cards{grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}}
  `;document.head.appendChild(css);
  function ensureScreen(){let s=document.getElementById('seasonAllStarWeekend');if(s)return s;const shell=document.querySelector('.app-shell');if(!shell)return null;s=document.createElement('section');s.id='seasonAllStarWeekend';s.className='screen s5-season-screen';s.innerHTML='<div class="s5-season-head"><div><div class="s5-season-kicker">All-Star Weekend</div><h2>All-Star Weekend</h2></div><button class="ghost-btn" data-asw-back>← Season</button></div><div id="s5AllStarWeekendContent"></div>';shell.appendChild(s);s.querySelector('[data-asw-back]').addEventListener('click',()=>activate('seasonHub'));return s}
  function awardBox(title,r,cat){if(!r)return `<section class="s5-asw-award"><h3>${title}</h3><b>—</b></section>`;return `<section class="s5-asw-award"><img class="team" src="${logo(r.p.teamId)}" alt=""><h3>${title}</h3><b>${r.p.name}</b><small>${r.p.position} · ${short(r.p.teamId)}</small><div class="s5-asw-score">${r.plus[cat]>=0?'+':''}${r.plus[cat]} ${LABEL[cat]} matchup differential</div></section>`}
  function openChampions(){const s=read(),screen=ensureScreen();if(!s||!screen)return;const ch=selectChampions(s);s.allStarWeekend=s.allStarWeekend||{};s.allStarWeekend.skillChampions={complete:true,threePoint:{playerKey:ch.three?.key,name:ch.three?.p.name,teamId:ch.three?.p.teamId,plus:ch.three?.plus.three},slamDunk:{playerKey:ch.dunk?.key,name:ch.dunk?.p.name,teamId:ch.dunk?.p.teamId,plus:ch.dunk?.plus.dunks}};write(s);const host=screen.querySelector('#s5AllStarWeekendContent');host.innerHTML=`<section class="s5-asw-hero"><div class="s5-asw-kicker">First-Half Stat Leaders</div><h2>All-Star Weekend</h2><p>Leaders are based only on the +/- margin from actual simulated matchups through Game 41.</p></section><div class="s5-asw-awards">${awardBox('3PT Champion',ch.three,'three')}${awardBox('Dunk Champion',ch.dunk,'dunks')}</div><button class="s5-asw-play" data-as-next>Continue to All-Star Game</button>`;host.querySelector('[data-as-next]')?.addEventListener('click',openAllStarIntro);activate('seasonAllStarWeekend')}
  function roster(title,list){return `<section class="s5-as-team"><h3>${title}</h3>${list.map(r=>`<div class="s5-as-row"><img src="${logo(r.p.teamId)}" alt=""><div><b>${r.p.name}</b><small>${r.p.position} · ${short(r.p.teamId)}</small></div><span class="s5-as-plus">${r.total>=0?'+':''}${r.total}</span></div>`).join('')}</section>`}
  function openAllStarIntro(){const s=read(),screen=ensureScreen();if(!s||!screen)return;const r=selectAllStars(s),host=screen.querySelector('#s5AllStarWeekendContent');host.innerHTML=`<section class="s5-asw-hero"><div class="s5-asw-kicker">All-Star Game</div><h2>East vs West</h2><p>The highest cumulative actual matchup +/- player at each position through Game 41 represents each conference. PG, SG, SF, PF and C are required.</p></section><div class="s5-as-rosters">${roster('Eastern Conference',r.east)}${roster('Western Conference',r.west)}</div><button class="s5-asw-play" data-as-start>Play All-Star Game</button>`;host.querySelector('[data-as-start]')?.addEventListener('click',()=>startGame(r));activate('seasonAllStarWeekend')}
  let game=null;
  function startGame(r){const s=read();if(!s)return;const userEast=EAST.has(String(s.teamId)),user=(userEast?r.east:r.west).map(x=>x.p),cpu=(userEast?r.west:r.east).map(x=>x.p);game={user,cpu,userName:userEast?'EAST':'WEST',cpuName:userEast?'WEST':'EAST',u:0,c:0,usedU:new Set(),usedC:new Set(),round:1,category:null,history:[]};nextRound()}
  function nextRound(){if(!game)return;if(game.round>5){finish();return}game.category=CATS[Math.floor(Math.random()*CATS.length)];renderGame()}
  function renderGame(){const host=ensureScreen()?.querySelector('#s5AllStarWeekendContent'),cat=game.category,pos=POS[game.round-1];if(!host)return;host.innerHTML=`<div class="s5-as-gamehead"><div class="s5-as-score"><span>${game.userName}</span><strong>${game.u}</strong></div><div class="s5-as-cat"><span>${pos} · Matchup ${game.round} of 5</span><b>${LABEL[cat]}</b></div><div class="s5-as-score"><span>${game.cpuName}</span><strong>${game.c}</strong></div></div><div class="s5-as-cards">${game.user.map(p=>`<div class="s5-as-card ${game.usedU.has(key(p))||p.position!==pos?'used':''}" data-as-player="${key(p)}">${typeof cardMarkup==='function'?cardMarkup(p,{activeStat:cat,eager:true}):`<div>${p.name}</div>`}</div>`).join('')}</div><div class="s5-as-result">Choose your ${pos}. Position lock applies in the All-Star Game.</div>`;host.querySelectorAll('[data-as-player]').forEach(el=>el.addEventListener('click',()=>play(el.dataset.asPlayer)));activate('seasonAllStarWeekend')}
  function play(k){const pos=POS[game.round-1],u=game.user.find(p=>key(p)===k&&p.position===pos);if(!u||game.usedU.has(k))return;const c=game.cpu.find(p=>p.position===pos&&!game.usedC.has(key(p)));if(!c)return;const uv=stat(u,game.category),cv=stat(c,game.category),diff=uv-cv;game.usedU.add(key(u));game.usedC.add(key(c));if(diff>0)game.u++;else if(diff<0)game.c++;game.history.push({round:game.round,position:pos,category:game.category,user:u.name,userKey:key(u),userTeamId:u.teamId,cpu:c.name,cpuKey:key(c),cpuTeamId:c.teamId,uv,cv,userDiff:diff,cpuDiff:-diff});const host=document.getElementById('s5AllStarWeekendContent'),res=host?.querySelector('.s5-as-result');if(res)res.innerHTML=`<b>${u.name} ${uv} — ${cv} ${c.name}</b><br>${diff>0?game.userName+' wins the matchup':diff<0?game.cpuName+' wins the matchup':'Tie matchup'}`;host?.querySelectorAll('.s5-as-card').forEach(x=>x.style.pointerEvents='none');setTimeout(()=>{game.round++;nextRound()},900)}
  function mvpFromHistory(){let best=null;for(const h of game.history){const a={name:h.user,key:h.userKey,teamId:h.userTeamId,diff:h.userDiff},b={name:h.cpu,key:h.cpuKey,teamId:h.cpuTeamId,diff:h.cpuDiff};if(a.diff>0&&(!best||a.diff>best.diff))best=a;if(b.diff>0&&(!best||b.diff>best.diff))best=b}return best||{name:game.history[0]?.user||'—',teamId:game.history[0]?.userTeamId,diff:0}}
  function finish(){const s=read();if(!s)return;const winner=game.u===game.c?'TIE':game.u>game.c?game.userName:game.cpuName,mvp=mvpFromHistory();s.allStarWeekend=s.allStarWeekend||{};s.allStarWeekend.allStarGame={complete:true,winner,score:`${game.u}-${game.c}`,mvp,history:game.history,completedAt:new Date().toISOString()};write(s);const host=document.getElementById('s5AllStarWeekendContent');if(host)host.innerHTML=`<section class="s5-as-final"><div class="s5-asw-kicker">All-Star Game Final</div><h2>${winner==='TIE'?'All-Star Game ends tied':winner+' wins'}</h2><p>${game.userName} ${game.u} — ${game.c} ${game.cpuName}</p><div class="s5-as-mvp">${mvp.teamId?`<img src="${logo(mvp.teamId)}" alt="">`:''}<div class="s5-asw-kicker">All-Star MVP</div><b>${mvp.name}</b><span>+${mvp.diff} best matchup differential</span></div><button class="s5-asw-play" data-as-finish>Continue to Game 42</button></section>`;host?.querySelector('[data-as-finish]')?.addEventListener('click',()=>{activate('seasonHub');setTimeout(refreshHubButton,0)});refreshHubButton()}
  function weekendComplete(s){return !!s?.allStarWeekend?.allStarGame?.complete}
  function refreshHubButton(){const s=read(),btn=document.getElementById('s5PlaySeasonGame');if(!s||!btn||played(s)!==41)return;if(!s.allStarWeekend?.risingStars?.complete)return;const label=btn.closest('.s5-next')?.querySelector('.s5-next-label'),wanted='ALL-STAR WEEKEND · BETWEEN GAMES 41 & 42';if(!s.allStarWeekend?.skillChampions?.complete){if(btn.textContent!=='All-Star Weekend — Saturday Night')btn.textContent='All-Star Weekend — Saturday Night';if(label&&label.textContent!==wanted)label.textContent=wanted;return}if(!weekendComplete(s)){if(btn.textContent!=='All-Star Weekend — All-Star Game')btn.textContent='All-Star Weekend — All-Star Game';if(label&&label.textContent!==wanted)label.textContent=wanted;return}}
  document.addEventListener('click',e=>{const btn=e.target.closest('#s5PlaySeasonGame');if(!btn)return;const s=read();if(!s||played(s)!==41||!s.allStarWeekend?.risingStars?.complete||weekendComplete(s))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(!s.allStarWeekend?.skillChampions?.complete)openChampions();else openAllStarIntro()},true);
  const start=()=>refreshHubButton();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshHubButton()});window.addEventListener('pageshow',refreshHubButton);
  window.STARTING5_ALLSTAR_WEEKEND={openChampions,openAllStarIntro,selectChampions,selectAllStars};
})();