/* NBA Starting5 v0.13.2 — two-cycle Season free agency + transaction ticker. Event-driven; no polling. */
(()=>{
  if(window.__starting5SeasonFreeAgencyV0132)return;window.__starting5SeasonFreeAgencyV0132=true;
  const SAVE_KEY='nbaStarting5SeasonV2',ACTIVE_KEY='nbaStarting5SeasonGameUiV1',PENDING_KEY='nbaStarting5SeasonPendingGameV1';
  const TEAM_IDS=['1610612737','1610612738','1610612751','1610612766','1610612741','1610612739','1610612742','1610612743','1610612765','1610612744','1610612745','1610612754','1610612746','1610612747','1610612763','1610612748','1610612749','1610612750','1610612740','1610612752','1610612760','1610612753','1610612755','1610612756','1610612757','1610612758','1610612759','1610612761','1610612762','1610612764'];
  const TEAM_NAMES={'1610612737':'Atlanta Hawks','1610612738':'Boston Celtics','1610612751':'Brooklyn Nets','1610612766':'Charlotte Hornets','1610612741':'Chicago Bulls','1610612739':'Cleveland Cavaliers','1610612742':'Dallas Mavericks','1610612743':'Denver Nuggets','1610612765':'Detroit Pistons','1610612744':'Golden State Warriors','1610612745':'Houston Rockets','1610612754':'Indiana Pacers','1610612746':'LA Clippers','1610612747':'Los Angeles Lakers','1610612763':'Memphis Grizzlies','1610612748':'Miami Heat','1610612749':'Milwaukee Bucks','1610612750':'Minnesota Timberwolves','1610612740':'New Orleans Pelicans','1610612752':'New York Knicks','1610612760':'Oklahoma City Thunder','1610612753':'Orlando Magic','1610612755':'Philadelphia 76ers','1610612756':'Phoenix Suns','1610612757':'Portland Trail Blazers','1610612758':'Sacramento Kings','1610612759':'San Antonio Spurs','1610612761':'Toronto Raptors','1610612762':'Utah Jazz','1610612764':'Washington Wizards'};
  const SHORT={'1610612737':'Hawks','1610612738':'Celtics','1610612751':'Nets','1610612766':'Hornets','1610612741':'Bulls','1610612739':'Cavaliers','1610612742':'Mavericks','1610612743':'Nuggets','1610612765':'Pistons','1610612744':'Warriors','1610612745':'Rockets','1610612754':'Pacers','1610612746':'Clippers','1610612747':'Lakers','1610612763':'Grizzlies','1610612748':'Heat','1610612749':'Bucks','1610612750':'Timberwolves','1610612740':'Pelicans','1610612752':'Knicks','1610612760':'Thunder','1610612753':'Magic','1610612755':'76ers','1610612756':'Suns','1610612757':'Trail Blazers','1610612758':'Kings','1610612759':'Spurs','1610612761':'Raptors','1610612762':'Jazz','1610612764':'Wizards'};
  const POS={PG:0,SG:1,SF:2,PF:3,C:4},CATS=['scoring','dunks','three','rebounding','passing','blocks','steals'];
  const CHECKPOINTS=[10,15,20,30,35,40];
  const read=()=>{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch{return null}};
  const write=s=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(s))}catch{}};
  const runtimePool=()=>{try{return Array.isArray(players)?players:[]}catch{return []}};
  const slug=s=>String(s||'player').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const clone=o=>{try{return JSON.parse(JSON.stringify(o))}catch{return o}};
  const overall=p=>{try{if(typeof window.courtsideOverall==='function')return Number(window.courtsideOverall(p))||0}catch{}const v=CATS.map(k=>Number(p?.stats?.[k])||0);return v.reduce((a,b)=>a+b,0)/v.length};
  const logo=id=>`https://cdn.nba.com/logos/nba/${id}/global/L/logo.svg`;
  const playerKey=p=>String(p?.playerId||p?.id||`${p?.name||''}|${p?.position||''}`);
  function rosterNow(id){return runtimePool().filter(p=>String(p.teamId)===String(id)&&!p.classicTeam&&!p.__s5FreeAgent).sort((a,b)=>(POS[a.position]??9)-(POS[b.position]??9)).slice(0,5)}
  function snap(p){return{id:String(p?.id||`fa-${slug(p?.name)}`),playerId:String(p?.playerId||p?.id||`fa-${slug(p?.name)}`),name:p?.name||'Player',position:p?.position||'SF',stats:clone(p?.stats||{}),artSlug:p?.artSlug||slug(p?.name),art:clone(p?.art||{x:50,y:100,s:.76,r:0}),theme:clone(p?.theme||null),season:p?.season||'2026–27',sourceTeam:p?.sourceTeam||p?.team||''}}
  function buildInitialPool(){const src=window.NBA_STARTING5_SEASON_FREE_AGENTS||window.nbaStarting5SeasonFreeAgents||[];return src.map(f=>{const rich=runtimePool().find(p=>p.name===f.name&&!p.classicTeam);const x=snap(rich||f);x.id=f.id||x.id;x.playerId=rich?.playerId||f.playerId||x.playerId;x.position=f.position||x.position;x.stats=clone(f.stats||x.stats);x.sourceTeam=f.sourceTeam||x.sourceTeam;return x})}
  function ensureState(s){
    s.freeAgency=s.freeAgency||{};const f=s.freeAgency;
    f.version=2;f.pool=Array.isArray(f.pool)?f.pool:buildInitialPool();f.rosters=f.rosters||{};
    for(const id of TEAM_IDS){if(!Array.isArray(f.rosters[id])||f.rosters[id].length!==5){const r=rosterNow(id);if(r.length===5)f.rosters[id]=r.map(snap)}}
    f.served=f.served||{'1':[],'2':[]};f.served['1']=Array.isArray(f.served['1'])?f.served['1']:[];f.served['2']=Array.isArray(f.served['2'])?f.served['2']:[];
    f.processed=Array.isArray(f.processed)?f.processed:[];f.transactions=Array.isArray(f.transactions)?f.transactions:[];if(!('pendingUser'in f))f.pendingUser=null;
    return f;
  }
  function decoratePlayer(p,id){const n=SHORT[id]||'Team',full=TEAM_NAMES[id]||n;return{...clone(p),teamId:String(id),team:full,teamFull:full,teamShort:n,season:'2026–27',freeAgent:false,__s5FreeAgent:false}}
  function syncRuntime(s){const f=s?.freeAgency;if(!f?.rosters)return;const pool=runtimePool();if(!Array.isArray(pool))return;
    for(const p of pool){if(p.classicTeam)continue;const tid=String(p.teamId||'');if(!TEAM_IDS.includes(tid))continue;const wanted=f.rosters[tid]||[];if(!wanted.some(x=>playerKey(x)===playerKey(p)||x.name===p.name)){p.teamId='__S5_FA__';p.freeAgent=true;p.__s5FreeAgent=true}}
    for(const id of TEAM_IDS){for(const row of f.rosters[id]||[]){let p=pool.find(x=>!x.classicTeam&&(playerKey(x)===playerKey(row)||x.name===row.name));const d=decoratePlayer(row,id);if(p)Object.assign(p,d);else{p=d;pool.push(p)}}}
  }
  function worstFirst(s,ids=TEAM_IDS){return [...ids].sort((a,b)=>{const A=s.records?.[a]||{w:0,l:0},B=s.records?.[b]||{w:0,l:0},ag=A.w+A.l,bg=B.w+B.l,ap=ag?A.w/ag:0,bp=bg?B.w/bg:0;return ap-bp||B.l-A.l||A.w-B.w||String(a).localeCompare(String(b))})}
  function played(s){const r=s?.records?.[s.teamId]||{w:0,l:0};return Math.max(Number(s?.roundIndex)||0,(Number(r.w)||0)+(Number(r.l)||0))}
  function cycleFor(cp){return cp<=20?1:2}
  function groupFor(s,cp){const f=ensureState(s),cycle=String(cycleFor(cp)),served=new Set(f.served[cycle].map(String)),left=TEAM_IDS.filter(id=>!served.has(id));if(cp===20||cp===40)return worstFirst(s,left);return worstFirst(s,left).slice(0,10)}
  function transaction(f,teamId,signed,dropped,game){f.transactions.push({game,teamId:String(teamId),signed:signed.name,dropped:dropped.name,at:Date.now()});if(f.transactions.length>24)f.transactions=f.transactions.slice(-24)}
  function makeSwap(s,teamId,faIndex){const f=ensureState(s),fa=f.pool[faIndex],r=f.rosters[teamId];if(!fa||!Array.isArray(r))return false;const dropIndex=r.findIndex(p=>p.position===fa.position);if(dropIndex<0)return false;const dropped=r[dropIndex];r[dropIndex]=decoratePlayer(fa,teamId);f.pool.splice(faIndex,1);const back=snap(dropped);back.sourceTeam=TEAM_NAMES[teamId]||dropped.sourceTeam;f.pool.push(back);transaction(f,teamId,fa,dropped,played(s));return true}
  function cpuProbability(rank){if(rank<3)return .84;if(rank<10)return .65;if(rank<20)return .4;if(rank<25)return .23;return .1}
  function cpuThreshold(rank){if(rank<3)return .35;if(rank<10)return .8;if(rank<20)return 1.6;return 3}
  function cpuAct(s,teamId,rank){const f=ensureState(s);if(Math.random()>cpuProbability(rank))return false;const r=f.rosters[teamId]||[];let best=null;f.pool.forEach((fa,i)=>{const starter=r.find(p=>p.position===fa.position);if(!starter)return;const gain=overall(fa)-overall(starter);if(!best||gain>best.gain)best={i,gain}});if(!best||best.gain<cpuThreshold(rank))return false;return makeSwap(s,teamId,best.i)}
  function processCheckpoint(s,cp){const f=ensureState(s);if(f.processed.includes(cp))return;const cycle=String(cycleFor(cp)),group=groupFor(s,cp),ranks=worstFirst(s);for(const id of group){if(!f.served[cycle].includes(id))f.served[cycle].push(id)}f.processed.push(cp);
    for(const id of group){if(String(id)===String(s.teamId)){f.pendingUser={checkpoint:cp,cycle:Number(cycle),opened:false};continue}cpuAct(s,id,ranks.indexOf(id))}
  }
  function processDue(){const s=read();if(!s)return null;const f=ensureState(s),n=played(s);for(const cp of CHECKPOINTS){if(n>=cp&&!f.processed.includes(cp))processCheckpoint(s,cp)}write(s);syncRuntime(s);return f.pendingUser}
  function otherFeatureDue(s){const n=played(s);if(s?.playerOfWeek?.pending||s?.whosHotNot?.pending)return true;if(n>0&&n%4===0)return true;if(n>=6&&(n-6)%4===0)return true;return false}
  function ensureScreen(){let screen=document.getElementById('seasonFreeAgency');if(screen)return screen;const shell=document.querySelector('.app-shell');if(!shell)return null;screen=document.createElement('section');screen.id='seasonFreeAgency';screen.className='screen s5-fa-screen';screen.innerHTML=`<div class="s5-fa-kicker">NBA STARTING5</div><h2>FREE AGENCY WINDOW</h2><div class="s5-fa-sub"></div><div class="s5-fa-roster"></div><div class="s5-fa-list"></div><button type="button" class="ghost-btn s5-fa-skip">Skip Free Agency</button>`;shell.appendChild(screen);screen.querySelector('.s5-fa-skip').addEventListener('click',()=>finishUser(false));return screen}
  function candidateMarkup(s,fa,i){const f=ensureState(s),r=f.rosters[s.teamId]||[],drop=r.find(p=>p.position===fa.position),gain=drop?overall(fa)-overall(drop):0,sign=gain>0?`+${gain.toFixed(1)}`:gain.toFixed(1);return `<button type="button" class="s5-fa-option" data-fa-index="${i}"><div class="s5-fa-option-main"><strong>${fa.name}</strong><span>${fa.position} · ${fa.sourceTeam||'Free Agent'}</span></div><div class="s5-fa-swap"><b>${sign}</b><span>replaces ${drop?.name||'—'}</span></div></button>`}
  function showFreeAgency(){const s=read(),f=s&&ensureState(s);if(!s||!f?.pendingUser)return false;const screen=ensureScreen();if(!screen)return false;const cp=f.pendingUser.checkpoint,rec=s.records?.[s.teamId]||{w:0,l:0};screen.querySelector('.s5-fa-sub').textContent=`AFTER GAME ${cp} · ${SHORT[s.teamId]||'YOUR TEAM'} ${rec.w}-${rec.l} · ONE MOVE OR SKIP`;screen.querySelector('.s5-fa-roster').innerHTML=(f.rosters[s.teamId]||[]).map(p=>`<span><b>${p.position}</b> ${p.name}</span>`).join('');const list=screen.querySelector('.s5-fa-list');const rows=f.pool.map((fa,i)=>({fa,i,drop:(f.rosters[s.teamId]||[]).find(p=>p.position===fa.position)})).filter(x=>x.drop).sort((a,b)=>(overall(b.fa)-overall(b.drop))-(overall(a.fa)-overall(a.drop)));list.innerHTML=rows.map(x=>candidateMarkup(s,x.fa,x.i)).join('')||'<div class="s5-fa-empty">No eligible free agents are available.</div>';list.querySelectorAll('[data-fa-index]').forEach(b=>b.addEventListener('click',()=>finishUser(true,Number(b.dataset.faIndex))));document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));screen.classList.add('active');f.pendingUser.opened=true;write(s);window.scrollTo({top:0,behavior:'instant'});return true}
  function finishUser(sign,index){const s=read();if(!s)return;const f=ensureState(s);if(sign&&Number.isInteger(index))makeSwap(s,String(s.teamId),index);f.pendingUser=null;write(s);syncRuntime(s);try{sessionStorage.removeItem(ACTIVE_KEY);sessionStorage.removeItem(PENDING_KEY)}catch{}window.STARTING5_SEASON_MODE?.renderHub?.();injectTicker();try{showScreen('seasonHub')}catch{}window.scrollTo({top:0,behavior:'instant'})}
  function tickerText(s){const t=s?.freeAgency?.transactions||[];if(!t.length)return '';return t.slice(-10).flatMap(x=>[`${SHORT[x.teamId]||'Team'} signed ${x.signed}`,`${SHORT[x.teamId]||'Team'} dropped ${x.dropped}`]).join('  •  ')}
  function injectTicker(){const s=read(),hub=document.getElementById('seasonHub'),content=document.getElementById('s5SeasonContent');if(!s||!hub||!content)return;const old=document.getElementById('s5TransactionTicker'),text=tickerText(s);if(!text){old?.remove();return}let ticker=old;if(!ticker){ticker=document.createElement('section');ticker.id='s5TransactionTicker';ticker.className='s5-news-ticker';const hero=content.querySelector('.s5-season-hero');if(hero)hero.insertAdjacentElement('afterend',ticker);else content.prepend(ticker)}ticker.innerHTML=`<div class="s5-news-tag">LEAGUE NEWS</div><div class="s5-news-window"><div class="s5-news-track"><span>${text}</span><span aria-hidden="true">${text}</span></div></div>`}
  }
  const style=document.createElement('style');style.textContent=`
  .s5-news-ticker{height:38px;margin:-2px 0 11px;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:#080c12;display:grid;grid-template-columns:auto 1fr;align-items:center;overflow:hidden}.s5-news-tag{align-self:stretch;display:flex;align-items:center;padding:0 10px;background:#f7b928;color:#090b0f;font-size:8px;font-weight:1000;letter-spacing:.09em;white-space:nowrap;z-index:2}.s5-news-window{min-width:0;overflow:hidden;white-space:nowrap}.s5-news-track{display:inline-flex;min-width:max-content;will-change:transform;animation:s5Ticker 26s linear infinite}.s5-news-track span{padding-right:44px;font-size:10px;font-weight:900;color:#e7ebf2}.s5-news-track span:before{content:'TRANSACTIONS  •  ';color:#7f8998}@keyframes s5Ticker{from{transform:translateX(0)}to{transform:translateX(-50%)}}
  .s5-fa-screen{padding:9px 14px 28px!important}.s5-fa-kicker{text-align:center;color:#f7b928;font-size:10px;font-weight:1000;letter-spacing:.18em}.s5-fa-screen h2{text-align:center;margin:5px 0 4px;font-size:27px;line-height:1}.s5-fa-sub{text-align:center;color:#98a2b1;font-size:9px;font-weight:900;letter-spacing:.06em;margin-bottom:12px}.s5-fa-roster{display:grid;grid-template-columns:1fr;gap:5px;border:1px solid rgba(255,255,255,.09);border-radius:14px;background:#0b1017;padding:9px;margin-bottom:10px}.s5-fa-roster span{font-size:9px;color:#b6bec9;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.s5-fa-roster b{display:inline-block;width:25px;color:#f7b928}.s5-fa-list{display:grid;gap:7px;max-height:55vh;overflow-y:auto;padding:1px}.s5-fa-option{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;text-align:left;border:1px solid rgba(255,255,255,.1);border-radius:14px;background:linear-gradient(180deg,#141b25,#0c1118);color:#fff;padding:11px}.s5-fa-option-main strong{display:block;font-size:13px}.s5-fa-option-main span,.s5-fa-swap span{display:block;margin-top:3px;color:#8f99a8;font-size:8px;font-weight:800}.s5-fa-swap{text-align:right;max-width:130px}.s5-fa-swap b{font-size:13px;color:#f7b928}.s5-fa-swap span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.s5-fa-skip{width:100%;min-height:49px;margin-top:11px}.s5-fa-empty{text-align:center;color:#929cab;padding:24px;font-size:11px}@media(max-width:390px){.s5-news-tag{padding:0 8px}.s5-fa-screen{padding-left:10px!important;padding-right:10px!important}.s5-fa-screen h2{font-size:24px}}
  `;document.head.appendChild(style);
  window.addEventListener('s5:game-finished',()=>{processDue()});
  window.addEventListener('s5:season-continue-request',e=>{const p=processDue(),s=read();if(!p||otherFeatureDue(s))return;e.preventDefault();showFreeAgency()});
  window.addEventListener('click',e=>{if(e.target?.closest?.('#seasonModeBtn'))requestAnimationFrame(()=>{processDue();injectTicker()});if(e.target?.closest?.('.s5-hotnot-continue,.s5-potw-continue'))queueMicrotask(()=>{const s=read();const p=processDue();if(p&&!s?.playerOfWeek?.pending&&!s?.whosHotNot?.pending)showFreeAgency();else requestAnimationFrame(injectTicker)})},true);
  window.addEventListener('s5:player-of-week-open',()=>{});
  window.STARTING5_SEASON_FREE_AGENCY={processDue,showFreeAgency,injectTicker,syncRuntime};
  function start(){ensureScreen();const s=read();if(s?.freeAgency){ensureState(s);syncRuntime(s);write(s)}requestAnimationFrame(injectTicker)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
