/* NBA Courtside v0.10.17 — full awards races + All-Star Weekend */
(()=>{
  if(window.__courtsideSeasonAwardsAllStarV01017)return;
  window.__courtsideSeasonAwardsAllStarV01017=true;
  const SAVE_KEY='nbaCourtsideSeasonModeV1',ACTIVE_KEY='nbaCourtsideSeasonGameActiveV1',ALLSTAR_KEY='nbaCourtsideAllStarActiveV1';
  const EAST=new Set(['1610612737','1610612738','1610612751','1610612766','1610612741','1610612739','1610612765','1610612754','1610612748','1610612749','1610612752','1610612753','1610612755','1610612761','1610612764']);
  const POS=['PG','SG','SF','PF','C'],CATS=['scoring','dunks','three','rebounding','passing','blocks','steals'];
  const read=()=>{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch{return null}};
  const write=s=>localStorage.setItem(SAVE_KEY,JSON.stringify(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const pk=p=>String(p?.playerId||p?.id||p?.name||'player');
  const hash=s=>[...String(s)].reduce((n,c)=>(n*33+c.charCodeAt(0))>>>0,2166136261);
  const roster=id=>players.filter(p=>String(p.teamId)===String(id)&&!p.classicTeam);
  const overall=p=>Math.round(CATS.reduce((n,k)=>n+(+p.stats?.[k]||0),0)/CATS.length);
  const ensure=s=>{s.rewards=s.rewards||{};s.rewards.actualGames=s.rewards.actualGames||{};s.rewards.awards=s.rewards.awards||{};s.rewards.allStar=s.rewards.allStar||{date:'2027-02-21',played:false,rosters:null,mvp:null};return s.rewards;};

  function actualRows(s){const out=[];Object.entries(ensure(s).actualGames).forEach(([gameId,hist])=>(hist||[]).forEach(h=>{if(!h?.user||!h?.cpu)return;const a=+h.userPts||0,b=+h.cpuPts||0;if(a===b)return;const winner=a>b?h.user:h.cpu;out.push({gameId,category:h.category,winner,margin:Math.abs(a-b),phase:h.phase||'regular',round:h.round||''});}));return out;}
  function syntheticRows(s){const out=[];for(const [gameId,res] of Object.entries(s.results||{})){if(res?.userPlayed||ensure(s).actualGames[gameId])continue;const g=(s.schedule||[]).find(x=>x.id===gameId);if(!g)continue;const A=roster(g.home),B=roster(g.away);if(!A.length||!B.length)continue;for(let i=0;i<4;i++){const cat=CATS[(hash(gameId)+i*3)%CATS.length];const pa=A.reduce((x,p)=>(+p.stats?.[cat]||0)>(+x.stats?.[cat]||0)?p:x,A[0]);const pb=B.reduce((x,p)=>(+p.stats?.[cat]||0)>(+x.stats?.[cat]||0)?p:x,B[0]);const va=+pa.stats?.[cat]||0,vb=+pb.stats?.[cat]||0;if(va===vb)continue;out.push({gameId,category:cat,winner:va>vb?pa:pb,margin:Math.abs(va-vb),phase:'regular',round:''});}}
    return out;
  }
  function rows(s){return actualRows(s).concat(syntheticRows(s));}
  function board(s,filter=()=>true){const map={};for(const r of rows(s)){if(!filter(r))continue;const k=pk(r.winner),x=map[k]||(map[k]={playerId:r.winner.playerId||r.winner.id,name:r.winner.name,teamId:r.winner.teamId,position:r.winner.position,total:0,wins:0});x.total+=r.margin;x.wins++;}return Object.values(map).sort((a,b)=>b.total-a.total||b.wins-a.wins||a.name.localeCompare(b.name));}
  const leader=(s,f)=>board(s,f)[0]||null;
  function syncMvp(s){const top=board(s).slice(0,5);const m=ensure(s);m.mvp=m.mvp||{scores:{},awarded:null};m.mvp.scores={};top.forEach(x=>m.mvp.scores[String(x.playerId)]={...x});}
  function award(s,key,title,row){if(!row||ensure(s).awards[key])return;const a={...row,title,at:new Date().toISOString()};s.rewards.awards[key]=a;s.history=s.history||[];s.history.unshift({at:a.at,type:'reward',reward:title,playerId:a.playerId,total:a.total,text:`${a.name} won ${title} with a +${a.total} cumulative matchup margin.`});}
  function maybeAwards(s){syncMvp(s);const played=Object.keys(s.results||{}).length;const datePassed=(s.schedule||[]).filter(g=>s.results?.[g.id]).some(g=>g.date>='2027-02-20');if(datePassed){award(s,'dunkChampion','Slam Dunk Champion',leader(s,r=>r.category==='dunks'));award(s,'threeChampion','3-Point Shootout Champion',leader(s,r=>r.category==='three'));}
    if(s.completed){award(s,'mvp','Season MVP',leader(s,()=>true));award(s,'scoringChampion','Scoring Champion',leader(s,r=>['scoring','three','dunks'].includes(r.category)));award(s,'dpoy','Defensive Player of the Year',leader(s,r=>['blocks','steals'].includes(r.category)));const fm=leader(s,r=>r.phase==='postseason'&&/final/i.test(r.round||''));if(fm)award(s,'finalsMvp','Finals MVP',fm);}
  }
  function allStarRosters(s){const b=board(s),score=new Map(b.map(x=>[String(x.playerId),x.total]));const pick=(east,pos)=>players.filter(p=>!p.classicTeam&&String(p.position)===pos&&(EAST.has(String(p.teamId))===east)).sort((a,b)=>(score.get(pk(b))||0)-(score.get(pk(a))||0)||overall(b)-overall(a))[0];return {east:POS.map(p=>pick(true,p)).filter(Boolean),west:POS.map(p=>pick(false,p)).filter(Boolean)};}

  const style=document.createElement('style');style.textContent=`
  .awards-races{border:1px solid rgba(247,185,40,.28);border-radius:18px;overflow:hidden;background:#0c1118;margin-bottom:12px}.awards-races h3{margin:0;padding:12px 13px;background:linear-gradient(135deg,rgba(247,185,40,.16),rgba(255,223,105,.05));font-size:14px}.award-race-row{display:grid;grid-template-columns:1fr auto;gap:8px;padding:10px 12px;border-top:1px solid rgba(255,255,255,.07)}.award-race-row span{font-size:9px;color:#9ba5b3;text-transform:uppercase;font-weight:1000;letter-spacing:.06em}.award-race-row strong{display:block;font-size:11px;margin-top:2px}.award-race-score{font-size:16px!important;color:#f7b928!important;align-self:center}.allstar-card{padding:14px;border:1px solid rgba(247,185,40,.32);border-radius:18px;background:linear-gradient(150deg,#1b1608,#0b1018 62%);margin-bottom:10px}.allstar-card .season-next-label{margin-bottom:6px}.allstar-card h3{margin:0 0 5px;font-size:19px}.allstar-card p{margin:0 0 11px;color:#9ca6b4;font-size:10px;line-height:1.4}.allstar-play{width:100%;min-height:48px;border:0;border-radius:13px;background:linear-gradient(180deg,#ffdf69,#f7b928);font-weight:1000;color:#090b0e}.allstar-schedule{border-color:rgba(247,185,40,.35)!important}.allstar-mvp-note{margin-top:7px;font-size:10px;font-weight:900;color:#f7b928}`;document.head.appendChild(style);

  function racesMarkup(s){const a=ensure(s).awards;const race=(key,title,f)=>{const done=a[key],x=done||leader(s,f);return `<div class="award-race-row"><div><span>${esc(title)}</span><strong>${x?esc(x.name):'No leader yet'}${done?' · Awarded':''}</strong></div><strong class="award-race-score">${x?`+${x.total}`:'—'}</strong></div>`};return `<section id="awardsRaces" class="awards-races"><h3>Season Awards</h3>${race('scoringChampion','Scoring Champion',r=>['scoring','three','dunks'].includes(r.category))}${race('dpoy','Defensive Player of the Year',r=>['blocks','steals'].includes(r.category))}${race('dunkChampion','Slam Dunk Champion',r=>r.category==='dunks')}${race('threeChampion','3-Point Shootout Champion',r=>r.category==='three')}${race('finalsMvp','Finals MVP',r=>r.phase==='postseason'&&/final/i.test(r.round||''))}</section>`;}
  function paintHistory(){const content=document.getElementById('seasonContent');const active=[...document.querySelectorAll('#seasonTabs .season-tab')].find(b=>b.classList.contains('active'));if(!content||active?.dataset.tab!=='history'||document.getElementById('awardsRaces'))return;const s=read();if(!s)return;maybeAwards(s);write(s);content.insertAdjacentHTML('afterbegin',racesMarkup(s));}
  function nextGameDate(s){const g=(s.schedule||[]).filter(g=>!s.results?.[g.id]&&(g.home===s.teamId||g.away===s.teamId)).sort((a,b)=>a.date.localeCompare(b.date))[0];return g?.date||'9999-99-99';}
  function allStarDue(s){const a=ensure(s).allStar;return !a.played&&s.phase==='regular'&&nextGameDate(s)>='2027-02-19';}
  function paintAllStar(){const s=read();if(!s)return;const content=document.getElementById('seasonContent');const active=[...document.querySelectorAll('#seasonTabs .season-tab')].find(b=>b.classList.contains('active'));if(active?.dataset.tab==='schedule'&&!document.getElementById('allStarScheduleRow')){const list=content?.querySelector('.schedule-list');if(list){const row=document.createElement('div');row.id='allStarScheduleRow';row.className='schedule-game allstar-schedule';row.innerHTML=`<div style="font-size:25px;text-align:center">★</div><div><strong>NBA All-Star Game · East vs West</strong><small>Feb 21, 2027 · Phoenix, Arizona · Exhibition</small></div><span class="schedule-result ${s.rewards?.allStar?.played?'win':'next'}">${s.rewards?.allStar?.played?'FINAL':'ALL-STAR'}</span>`;list.appendChild(row);}}
    if(active?.dataset.tab==='overview'&&allStarDue(s)&&!document.getElementById('allStarWeekendCard')){const c=document.createElement('section');c.id='allStarWeekendCard';c.className='allstar-card';c.innerHTML=`<div class="season-next-label">All-Star Weekend · Phoenix</div><h3>East vs West</h3><p>The best player at each position in each conference has been selected from the season awards data. Play the All-Star Game like a normal Courtside matchup.</p><button class="allstar-play" type="button" id="playAllStarGame">Play All-Star Game</button>`;content?.prepend(c);document.getElementById('playAllStarGame')?.addEventListener('click',()=>startAllStar(s));}}
  function startAllStar(s){const r=allStarRosters(s);ensure(s).allStar.rosters={east:r.east.map(pk),west:r.west.map(pk)};write(s);const userEast=EAST.has(String(s.teamId));userTeam=userEast?r.east:r.west;cpuTeam=userEast?r.west:r.east;state={quarter:1,userScore:0,cpuScore:0,usedUser:new Set(),usedCpu:new Set(),category:null,history:[],overtime:false};sessionStorage.setItem(ALLSTAR_KEY,userEast?'E':'W');showScreen('game');beginQuarter();setTimeout(()=>{const sides=document.querySelectorAll('#game .score-side span');if(sides[0])sides[0].textContent=userEast?'EAST':'WEST';if(sides[1])sides[1].textContent=userEast?'WEST':'EAST';},0);window.scrollTo({top:0});}

  const baseFinish=window.finishGame;
  if(typeof baseFinish==='function')window.finishGame=function(){const isAS=!!sessionStorage.getItem(ALLSTAR_KEY);const isSeason=sessionStorage.getItem(ACTIVE_KEY)==='1';const snap=(typeof state!=='undefined'&&state?.history)?state.history.map(h=>({...h,user:h.user?{...h.user}:h.user,cpu:h.cpu?{...h.cpu}:h.cpu})):[];const before=read();const beforeKeys=new Set(Object.keys(before?.results||{}));const out=baseFinish.apply(this,arguments);if(isAS){sessionStorage.removeItem(ALLSTAR_KEY);const s=read();if(s){let best=null;for(const h of snap){if((+h.userPts||0)===(+h.cpuPts||0))continue;const w=(+h.userPts||0)>(+h.cpuPts||0)?h.user:h.cpu,m=Math.abs((+h.userPts||0)-(+h.cpuPts||0));if(!best||m>best.margin)best={playerId:w.playerId||w.id,name:w.name,teamId:w.teamId,margin:m,category:h.category};}const a=ensure(s).allStar;a.played=true;a.score=`${state?.userScore||0}-${state?.cpuScore||0}`;a.mvp=best;a.playedAt=new Date().toISOString();if(best){s.history=s.history||[];s.history.unshift({at:a.playedAt,type:'reward',reward:'All-Star MVP',playerId:best.playerId,text:`${best.name} won All-Star MVP with a +${best.margin} matchup margin.`});}write(s);setTimeout(()=>{const final=document.getElementById('final');const card=final?.querySelector('.compact-final-card');if(card&&best)card.insertAdjacentHTML('beforeend',`<div class="allstar-mvp-note">ALL-STAR MVP · ${esc(best.name)} · +${best.margin}</div>`);},0);}return out;}
    if(isSeason){setTimeout(()=>{const s=read();if(!s)return;const newId=Object.keys(s.results||{}).find(k=>!beforeKeys.has(k));if(newId&&snap.length){const phase=s.phase==='regular'?'regular':'postseason';const round=s.post?.userSeries?.label||s.post?.pending?.label||'';ensure(s).actualGames[newId]=snap.map(h=>({...h,phase,round}));}maybeAwards(s);write(s);},0);}return out;};

  const observer=new MutationObserver(()=>requestAnimationFrame(()=>{paintHistory();paintAllStar();}));const start=()=>{const c=document.getElementById('seasonContent');if(c)observer.observe(c,{childList:true,subtree:false});paintHistory();paintAllStar();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,300),{once:true});else setTimeout(start,300);
})();