const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let src=read('app-v0.36.js');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__v35={
 getState:()=>state,getGL:()=>gl34(),setUserTeam:a=>{userTeam=a;state.userTeam=a;},setSeason:(date='2026-12-15')=>{state.date=date;state.phase='regular_season';state.seasonStarted=true;state.seasonComplete=false;},simTo:simulateGLeagueToV34,available:availableCallupsV34,sign:signGLeagueCandidateV34,canSign:canSignGLeagueV34,getPlayer:id=>byId.get(id),currentTeam,record:glRecordV34,affiliate:glAffiliateV34,twoWay:twoWayRowsV34
};\n})();`)
.replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}')
.replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}')
.replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}');
function cls(init=[]){const s=new Set(init);return {add(...x){x.forEach(v=>s.add(v))},remove(...x){x.forEach(v=>s.delete(v))},contains:v=>s.has(v),toggle(){return false}}}
function el(){return {innerHTML:'',textContent:'',dataset:{},style:{setProperty(){},removeProperty(){}},classList:cls(),onclick:null,hidden:false,disabled:false,setAttribute(){},removeAttribute(){},getAttribute(){return null},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},contains(){return true},appendChild(){},insertAdjacentHTML(){},offsetParent:{}}}
const store={nbaCourtsideTeam:'MIA'};const document={documentElement:{style:{setProperty(){}}},head:{appendChild(){}},body:el(),activeElement:el(),querySelector(){return null},querySelectorAll(){return[]},getElementById(){return null},createElement(){return el()},addEventListener(){},contains(){return true}};
const ctx={console,structuredClone,Date,URLSearchParams,Math,document,location:{search:'',reload(){}},navigator:{},scrollTo(){},confirm:()=>true,setTimeout:f=>f(),clearTimeout(){},requestAnimationFrame:f=>f(),MutationObserver:function(){this.observe=()=>{}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},window:{}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data-v0.36.js','data/source-certification-v0.36.js','data/future-pick-ledger-v0.36.js','data/schedule-v0.36.js','data/schedule-template-v0.36.js','cba-v0.36.js','data/organizations-v0.36.js','data/g-league-v0.36.js','data/college-draft-v0.36.js'])vm.runInContext(read(f),ctx,{filename:f});
vm.runInContext(src,ctx,{filename:'app-v0.36.js'});const t=ctx.__v35;if(!t)throw new Error('v35 hooks missing');t.setUserTeam('MIA');t.setSeason('2026-12-15');t.simTo('2026-12-15');const G=t.getGL();if(G.version!==34)throw new Error('G League save branch version');if(!G.results.length)throw new Error('G League simulation produced no results');if(!/^\d+-\d+$/.test(t.record('GL-MIA')))throw new Error('affiliate record unavailable');if(t.twoWay('MIA').length!==2)throw new Error('MIA two-way tracker mismatch');const c=t.available()[0];if(!c)throw new Error('no call-up candidate');const check=t.canSign(c,'MIA');if(!check.ok)throw new Error('MIA should have a legal call-up route: '+check.reason);if(!t.sign(c.id,'MIA',true))throw new Error('G League call-up failed');const p=t.getPlayer(c.id);if(!p||t.currentTeam(p)!=='MIA')throw new Error('call-up player not assigned to NBA team');if(p.stats_2025_26!==null)throw new Error('G League evidence leaked into NBA stats row');if(p.rating_source!=='2026_g_league_callup_projection_v0.34')throw new Error('call-up rating source missing');if(!G.signedToNBA[c.id]||G.signedToNBA[c.id].team!=='MIA')throw new Error('call-up state not persisted');const gp=Object.values(G.standings).map(x=>x.gp);if(Math.max(...gp)-Math.min(...gp)>1)throw new Error('G League schedule balance drift');console.log(JSON.stringify({status:'PASS',version:G.version,results:G.results.length,affiliate:t.affiliate('MIA').name,affiliateRecord:t.record('GL-MIA'),twoWayFilled:t.twoWay('MIA').length,callup:c.name,callupOVR:p.ratings.overall,nbaStats:p.stats_2025_26,scheduleSpread:Math.max(...gp)-Math.min(...gp)},null,2));
