const fs=require('fs'),vm=require('vm');
const root='/mnt/data/NBA-Courtside-Smart-Front-Offices-v0.11';
const data=fs.readFileSync(root+'/data/data.js','utf8'),sched=fs.readFileSync(root+'/data/schedule.js','utf8');
let src=fs.readFileSync(root+'/app.js','utf8');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__test={getState:()=>state,getGames:()=>games,getPlayers:()=>players,teamPlayers,ensureAllRotations,ensureRotation,simulateGame,updateMoraleAll,expectedRole,expectedMinutes,actualMinutes,moraleBreakdown,moraleEntry,pendingMeetings,respondMeeting,playerMood};\n})();`)
 .replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}')
 .replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}')
 .replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}')
 .replace(/function processGameInjuries\([^\n]*\)\{[^\n]*\}/,'function processGameInjuries(){return []}');
const store={nbaCourtsideTeam:'TOR'};const noop=()=>{};
const ctx={console,structuredClone,Date,setTimeout:(f)=>f(),confirm:()=>true,scrollTo:noop,location:{reload:noop},window:{},document:{documentElement:{style:{setProperty:noop}},querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({classList:{add:noop,remove:noop}}),body:{appendChild:noop,style:{}}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]},Math};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(data,ctx);vm.runInContext(sched,ctx);vm.runInContext(src,ctx);
const t=ctx.__test,st=t.getState();st.userTeam='TOR';st.seasonStarted=true;st.phase='regular_season';st.date='2026-10-20';st.results={};st.seasonStats={};st.gameLogs={};st.playerMorale={};st.meetings=[];st.promises={};t.ensureAllRotations();
const tor=t.teamPlayers('TOR',{activeOnly:true}).sort((a,b)=>(b.ratings?.overall||0)-(a.ratings?.overall||0));const target=tor[0],r=t.ensureRotation('TOR');const old=r.minutes[target.id]||0;if(old<20)throw new Error('top player not in rotation');const diff=old-8;r.minutes[target.id]=8;const others=Object.keys(r.minutes).filter(id=>id!==target.id);for(let i=0;i<diff;i++)r.minutes[others[i%others.length]]++;
let torGames=0,lastDate='2026-10-20';for(const g of t.getGames()){t.simulateGame(g);lastDate=g.date;if(g.home==='TOR'||g.away==='TOR')torGames++;if(torGames>=12)break}
st.date=lastDate;for(let i=0;i<5;i++){st.date=new Date(new Date(lastDate+'T12:00:00').getTime()+i*86400000).toISOString().slice(0,10);t.updateMoraleAll(st.date,true)}
const breakdown=t.moraleBreakdown(target),m=t.moraleEntry(target);if(!(breakdown.actualMinutes<breakdown.expectedMinutes))throw new Error('minutes mismatch not detected');if(m.score>=60)throw new Error('morale did not fall enough: '+m.score);const meets=t.pendingMeetings();if(!meets.length)throw new Error('no player meeting generated');const before=t.ensureRotation('TOR').minutes[target.id];t.respondMeeting(meets[0].id,'increase');const after=t.ensureRotation('TOR').minutes[target.id];if(after<=before)throw new Error('increase role did not raise minutes');if(!st.promises[target.id])throw new Error('role promise missing');const mood=t.playerMood(target);console.log(JSON.stringify({player:target.name,role:t.expectedRole(target),expectedMinutes:t.expectedMinutes(target),actualMinutes:+breakdown.actualMinutes.toFixed(1),morale:m.score,status:m.status,meetingReason:meets[0].reason,minutesBefore:before,minutesAfter:after,promiseTarget:st.promises[target.id].target,postResponse:mood.m.score},null,2));
