const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let src=read('app-v0.40.js');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__v40={
 getState:()=>state,setUserTeam:a=>{userTeam=a;state.userTeam=a;},players:()=>players,teams:()=>teams,games:()=>games,health:health40,entry:healthEntryV40,medical:medicalTeamV40,ratings:medicalRatingsV40,condition:conditionV40,status:medicalStatusV40,workload:workloadV40,createInjury,processMedicalDay,returnStage:returnStageV40,setPlan:setLoadPlanV40,cap:minuteCapV40,available:isAvailable,injuryRisk,applyGameLoad:applyGameLoadV40,summary:teamHealthSummaryV40,view:medicalViewV40,portal:medicalPortalV40,applyAction:applyDailyAction,action:activeDailyAction,setPolicy:setMedicalPolicyV40,simulateGame,currentTeam,teamPlayers,overall
};\n})();`)
.replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}')
.replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}')
.replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}')
.replace(/function closeSheet\(\)\{[^\n]*\}/,'function closeSheet(){}');
function classList(init=[]){const s=new Set(init);return {add(...x){x.forEach(v=>s.add(v))},remove(...x){x.forEach(v=>s.delete(v))},contains:v=>s.has(v),toggle(){return false}}}
function el(){return {innerHTML:'',textContent:'',dataset:{},style:{setProperty(){},removeProperty(){}},classList:classList(),onclick:null,hidden:false,disabled:false,setAttribute(){},removeAttribute(){},getAttribute(){return null},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},contains(){return true},appendChild(){},insertAdjacentHTML(){},offsetParent:{}}}
const store={nbaCourtsideTeam:'BOS'};const document={documentElement:{style:{setProperty(){}}},head:{appendChild(){}},body:el(),activeElement:el(),querySelector(){return null},querySelectorAll(){return[]},getElementById(){return null},createElement(){return el()},addEventListener(){},contains(){return true}};
const ctx={console,structuredClone,Date,URLSearchParams,Math,document,location:{search:'',reload(){}},navigator:{},scrollTo(){},confirm:()=>true,setTimeout:f=>f(),clearTimeout(){},requestAnimationFrame:f=>f(),MutationObserver:function(){this.observe=()=>{}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},window:{}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data-v0.40.js','data/source-certification-v0.40.js','data/future-pick-ledger-v0.40.js','data/schedule-v0.40.js','data/schedule-template-v0.40.js','cba-v0.40.js','data/organizations-v0.40.js','data/staff-careers-v0.40.js','data/g-league-v0.40.js','data/college-draft-v0.40.js','data/contract-market-v0.40.js'])vm.runInContext(read(f),ctx,{filename:f});
vm.runInContext(src,ctx,{filename:'app-v0.40.js'});const t=ctx.__v40;if(!t)throw new Error('v40 hooks missing');
t.setUserTeam('BOS');const s=t.getState();s.seasonYear=2026;s.phase='regular_season';s.seasonStarted=true;s.seasonComplete=false;s.date='2026-11-10';
const H=t.health();if(H.version!==40)throw new Error('health state version');if(Object.keys(H.teams).length!==30)throw new Error('medical departments not 30');for(const a of Object.keys(H.teams)){if(H.teams[a].staff.length!==3)throw new Error('medical staff count '+a)}
const tat=t.players().find(p=>p.name==='Jayson Tatum');if(!tat)throw new Error('Tatum missing');const e=t.entry(tat);e.fatigue=68;const c=t.condition(tat);if(!(c<75&&c>45))throw new Error('condition not fatigue sensitive '+c);const riskHeavy=t.injuryRisk(tat,36);e.fatigue=8;const riskFresh=t.injuryRisk(tat,36);if(!(riskHeavy>riskFresh))throw new Error('fatigue not increasing injury risk');
// Force a known injury and verify enriched body area + staged return.
const inj=t.createInjury(tat,s.date,'runtime',{name:'Ankle sprain',severity:'minor',min:5,max:5,w:1});if(!inj||inj.body_area!=='ANKLE'||inj.medical_model!=='v0.40')throw new Error('enriched injury missing');const ret=inj.return_date;s.date=ret;t.processMedicalDay(ret);if(t.available(tat,ret)!==true)throw new Error('cleared player not available');const r=t.returnStage(tat,ret);if(!r||!(r.cap>=20&&r.cap<=34))throw new Error('return-to-play restriction missing');if(t.cap(tat,ret)!==r.cap)throw new Error('medical cap not enforced');
// GM can rest or override the medical recommendation for the next game.
const next=t.games().find(g=>(g.home==='BOS'||g.away==='BOS')&&g.date>=ret);if(!next)throw new Error('next BOS game missing');s.date=next.date;t.setPlan(tat.id,'rest');if(t.available(tat,next.date)!==false)throw new Error('rest plan not enforced');t.setPlan(tat.id,'full');if(t.cap(tat,next.date)!==48)throw new Error('full-go override missing');
// Training activity has physical effect.
s.livingLeague=s.livingLeague||{version:32,dailyActions:{},developmentCredits:{},newsArchive:[],actionQueue:[],incomingTrades:[],findTradeResults:[]};s.livingLeague.dailyActions={};e.fatigue=50;t.applyAction('recovery');if(!(e.fatigue<=32))throw new Error('recovery day did not reduce fatigue '+e.fatigue);
const html=t.view();for(const needle of ['AVAILABILITY<br>MATTERS.','ROSTER HEALTH','MEDICAL STAFF','HISTORY'])if(!html.includes(needle))throw new Error('medical UI missing '+needle);if(!t.portal().includes('HEALTH + PERFORMANCE'))throw new Error('medical portal missing');
console.log(JSON.stringify({status:'PASS',version:H.version,teams:Object.keys(H.teams).length,medicalStaff:Object.values(H.teams).reduce((n,x)=>n+x.staff.length,0),bostonRatings:t.ratings('BOS'),fatigueRisk:{fresh:riskFresh,heavy:riskHeavy},injury:{name:inj.name,body:inj.body_area,return:ret,cap:r.cap},recoveryFatigue:e.fatigue,teamSummary:t.summary('BOS')},null,2));
