const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let src=read('app-v0.37.js');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__v37={
 getState:()=>state,setUserTeam:a=>{userTeam=a;state.userTeam=a;},events:leagueEventsV37,season:seasonEventsV37,allStar:ensureAllStarV37,contests:simulateAllStarContestsV37,asg:simulateAllStarGameV37,process:processLeagueEventsDayV37,race:playoffRaceSnapshotV37,awards:()=>{generateAwards();return state.awards},view:leagueEventsViewV37,combine:ensureCombineV37,summer:runSummerLeagueV37,summerView:summerLeagueBridgeV37,allStarView:allStarHubV37,awardsView:awardsShowV37,teams:()=>teams,players:()=>players,games:()=>games,buildDraftOrder,record
};\n})();`)
.replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}')
.replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}')
.replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}');
function classList(init=[]){const s=new Set(init);return {add(...x){x.forEach(v=>s.add(v))},remove(...x){x.forEach(v=>s.delete(v))},contains:v=>s.has(v),toggle(){return false}}}
function el(){return {innerHTML:'',textContent:'',dataset:{},style:{setProperty(){},removeProperty(){}},classList:classList(),onclick:null,hidden:false,disabled:false,setAttribute(){},removeAttribute(){},getAttribute(){return null},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},contains(){return true},appendChild(){},insertAdjacentHTML(){},offsetParent:{}}}
const store={nbaCourtsideTeam:'BOS'};const document={documentElement:{style:{setProperty(){}}},head:{appendChild(){}},body:el(),activeElement:el(),querySelector(){return null},querySelectorAll(){return[]},getElementById(){return null},createElement(){return el()},addEventListener(){},contains(){return true}};
const ctx={console,structuredClone,Date,URLSearchParams,Math,document,location:{search:'',reload(){}},navigator:{},scrollTo(){},confirm:()=>true,setTimeout:f=>f(),clearTimeout(){},requestAnimationFrame:f=>f(),MutationObserver:function(){this.observe=()=>{}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},window:{}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data-v0.37.js','data/source-certification-v0.37.js','data/future-pick-ledger-v0.37.js','data/schedule-v0.37.js','data/schedule-template-v0.37.js','cba-v0.37.js','data/organizations-v0.37.js','data/g-league-v0.37.js','data/college-draft-v0.37.js'])vm.runInContext(read(f),ctx,{filename:f});
vm.runInContext(src,ctx,{filename:'app-v0.37.js'});const t=ctx.__v37;if(!t)throw new Error('v37 hooks missing');
t.setUserTeam('BOS');const s=t.getState();s.seasonYear=2026;s.phase='regular_season';s.seasonStarted=true;s.seasonComplete=false;s.date='2027-02-15';s.results={};s.seasonStats={};
// Build a deterministic midseason universe without consuming the game's RNG.
for(const g of t.games().filter(g=>g.date<='2027-02-15')){let h=0;for(const c of g.id)h=(h*33+c.charCodeAt(0))>>>0;const homeWin=(h%100)<56;const hs=homeWin?116+(h%12):101+(h%13),as=homeWin?101+((h>>>3)%13):116+((h>>>3)%12);s.results[g.id]={home_score:hs,away_score:as,winner:homeWin?g.home:g.away};}
for(const p of t.players()){
 if(!p.team&&!p.rights_team)continue;const b=p.stats_2025_26||{},gp=48,mpg=+(b.mpg||Math.max(8,Math.min(36,(p.ratings?.overall||70)-48))).toFixed(1),pts=+(b.pts||Math.max(4,((p.ratings?.overall||70)-58)*.8)).toFixed(1),reb=+(b.reb||4).toFixed(1),ast=+(b.ast||2.5).toFixed(1),stl=+(b.stl||.8).toFixed(1),blk=+(b.blk||.5).toFixed(1),fga=+(b.fga||Math.max(5,pts/1.25)).toFixed(1),tpa=+(b.three_pa||Math.max(1,fga*.35)).toFixed(1),fta=+(b.fta||Math.max(1,pts*.2)).toFixed(1),fg=+(b.fg_pct||.46),tp=+(b.three_pct||.35),ft=+(b.ft_pct||.78);
 s.seasonStats[p.id]={gp,gs:(p.ratings?.overall||70)>=78?gp*.8:gp*.2,min:mpg*gp,pts:pts*gp,reb:reb*gp,ast:ast*gp,stl:stl*gp,blk:blk*gp,tov:(b.tov||1.8)*gp,fgm:fga*fg*gp,fga:fga*gp,tpm:tpa*tp*gp,tpa:tpa*gp,ftm:fta*ft*gp,fta:fta*gp};
}
const E=t.events();if(E.version!==37)throw new Error('league events version');
const A=t.allStar();if(!A||A.east.starters.length!==5||A.west.starters.length!==5||A.east.reserves.length!==7||A.west.reserves.length!==7)throw new Error('all-star selection invalid');
t.contests('2027-02-20');t.asg('2027-02-21');if(!A.results.contests?.threePoint?.[0]||!A.results.contests?.dunk?.[0]||!A.results.game?.mvp)throw new Error('all-star events incomplete');
s.date='2027-03-30';t.process(s.date);const race=t.race();if(race.length!==30)throw new Error('playoff race not 30 teams');
s.date='2027-04-11';s.seasonComplete=true;const awards=t.awards();for(const k of ['mvp','dpoy','roy','smoy','mip','coy'])if(!awards[k])throw new Error('missing award '+k);for(const k of ['all_nba_first','all_nba_second','all_nba_third','all_defense_first'])if((awards[k]||[]).length!==5)throw new Error('team length '+k);
// Combine + Summer League bridge runtime probes.
s.seasonComplete=false;s.phase='scouting';s.draft={prospectIds:t.players().slice(0,20).map(p=>p.id),selections:t.players().slice(0,4).map((p,i)=>({pick:i+1,team:i===0?'BOS':'ATL',player_id:p.id}))};s.date='2027-06-21';const C=t.combine();if(!C||C.participants.length!==20)throw new Error('combine failed');t.summer();const SL=t.season().summerLeague;if(!SL||SL.games!==5||!SL.mvp)throw new Error('summer league failed');
const html=t.view();for(const needle of ['THE SEASON<br>HAS MOMENTS.','AWARDS','ALL-STAR','DEADLINE'])if(!html.includes(needle))throw new Error('event hub missing '+needle);const ash=t.allStarView();if(!ash.includes('ALL-STAR'))throw new Error('all-star UI missing');const awardHtml=t.awardsView();if(!awardHtml.includes('ALL-NBA FIRST TEAM'))throw new Error('awards show missing all-nba');
console.log(JSON.stringify({status:'PASS',version:E.version,allStars:{east:A.east.starters.length+A.east.reserves.length,west:A.west.starters.length+A.west.reserves.length},threePointWinner:A.results.contests.threePoint[0].id,dunkWinner:A.results.contests.dunk[0].id,allStarMvp:A.results.game.mvp,raceTeams:race.length,awards:{mvp:awards.mvp,dpoy:awards.dpoy,roy:awards.roy,coy:awards.coy},allNBA:[awards.all_nba_first.length,awards.all_nba_second.length,awards.all_nba_third.length],combine:C.participants.length,summerLeagueMvp:SL.mvp},null,2));
