const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const noop=()=>{};const dummy=()=>({innerHTML:'',classList:{add:noop,remove:noop,toggle:noop},onclick:null,style:{},dataset:{},addEventListener:noop,disabled:false});
const store={nbaCourtsideTeam:'PHI'};
const ctx={console,structuredClone,Date,Math,URLSearchParams,setTimeout:()=>{},clearTimeout:()=>{},confirm:()=>true,scrollTo:noop,location:{reload:noop,search:''},navigator:{},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{documentElement:{style:{setProperty:noop}},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild(){}}}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data.js','data/source-certification.js','data/future-pick-ledger.js','data/schedule.js','data/schedule-template.js','cba.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),ctx,{filename:f});
let src=fs.readFileSync(root+'/app.js','utf8');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};
userTeam='PHI';state.userTeam='PHI';
const dean=byId.get('dean-wade'),brown=byId.get('jaylen-brown'),ty=byId.get('ty-jerome');
if(birdLevelFor(dean)!=='non_bird')throw new Error('Dean Wade seed');
if(birdLevelFor(brown)!=='bird')throw new Error('Jaylen Brown seed');
state.birdClock[ty.id]=2;
state.contractOverrides[ty.id]={years:[{season_start:2026,season:'2026-27',amount:10000000,option:'guaranteed'},{season_start:2027,season:'2027-28',amount:1,option:'player_option'}],expiry:'UFA',team:currentTeam(ty)};
processContractsForNextSeason(2026);
if(state.freeAgentRights[ty.id]?.level!=='early_bird')throw new Error('Early Bird option-decline path');
const ext=byId.get('dean-wade');state.assignments[ext.id]='PHI';state.birdClock[ext.id]=3;waivePlayer(ext,'PHI',{cpu:true});if(state.birdClock[ext.id]!==3)throw new Error('pending waiver should preserve Bird continuity');clearWaivers(ext,waiverEntry(ext));if(state.birdClock[ext.id]!==0)throw new Error('cleared waiver did not reset Bird clock');
const routes=CBA.signingRoutes({teamSalary:CAP.salary_cap+10000000,cap:CAP.salary_cap,firstApron:CAP.first_apron,secondApron:CAP.second_apron,amount:5000000,usage:{},ownRights:{level:'early_bird',last_salary:5000000},player:ty});
const er=routes.find(r=>r.id==='early_bird');if(!er||er.minYears!==2||er.years!==4)throw new Error('Early Bird term bounds');
if(CBA.annualRaise({level:'early_bird'})!==.08||CBA.annualRaise({level:'non_bird'})!==.05)throw new Error('rights raise rates');
console.log(JSON.stringify({status:'PASS',dean:birdLevelFor(dean),brown:birdLevelFor(brown),tyOptionRights:state.freeAgentRights[ty.id]?.level,earlyBird:{minYears:er.minYears,maxYears:er.years,raise:CBA.annualRaise({level:'early_bird'})}},null,2));
})();`);
vm.runInContext(src,ctx,{filename:'app-bird-v21.js',timeout:120000});
