const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const noop=()=>{};const dummy=()=>({innerHTML:'',classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},onclick:null,onchange:null,style:{},dataset:{},disabled:false,hidden:false,offsetParent:{},appendChild:noop,prepend:noop,querySelector:()=>null,querySelectorAll:()=>[],setAttribute:noop,removeAttribute:noop,getAttribute:()=>null,addEventListener:noop,focus:noop,insertAdjacentHTML:noop});
const store={nbaCourtsideTeam:'PHI'};
const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},confirm:()=>true,scrollTo:()=>{},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{activeElement:null,contains:()=>false,addEventListener:noop,documentElement:{style:{setProperty:noop}},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild(){}}},location:{reload(){},search:''},navigator:{}};sandbox.window=sandbox;
vm.createContext(sandbox);
for(const f of ['data/data-v0.44.js','data/source-certification-v0.44.js','data/future-pick-ledger-v0.44.js','data/schedule-v0.44.js','data/schedule-template-v0.44.js','cba-v0.44.js','data/organizations-v0.44.js','data/staff-careers-v0.44.js','data/g-league-v0.44.js','data/college-draft-v0.44.js','data/contract-market-v0.44.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(root+'/app-v0.51.js','utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};
refreshSeasonConfig();userTeam='PHI';state.userTeam='PHI';state.seasonYear=2026;state.seasonStarted=true;state.phase='regular_season';state.date='2026-11-20';
staff38();const V=staffCoaching50();if(!V||V.version!==50)throw new Error('v50 state missing');
const st=teamStaffV38(userTeam);if(!st.coach)throw new Error('head coach missing');fillAssistantsV38(userTeam,5);const roles=assistantAssignmentsV50(userTeam);if(roles.length!==5||roles.filter(x=>x.staff).length<4)throw new Error('specialized assistants missing');
const traits=staffTraitsV50(st.coach);for(const k of ['tactics','development','playerManagement','adaptability','scouting','reputation'])if(!Number.isFinite(traits[k]))throw new Error('trait '+k+' missing');
const tend=coachTendenciesV50(userTeam);if(!tend.rotationDepth||!tend.pace||!Number.isFinite(tend.flexibility))throw new Error('coach tendencies incomplete');
const chem=staffChemistryV50(userTeam);if(chem.score<35||chem.score>96)throw new Error('staff chemistry out of range');
const ident=organizationalIdentityV50(userTeam);if(!ident.tags||ident.tags.length<4)throw new Error('organizational identity missing');
const fit=coachRosterReadV50(userTeam);if(!Number.isFinite(fit.fit))throw new Error('coach roster fit missing');
const young=teamPlayers(userTeam).filter(p=>['active','two_way'].includes(currentStatus(p))).sort((a,b)=>a.age-b.age)[0];if(!young)throw new Error('no player for development test');
setDevelopmentPlanV50(young.id,'shooting',roleTargetsV50(young)[0]);const plan=developmentPlanV50(young);if(!plan||plan.focus!=='shooting')throw new Error('development plan not saved');rng=()=>0.01;const devOut=applyDevelopment(young);if(!devOut.staffFocused||devOut.staffFocus!=='shooting'||devOut.staffGain<1)throw new Error('probabilistic staff development path did not apply');
const beforeRel=v50CoachRelPrev(young),afterRel=coachRelationshipScoreV36(young);if(!Number.isFinite(afterRel)||afterRel<20||afterRel>98)throw new Error('coach relationship integration invalid');
const market=staffCandidatePoolV38('coach',userTeam),cand=market.find(x=>x.id!==st.coach.id);if(!cand)throw new Error('no coach candidate');interviewStaffV38(cand.id,userTeam);const read=staffCoaching50().interviewReads[cand.id];if(!read||!read.demand||!read.read)throw new Error('interview demands missing');
const m=metrics(userTeam);if(!m.coachingV50||!Number.isFinite(m.coachingV50.chemistry))throw new Error('v50 simulation impact missing');
const html=staffViewV38();for(const token of ['ORGANIZATIONAL IDENTITY','DEVELOPMENT','Specialized Coaching Staff'])if(!html.includes(token))throw new Error('staff UI missing '+token);
staffTabV38='development';const devHtml=staffViewV38();if(!devHtml.includes('PLAYER DEVELOPMENT PROGRAM')||!devHtml.includes('Probabilistic development'))throw new Error('development UI missing');
console.log(JSON.stringify({status:'PASS',coach:st.coach.name,traits,tendencies:tend,chemistry:chem,identity:ident.tags,assistantRoles:roles.map(x=>[x.role.label,x.staff?.name||null]),developmentPlayer:young.name,developmentPlan:plan,developmentOutcome:devOut,relationship:{before:beforeRel,after:afterRel},interview:{candidate:cand.name,demand:read.demand,read:read.read},simulationImpact:m.coachingV50},null,2));
})();`);
vm.runInContext(code,sandbox,{filename:'app-v0.51-runtime.js',timeout:120000});
