const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),noop=()=>{};
function dummy(){return {innerHTML:'',textContent:'',classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},onclick:null,style:{},dataset:{},disabled:false,appendChild:noop,prepend:noop,insertAdjacentElement:noop,insertAdjacentHTML:noop,remove:noop,setAttribute:noop,querySelector:()=>dummy(),querySelectorAll:()=>[],addEventListener:noop}}
const store={};
const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},confirm:()=>true,scrollTo:()=>{},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{documentElement:{style:{setProperty:noop}},head:{appendChild:noop},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild(){},addEventListener:noop},addEventListener:noop},location:{reload(){},search:''},navigator:{},URLSearchParams};sandbox.window=sandbox;
vm.createContext(sandbox);
for(const f of ['data/data.js','data/source-certification.js','data/future-pick-ledger.js','data/schedule.js','data/schedule-template.js','cba.js','data/historical-universes-v0.56.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(root+'/app-v0.57.js','utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};
state=createHistoricalStateV54('historical-2018-19-opening-night');userTeam='TOR';state.userTeam='TOR';rebuildPlayerIndex();refreshSeasonConfig();ensureCbaState();ensureFuturePickHorizon();ensureAllRotations();ll();gm43();career46();
if(state.date!=='2018-10-16')throw new Error('wrong start date '+state.date);
if(userGameToday())throw new Error('TOR should have no game on Oct 16 in this universe');
if(activeDailyAction())throw new Error('daily activity should start unset');
const beforeNextHtml=String(v57NextGameCard());if(!beforeNextHtml.includes('NEXT GAME')||!beforeNextHtml.includes('Cleveland')&&!beforeNextHtml.includes('CLE'))throw new Error('off-day next-game card missing before advance');
const beforeResults=Object.keys(state.results).length;simNextDay();
if(state.date!=='2018-10-17')throw new Error('simNextDay did not advance one calendar day: '+state.date);
if(activeDailyAction())throw new Error('advance should not require or auto-create a training plan');
const afterResults=Object.keys(state.results).length;if(afterResults<=beforeResults)throw new Error('league games were not processed on advance');
console.log(JSON.stringify({status:'PASS',from:'2018-10-16',to:state.date,trainingWasOptional:true,resultsProcessed:afterResults-beforeResults,nextGameCardBeforeAdvance:true},null,2));
})();`);
vm.runInContext(code,sandbox,{filename:'app-v0.57-offday-progress-runtime.js',timeout:120000});
