const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),noop=()=>{};
function dummy(){return {innerHTML:'',textContent:'',classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},onclick:null,oninput:null,onchange:null,style:{setProperty:noop,removeProperty:noop},dataset:{},disabled:false,hidden:false,offsetParent:{},appendChild:noop,prepend:noop,insertAdjacentElement:noop,insertAdjacentHTML:noop,remove:noop,setAttribute:noop,removeAttribute:noop,getAttribute:()=>null,querySelector:()=>null,querySelectorAll:()=>[],addEventListener:noop,focus:noop,contains:()=>true,scrollIntoView:noop};}
const store={};
const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},requestAnimationFrame:f=>f(),confirm:()=>true,scrollTo:()=>{},MutationObserver:function(){this.observe=noop},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{activeElement:null,contains:()=>false,addEventListener:noop,documentElement:{style:{setProperty:noop}},head:{appendChild:noop},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild:noop,addEventListener:noop}},location:{reload(){},search:''},navigator:{},URLSearchParams};sandbox.window=sandbox;vm.createContext(sandbox);
for(const f of ['data/data-v0.44.js','data/source-certification-v0.44.js','data/future-pick-ledger-v0.44.js','data/schedule-v0.44.js','data/schedule-template-v0.44.js','cba-v0.44.js','data/organizations-v0.44.js','data/staff-careers-v0.44.js','data/g-league-v0.44.js','data/college-draft-v0.44.js','data/contract-market-v0.44.js','data/historical-universes-v0.56.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(path.join(root,'app-v0.59.js'),'utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};
state=createHistoricalStateV54('historical-2018-19-opening-night');userTeam='TOR';state.userTeam='TOR';rebuildPlayerIndex();refreshSeasonConfig();ensureCbaState();ensureFuturePickHorizon();ensureAllRotations();ll();gm43();career46();
if(state.date!=='2018-10-16')throw new Error('wrong historical start '+state.date);if(userGameToday())throw new Error('TOR should be off on Oct 16');if(String(teamToday()).trim()!=='')throw new Error('retired training surface rendered on historical off day');const ng=String(v57NextGameCard());if(!ng.includes('NEXT GAME'))throw new Error('historical next game missing');const before=state.date;simNextDay();if(state.date!=='2018-10-17')throw new Error('historical off day did not advance: '+state.date);if(activeDailyAction())throw new Error('retired training reappeared');console.log(JSON.stringify({status:'PASS',from:before,to:state.date,historical:true,trainingRetired:true,nextGame:true},null,2));})();`);
vm.runInContext(code,sandbox,{filename:'app-v0.59-historical-offday-runtime.js',timeout:120000});
