from pathlib import Path
import re,sys
ROOT=Path(__file__).resolve().parents[1]
app=(ROOT/'app-v0.50.js').read_text(); index=(ROOT/'index.html').read_text(); game=(ROOT/'gameday.html').read_text(); ex=(ROOT/'exhibition.html').read_text()
checks=[]
def ck(n,c): checks.append((n,bool(c)))
ck('v47 branding','V0.50 STAFF, COACHING + ORGANIZATIONAL IDENTITY' in index)
ck('v47 app pin','app-v0.50.js' in index)
ck('v47 gameday pin','gameday-v0.50.js' in game)
ck('v47 exhibition pin','exhibition-v0.50.js' in ex)
ck('exhibition query v47','exhibition.html?v=0.50' in index)
ck('schema 25','const SAVE_SCHEMA=25;' in app)
ck('save key','nbaCourtsideSaveV25' in app)
ck('additive history state','state.leagueHistoryV47' in app and 'version:47' in app)
ck('legacy importer','for(const x of state.history||[])' in app and 'legacy:true' in app)
ck('season archive','function archiveSeasonV47' in app)
ck('standings archive','standings=[' in app and "['East','West']" in app)
ck('team snapshots','payroll:apronTeamSalary' in app and 'roster:teamPlayers' in app)
ck('player season totals','playersSnap[id]' in app and 'stats:structuredClone(x)' in app)
ck('postseason archive','postseasonResults:structuredClone' in app)
ck('retirement ledger','H.retirements' in app and 'state.offseasonSummary?.retirements' in app)
ck('draft archive','H.drafts[state.seasonYear]' in app and 'state.draft.selections' in app)
ck('five history views',all(x in app for x in ['OVERVIEW','SEASONS','FRANCHISES','PLAYERS','DRAFTS']))
ck('save era record book','SAVE-ERA RECORD BOOK' in app.upper() and 'historyRecordBookV47' in app)
ck('franchise history','function teamHistoryV47' in app and 'SAVE-ERA FRANCHISE HISTORY' in app)
ck('player career totals','function careerTotalsV47' in app and 'NBA Courtside Career History' in app)
ck('draft history board','v47DraftBoard' in app)
ck('archive before employment review','const v47BeginOffseasonPrev=beginOffseason' in app and "if(state?.phase==='champion')archiveSeasonV47()" in app)
ck('gm career retained','state.gmCareerV46' in app and 'function career46()' in app)
ck('offseason retained','state.offseasonV45' in app and 'function offseasonCommandCenterV45' in app)
ck('deadline retained','state.tradeDeadlineV44' in app and 'function deadlineCommandCenter44' in app)
ck('action hierarchy retained','promotePrimaryActionsV441' in app)
ck('game links v48',"'v=0.48'" in app)
for f in ['app-v0.50.js','gameday-v0.50.js','exhibition-v0.50.js']:
    ck('asset '+f,(ROOT/f).exists())
passed=sum(v for _,v in checks)
for n,v in checks: print(('PASS' if v else 'FAIL')+' | '+n)
print(f'\nRESULT: {passed}/{len(checks)} checks passed')
if passed!=len(checks):
    [print('- '+n) for n,v in checks if not v];sys.exit(1)
