const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let src=read('app-v0.40.js');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__healthSeason={getState:()=>state,getGames:()=>games,getBaseGames:()=>baseGames,ensureAllRotations,simulateGame,ensureNBAProgress,refreshSeasonConfig,v17SimCpuCupFinal,processMedicalDay,health40,healthEntryV40,teamHealthSummaryV40};\n})();`).replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}').replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}').replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}');
const store={nbaCourtsideTeam:'NOPE'},noop=()=>{};const el=()=>({innerHTML:'',style:{setProperty:noop},classList:{add:noop,remove:noop,contains:()=>false},setAttribute:noop,addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],appendChild:noop,insertAdjacentHTML:noop});
const ctx={console,structuredClone,Date,URLSearchParams,Math,setTimeout:f=>f(),confirm:()=>true,scrollTo:noop,location:{search:'',reload:noop},window:{},document:{documentElement:{style:{setProperty:noop}},head:{appendChild:noop},body:el(),querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:el,addEventListener:noop},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data-v0.40.js','data/source-certification-v0.40.js','data/future-pick-ledger-v0.40.js','data/schedule-v0.40.js','data/schedule-template-v0.40.js','cba-v0.40.js','data/organizations-v0.40.js','data/staff-careers-v0.40.js','data/g-league-v0.40.js','data/college-draft-v0.40.js','data/contract-market-v0.40.js'])vm.runInContext(read(f),ctx,{filename:f});vm.runInContext(src,ctx,{filename:'app-v0.40.js'});
const t=ctx.__healthSeason,s=t.getState();if(!t)throw new Error('hooks missing');s.userTeam='NOPE';s.seasonYear=2026;s.date='2026-10-20';s.phase='regular_season';s.seasonStarted=true;s.seasonComplete=false;s.scheduleMode='official_2026';s.results={};s.seasonStats={};s.gameLogs={};s.rotations={};s.nbaCup=null;s.dynamicGames=[];s.cupHistory=[];s.injuries={};s.injuryHistory=[];s.healthPerformance=null;s.transactions=[];t.refreshSeasonConfig();t.ensureAllRotations();t.health40();
function addDays(d,n=1){const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)}
let peakActive=0,activeDays=0;
for(let d='2026-10-20';d<='2027-04-11';d=addDays(d)){s.date=d;t.processMedicalDay(d);t.refreshSeasonConfig();for(const g of t.getGames().filter(g=>g.date===d&&!s.results[g.id]))t.simulateGame(g);t.ensureNBAProgress();t.refreshSeasonConfig();if(s.nbaCup?.championshipGame?.date===d&&!s.nbaCup.championshipResult)t.v17SimCpuCupFinal();const active=Object.keys(s.injuries||{}).length;peakActive=Math.max(peakActive,active);if(active)activeDays++;}
t.ensureNBAProgress();const histories=(s.injuryHistory||[]),medical=t.health40(),entries=Object.values(medical.players||{}),fat=entries.map(x=>+x.fatigue||0),avgFat=fat.reduce((a,b)=>a+b,0)/Math.max(1,fat.length),heavy=fat.filter(x=>x>=62).length,major=histories.filter(x=>x.severity==='major').length,moderate=histories.filter(x=>x.severity==='moderate').length;
if(Object.keys(s.results).length!==1230)throw new Error('season results '+Object.keys(s.results).length);if(histories.length<50||histories.length>500)throw new Error('implausible injury-event volume '+histories.length);if(peakActive>100)throw new Error('too many simultaneous injuries '+peakActive);if(avgFat>65)throw new Error('league fatigue too high '+avgFat);const maxGp=Math.max(...Object.values(s.seasonStats).map(x=>x.gp||0));if(maxGp>82)throw new Error('player over 82 GP '+maxGp);
console.log(JSON.stringify({status:'PASS',games:Object.keys(s.results).length,injuryEvents:histories.length,major,moderate,peakActive,activeDays,healthPlayers:entries.length,avgFatigue:+avgFat.toFixed(1),heavyLoadPlayers:heavy,maxPlayerGP:maxGp,activeAtEnd:Object.keys(s.injuries||{}).length},null,2));
