const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const pre={console,structuredClone,Date,URLSearchParams};pre.window=pre;vm.createContext(pre);vm.runInContext(read('data/data-v0.41.js'),pre);vm.runInContext(read('data/schedule-v0.41.js'),pre);vm.runInContext(read('data/schedule-template-v0.41.js'),pre);vm.runInContext(read('data/organizations-v0.41.js'),pre);vm.runInContext(read('data/staff-careers-v0.41.js'),pre);
const D=pre.NBA_COURTSIDE_DATA,S=pre.NBA_COURTSIDE_SCHEDULE,T=pre.NBA_COURTSIDE_SCHEDULE_TEMPLATE,O=pre.NBA_COURTSIDE_ORGS_V033,ST=pre.NBA_COURTSIDE_STAFF_CAREERS_V038;
let src=read('gameday-v0.41.js');src=src.replace(/function render\(scrollTop=false\)\{[^\n]*\}/,'function render(){}').replace(/function bind\(\)\{[^\n]*\}/,'function bind(){}').replace(/window\.addEventListener\('beforeunload',stopLive\);[\s\S]*?\}\)\(\);$/m,`window.__test={startGame,simGame,getSave:()=>save};\n})();`);
const assignments={};for(const p of D.players)assignments[p.id]=p.roster_status==='restricted_free_agent_unsigned'?null:p.team;
function run(g,idx){const save={version:25,userTeam:g.home,seasonYear:2026,date:g.date,phase:'regular_season',seasonStarted:true,seasonComplete:false,scheduleMode:'official_2026',assignments:{...assignments},statusOverrides:{},salaryOverrides:{},results:{},seasonStats:{},gameLogs:{},rotations:{},generatedPlayers:[],playerOverrides:{},injuries:{},injuryHistory:[],injuryRotationBackups:{},transactions:[],dynamicGames:[],nbaCup:null,rng:20260819+idx*97,healthPerformance:{version:40,players:{},teams:{},history:[],medicalNews:[],lastProcessedDate:g.date},gameDayCoaching:{version:41,mode:'full_auto',rotationPlan:'normal',lastOffense:'balanced',lastDefense:'balanced',lastLate:'auto'}};const store={nbaCourtsideSaveV25:JSON.stringify(save),nbaCourtsideTeam:g.home},noop=()=>{};const ctx={console:{log:noop,warn:noop,error:console.error},structuredClone,Date,URLSearchParams,setInterval:()=>0,clearInterval:noop,setTimeout:f=>f(),window:{},location:{search:`?game=${g.id}&mode=watch`},document:{documentElement:{style:{setProperty:noop}},querySelector:()=>null,querySelectorAll:()=>[]},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v)},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v)},Math,NBA_COURTSIDE_DATA:D,NBA_COURTSIDE_SCHEDULE:S,NBA_COURTSIDE_SCHEDULE_TEMPLATE:T,NBA_COURTSIDE_ORGS_V033:O,NBA_COURTSIDE_STAFF_CAREERS_V038:ST};ctx.window=ctx;ctx.window.NBA_COURTSIDE_DATA=D;ctx.window.NBA_COURTSIDE_SCHEDULE=S;ctx.window.NBA_COURTSIDE_SCHEDULE_TEMPLATE=T;ctx.window.NBA_COURTSIDE_ORGS_V033=O;ctx.window.NBA_COURTSIDE_STAFF_CAREERS_V038=ST;vm.createContext(ctx);vm.runInContext(src,ctx,{filename:'gameday-v0.41.js'});ctx.__test.startGame(false,true);ctx.__test.simGame();return ctx.__test.getSave().results[g.id];}
const sample=S.games.filter((_,i)=>i%10===0).slice(0,100),rows=[];let total=0,margin=0,ot=0;for(let i=0;i<sample.length;i++){const r=run(sample[i],i);if(!r)throw new Error('missing result '+sample[i].id);rows.push(r);total+=r.home_score+r.away_score;margin+=Math.abs(r.home_score-r.away_score);if(r.overtime)ot++;if(r.home_score<70||r.away_score<70||r.home_score>165||r.away_score>165)throw new Error('score pathology '+sample[i].id+' '+r.away_score+'-'+r.home_score);if(r.engine!=='courtside_v41_coaching_possession')throw new Error('wrong engine');}
const ppg=total/(rows.length*2),avgMargin=margin/rows.length;if(ppg<105||ppg>127)throw new Error('PPG calibration outside broad gate '+ppg);if(avgMargin<5||avgMargin>22)throw new Error('margin calibration outside broad gate '+avgMargin);console.log(JSON.stringify({status:'PASS',games:rows.length,teamPPG:+ppg.toFixed(2),avgMargin:+avgMargin.toFixed(2),overtime:ot,minScore:Math.min(...rows.flatMap(r=>[r.home_score,r.away_score])),maxScore:Math.max(...rows.flatMap(r=>[r.home_score,r.away_score]))},null,2));
