const fs=require('fs'),vm=require('vm');
const root='/mnt/data/NBA-Courtside-Smart-Front-Offices-v0.11';
const data=fs.readFileSync(root+'/data/data.js','utf8'),sched=fs.readFileSync(root+'/data/schedule.js','utf8');let src=fs.readFileSync(root+'/app.js','utf8');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__test={getState:()=>state,getGames:()=>games,getPlayers:()=>players,teamPlayers,pickAssets,teamDirection,frontOfficeProfile,pickTradeValue,playerTradeValue,stepienLegal,resolve2027FirstOwners,buildDraftOrder,evaluateTrade,completeTrade,ensureFuturePickHorizon};\n})();`).replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}').replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}').replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}');
const store={nbaCourtsideTeam:'TOR'},noop=()=>{},ctx={console,structuredClone,Date,setTimeout:(f)=>f(),confirm:()=>true,scrollTo:noop,location:{reload:noop},window:{},document:{documentElement:{style:{setProperty:noop}},querySelector:()=>({classList:{add:noop,remove:noop},innerHTML:'',onclick:null}),querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({classList:{add:noop,remove:noop}}),body:{appendChild:noop,style:{}}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]},Math};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(data,ctx);vm.runInContext(sched,ctx);vm.runInContext(src,ctx);const t=ctx.__test,st=t.getState();st.userTeam='TOR';t.ensureFuturePickHorizon();
if(t.pickAssets('TOR').length<10)throw new Error('TOR pick cabinet missing');
const origins=['WAS','DAL','LAL','MIA','SAS','ATL','NYK','PHX','HOU','BKN','MIL','NOP','UTA','CLE','MIN','DEN','OKC','LAC','TOR','BOS','CHA','CHI','DET','GSW','IND','MEM','ORL','PHI','POR','SAC'];
const owners=t.resolve2027FirstOwners(origins);const map=Object.fromEntries(origins.map((x,i)=>[x,owners[i]]));if(map.ATL!=='SAS'||map.NYK!=='BKN'||map.PHX!=='HOU')throw new Error('simple 2027 transfers failed');if(map.DAL!=='DAL')throw new Error('DAL top2 protection failed');
const torPlan=t.teamDirection('TOR'),bosPlan=t.teamDirection('BOS');if(!torPlan.label||!t.frontOfficeProfile('TOR').label)throw new Error('front office profiles missing');
// Stepien smoke: strip every TOR first from 2028 and 2029 and confirm violation.
const torFirsts=t.pickAssets('TOR').filter(x=>x.round===1),bad=torFirsts.filter(x=>x.year===2028||x.year===2029);const step=t.stepienLegal('TOR',bad);if(step.ok)throw new Error('Stepien guard failed');
console.log(JSON.stringify({version:st.version,draftAssets:st.draftAssets.length,torAssets:t.pickAssets('TOR').length,torPlan,torGM:t.frontOfficeProfile('TOR').label,bosPlan,stepienBlocked:!step.ok,stepienYears:step.years,owners2027:{ATL:map.ATL,NYK:map.NYK,PHX:map.PHX,DAL:map.DAL,LAL:map.LAL,MIA:map.MIA,SAS:map.SAS}},null,2));
