from pathlib import Path
import re, subprocess, json, sys
ROOT=Path(__file__).resolve().parents[1]
app=(ROOT/'app-v0.51.js').read_text(); idx=(ROOT/'index.html').read_text(); gd=(ROOT/'gameday.html').read_text(); ex=(ROOT/'exhibition.html').read_text(); gjs=(ROOT/'gameday-v0.51.js').read_text(); ejs=(ROOT/'exhibition-v0.51.js').read_text()
checks=[]
def ck(n,c): checks.append((n,bool(c)))
ck('index pins app v0.51','app-v0.51.js' in idx)
ck('main menu branding','V0.51 PLAYER DEVELOPMENT + AGING' in idx)
ck('gameday pins v0.51','gameday-v0.51.js' in gd)
ck('exhibition pins v0.51','exhibition-v0.51.js' in ex)
ck('schema 25 retained',"SAVE_KEY='nbaCourtsideSaveV25'" in app and 'SAVE_SCHEMA=25' in app)
ck('additive v51 state','state.playerDevelopmentV51' in app and 'version:51' in app)
ck('history state','history:{}' in app and 'developmentHistoryV51' in app)
ck('training load state','trainingLoads:{}' in app and 'setTrainingLoadV51' in app)
for x in ['LIGHT','STANDARD','AGGRESSIVE']: ck('training load '+x,x in app)
ck('aggressive injury tradeoff','injury:1.16' in app and 'v51InjuryRiskPrev' in app)
ck('light preservation','veteranPreserve:.18' in app and 'injury:.90' in app)
for x in ['shooting','playmaking','defense','strength','conditioning','finishing']: ck('skill group '+x,re.search(rf'\b{x}:\[',app) is not None)
ck('physical rating scaffolds','athleticism' in app and 'strength' in app and 'ensurePhysicalRatingsV51' in app)
ck('prime window','function primeWindowV51' in app and '[26,30]' in app and '[25,29]' in app)
ck('career stages',all(x in app for x in ['EARLY DEVELOPMENT','APPROACHING PRIME','LATE PRIME','EARLY DECLINE','LATE CAREER']))
ck('late bloomer','LATE BLOOMER' in app)
ck('early peak','EARLY PEAK' in app)
ck('development volatility','function volatilityV51' in app and all(x in app for x in ["'HIGH'","'MODERATE'","'LOW'"]))
ck('breakout variance','variance+=1.25' in app)
ck('bust variance','variance-=1.05' in app)
ck('preview does not use rng','preview?(hash01' in app)
ck('NBA opportunity','function seasonOpportunityV51' in app and 'major NBA role' in app)
ck('playoff experience','playoff experience' in app)
ck('G League reps','gLeagueDaysV51' in app and 'heavy G League reps' in app)
ck('G League assignment tracking','gleagueAssignments' in app and 'closeGLeagueAssignmentV51' in app and 'v51ToggleGLPrev' in app)
ck('injury burden','function seasonInjuryBurdenV51' in app and 'severe.length' in app)
ck('major injury skill impact',"['athleticism','stamina','finishing','perimeter_defense']" in app)
ck('staff quality factor','developmentStaffQualityV50' in app and 'staffEffect' in app)
ck('development plan factor','developmentPlanForSeasonV51' in app and 'planEffect' in app)
ck('team-aware load persistence','trainingLoads[id]={load,team:userTeam' in app)
ck('team-aware development context','function developmentTeamV51' in app)
ck('skill-specific application','function skillChangeMapV51' in app and 'focusKeys' in app)
ck('veteran physical decline','V51_AGING_PHYSICAL' in app)
ck('veteran skill retention','V51_AGING_SKILL' in app)
ck('role evolution','function roleEvolutionV51' in app and 'BENCH ORGANIZER' in app and '3-AND-D VETERAN' in app)
ck('annual outcome labels',all(x in app for x in ['BREAKOUT','IMPROVING','SHARP DECLINE','DECLINING','STABLE']))
ck('history archive per player','D.history[p.id]' in app and 'skillChanges:structuredClone' in app)
ck('league history integration','archived.playerDevelopmentV51' in app)
ck('live development watch','function developmentWatchV51' in app and 'Development Watch' in app)
ck('home hierarchy promotion','v51ReorderHomePrev' in app and 'insertAdjacentElement' in app)
ck('player development profile','Player Development + Aging' in app and 'PRIME WINDOW' in app and 'ROLE EVOLUTION' in app)
ck('draft retrospective','function draftRetrospectiveV51' in app and 'KNOWN OVR RANGE' in app)
ck('frozen draft knowledge copy','later development never rewrites that draft-night file' in app)
ck('staff development UI','v0.51 CAREER ARCS' in app and 'TRAINING LOAD' in app and 'OPPORTUNITY' in app)
ck('offseason development report','Your Development Report' in app and 'WHY IT MOVED' in app)
ck('franchise development history','Development Era' in app and 'BREAKOUT SEASONS' in app)
ck('v50 coaching retained','state.staffCoachingV50' in app and 'coachTendenciesV50' in app)
ck('v49 draft intelligence retained','draftIntelligenceV49' in app and 'selectionSnapshots' in app)
ck('v48 mobile hierarchy retained','v48AuditView' in app and 'action-context-supporting-detail' in app)
ck('v47 league history retained','leagueHistoryV47' in app and 'archiveSeasonV47' in app)
ck('v46 career retained','gmCareerV46' in app and 'acceptGMJobV46' in app)
ck('v45 offseason retained','offseasonV45' in app and 'offseasonCommandCenterV45' in app)
ck('v44 deadline retained','tradeDeadlineV44' in app and 'deadlineCommandCenter44' in app)
ck('game links move to v0.51',"replace(/v=0\\.50/g,'v=0.51')" in app)
ck('gameday back links v0.51','v=0.51' in gjs and 'v=0.50' not in gjs)
ck('exhibition back links v0.51','v=0.51' in ejs and 'v=0.50' not in ejs)
for f in ['app-v0.51.js','gameday-v0.51.js','exhibition-v0.51.js']:
    r=subprocess.run(['node','--check',str(ROOT/f)],capture_output=True,text=True); ck('syntax '+f,r.returncode==0)
for hn,text in [('index.html',idx),('gameday.html',gd),('exhibition.html',ex)]:
    refs=re.findall(r'<script[^>]+src="([^"]+)"',text); ck('runtime refs '+hn,all((ROOT/r.split('?')[0]).exists() for r in refs))
failed=[n for n,v in checks if not v]
print(json.dumps({'passed':len(checks)-len(failed),'total':len(checks),'failed':failed},indent=2))
sys.exit(1 if failed else 0)
