const fs=require('fs'),vm=require('vm');
const root='/mnt/data/NBA-Courtside-Draft-Offseason-v0.15';
const noop=()=>{};const dummy=()=>({innerHTML:'',classList:{add:noop,remove:noop,toggle:noop},onclick:null,style:{},dataset:{}});
const store={nbaCourtsideTeam:'TOR'};
const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},confirm:()=>true,scrollTo:()=>{},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{documentElement:{style:{setProperty:noop}},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild(){}}},location:{reload(){},search:''},navigator:{}};sandbox.window=sandbox;
vm.createContext(sandbox);for(const f of ['data/data.js','data/schedule.js','cba.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(root+'/app.js','utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};userTeam='TOR';state.userTeam='TOR';state.seasonYear=2027;refreshSeasonConfig();
// Create a controlled draft state with Toronto on the clock at 10 and a CPU pick at 16.
state.phase='draft';state.date='2027-06-25';state.draft={year:2027,stage:'draft',order:Array.from({length:60},(_,i)=>teams[i%30].abbr),originOrder:Array.from({length:60},(_,i)=>teams[i%30].abbr),pickIndex:9,selections:[],lotteryEntrants:[],lotteryOrder:[],records:{},generated:false};state.draft.order[9]='TOR';state.draft.originOrder[9]='TOR';state.draft.order[15]='BOS';state.draft.originOrder[15]='BOS';generateDraftClass();state.draftExperience={year:2027,stage:'draft',lotteryReveal:16,scoutingPoints:18,reports:{},board:[...state.draft.prospectIds],targets:[],tradeOffers:[],tradeHistory:[],lastSelection:null,lotteryComplete:true,scoutingComplete:true,draftStarted:true};
const offers=generateShopPickOffers();if(!offers.length)throw new Error('no trade-down offers generated');const o=offers[0],beforeCurrent=state.draft.order[9],beforeLater=state.draft.order[o.laterPick-1];acceptShopPickOffer(0);if(beforeCurrent!=='TOR')throw new Error('test setup broken');if(state.draftExperience.tradeHistory.length!==1)throw new Error('trade history missing');if(state.draft.pickIndex!==10)throw new Error('CPU did not make traded pick');
// Controlled trade-up test at pick 20 with Toronto holding a later slot.
state.draft.pickIndex=19;state.draft.order[19]='BOS';state.draft.originOrder[19]='BOS';state.draft.order[24]='TOR';state.draft.originOrder[24]='TOR';const up=tradeUpProposal();if(!up)throw new Error('no trade-up proposal');executeTradeUp();if(state.draft.order[19]!=='TOR'||state.draft.order[24]!=='BOS')throw new Error('trade-up slots not swapped');if(state.draftExperience.tradeHistory.length<2)throw new Error('trade-up history missing');
console.log(JSON.stringify({version:state.version,tradeDownPartner:o.from,tradeDownLaterPick:o.laterPick,tradeDownFutureAssets:o.assets.length,tradeUpFrom:up.laterPick,tradeUpTo:up.currentPick,tradeUpPartner:up.partner,tradeHistory:state.draftExperience.tradeHistory.length},null,2));})();`);
vm.runInContext(code,sandbox,{filename:'app-test-v15-trades.js',timeout:120000});
