const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const noop=()=>{};const dummy=()=>({innerHTML:'',classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},onclick:null,onchange:null,style:{},dataset:{},disabled:false,hidden:false,offsetParent:{},appendChild:noop,prepend:noop,querySelector:()=>null,querySelectorAll:()=>[],setAttribute:noop,removeAttribute:noop,getAttribute:()=>null,addEventListener:noop,focus:noop,insertAdjacentHTML:noop,insertAdjacentElement:noop});
const store={nbaCourtsideTeam:'PHI'};
const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},confirm:()=>true,scrollTo:()=>{},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{activeElement:null,contains:()=>false,addEventListener:noop,documentElement:{style:{setProperty:noop}},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild(){}}},location:{reload(){},search:''},navigator:{}};sandbox.window=sandbox;
vm.createContext(sandbox);
for(const f of ['data/data-v0.44.js','data/source-certification-v0.44.js','data/future-pick-ledger-v0.44.js','data/schedule-v0.44.js','data/schedule-template-v0.44.js','cba-v0.44.js','data/organizations-v0.44.js','data/staff-careers-v0.44.js','data/g-league-v0.44.js','data/college-draft-v0.44.js','data/contract-market-v0.44.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(root+'/app-v0.51.js','utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};
refreshSeasonConfig();userTeam='PHI';state.userTeam='PHI';state.seasonYear=2026;state.seasonStarted=true;state.phase='regular_season';state.date='2027-04-20';
staff38();staffCoaching50();playerDevelopment51();
const roster=teamPlayers(userTeam).filter(p=>['active','two_way'].includes(currentStatus(p)));const young=roster.slice().sort((a,b)=>a.age-b.age)[0];const veteran=roster.slice().sort((a,b)=>b.age-a.age)[0];if(!young||!veteran)throw new Error('development test roster missing');
state.seasonStats[young.id]={gp:70,min:2100,pts:1000,reb:300,ast:280};state.playoffStats[young.id]={gp:10,min:240,pts:120,reb:30,ast:40};
state.seasonStats[veteran.id]={gp:58,min:1450,pts:650,reb:250,ast:180};
state.injuryHistory.unshift({player_id:veteran.id,start_date:'2027-01-02',days_out:76,severity:'out',body_group:'lower'});
setDevelopmentPlanV50(young.id,'shooting',roleTargetsV50(young)[0]);setTrainingLoadV51(young.id,'aggressive');setTrainingLoadV51(veteran.id,'light');
const rngBefore=state.rng;const preview=currentDevelopmentReadV51(young);if(state.rng!==rngBefore)throw new Error('development preview consumed RNG');if(!['STRONG','IMPROVING','STABLE','STAGNATING','DECLINING'].includes(preview.label))throw new Error('invalid current trend');
const opp=seasonOpportunityV51(young);if(opp.gp!==70||opp.mpg<29||opp.playoffGames!==10)throw new Error('opportunity model missing NBA/playoff reps');
const inj=seasonInjuryBurdenV51(veteran);if(inj.days<70||inj.severe<1||inj.penalty>=0)throw new Error('major injury burden missing');
const prime=primeWindowV51(young);if(prime.length!==2)throw new Error('prime window missing');const vol=volatilityV51(young);if(!['LOW','MODERATE','HIGH'].includes(vol.band))throw new Error('volatility band missing');
const baseRisk=v51InjuryRiskPrev(young,30);const aggrRisk=injuryRisk(young,30);if(!(aggrRisk>baseRisk))throw new Error('aggressive training did not raise injury risk');
const old=overall(young),age=young.age;const out=applyDevelopment(young);if(!out.v51||young.age!==age+1)throw new Error('v51 annual development did not run');if(!Number.isFinite(out.delta)||!out.factors||!out.skillChanges)throw new Error('v51 development output incomplete');if(!playerDevelopment51().history[young.id]?.some(x=>x.season===2026))throw new Error('development history not archived');
const hist=developmentHistoryV51(young).at(-1);if(!hist||!hist.trainingLoad||!hist.volatility||!hist.roleEvolution)throw new Error('development ledger incomplete');if(!Number.isFinite(young.ratings.athleticism)||!Number.isFinite(young.ratings.strength))throw new Error('physical ratings not scaffolded');
const vOld=overall(veteran);const vOut=applyDevelopment(veteran);if(!vOut.v51||!developmentHistoryV51(veteran).at(-1).injury.severe)throw new Error('veteran injury-aware development missing');
const ui=staffDevelopmentViewV50();for(const token of ['v0.51 CAREER ARCS','TRAINING LOAD','OPPORTUNITY','VOLATILITY'])if(!ui.includes(token))throw new Error('development UI missing '+token);
const prof=playerDevelopmentProfileV51(young);for(const token of ['Player Development + Aging','CAREER STAGE','PRIME WINDOW','ROLE EVOLUTION'])if(!prof.includes(token))throw new Error('profile development history missing '+token);
console.log(JSON.stringify({status:'PASS',young:young.name,oldOverall:old,newOverall:overall(young),out,preview,opportunity:opp,prime,volatility:vol,veteran:{name:veteran.name,old:vOld,new:overall(veteran),out:vOut,injury:inj},history:hist},null,2));
})();`);
vm.runInContext(code,sandbox,{filename:'app-v0.51-runtime.js',timeout:120000});
