const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let src=read('app-v0.40.js');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__v36={
 getState:()=>state,setUserTeam:a=>{userTeam=a;state.userTeam=a;},setSeason:(date='2027-01-20')=>{state.date=date;state.phase='regular_season';state.seasonYear=2026;state.seasonStarted=true;state.seasonComplete=false;ensureRotation(userTeam,true);},relations:playerRelationsV36,role:roleExpectationV36,coach:coachRelationshipScoreV36,chem:teamChemistryV36,outlook:extensionOutlookV36,createConversation:createConversationV36,evaluatePromise:evaluatePromiseV36,pending:pendingConversationsV36,respond:respondConversationV36,makePromise:makePromiseV36,promise:activePromiseV36,restriction:currentTradeRestriction,updateAll:updateMoraleAll,view:relationsViewV36,roster:()=>teamPlayers(userTeam,{activeOnly:true}),morale:moraleEntry
};\n})();`)
.replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}')
.replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}')
.replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}');
function classList(init=[]){const s=new Set(init);return {add(...x){x.forEach(v=>s.add(v))},remove(...x){x.forEach(v=>s.delete(v))},contains:v=>s.has(v),toggle(){return false}}}
function el(){return {innerHTML:'',textContent:'',dataset:{},style:{setProperty(){},removeProperty(){}},classList:classList(),onclick:null,hidden:false,disabled:false,setAttribute(){},removeAttribute(){},getAttribute(){return null},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},contains(){return true},appendChild(){},insertAdjacentHTML(){},offsetParent:{}}}
const store={nbaCourtsideTeam:'BOS'};const document={documentElement:{style:{setProperty(){}}},head:{appendChild(){}},body:el(),activeElement:el(),querySelector(){return null},querySelectorAll(){return[]},getElementById(){return null},createElement(){return el()},addEventListener(){},contains(){return true}};
const ctx={console,structuredClone,Date,URLSearchParams,Math,document,location:{search:'',reload(){}},navigator:{},scrollTo(){},confirm:()=>true,setTimeout:f=>f(),clearTimeout(){},requestAnimationFrame:f=>f(),MutationObserver:function(){this.observe=()=>{}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},window:{}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data-v0.40.js','data/source-certification-v0.40.js','data/future-pick-ledger-v0.40.js','data/schedule-v0.40.js','data/schedule-template-v0.40.js','cba-v0.40.js','data/organizations-v0.40.js','data/staff-careers-v0.40.js','data/g-league-v0.40.js','data/college-draft-v0.40.js'])vm.runInContext(read(f),ctx,{filename:f});
vm.runInContext(src,ctx,{filename:'app-v0.40.js'});const t=ctx.__v36;if(!t)throw new Error('v36 hooks missing');
t.setUserTeam('BOS');t.setSeason();const R=t.relations();if(R.version!==36)throw new Error('relations state version');const roster=t.roster();if(roster.length<10)throw new Error('BOS roster missing');const star=roster.sort((a,b)=>(b.ratings?.overall||0)-(a.ratings?.overall||0))[0],young=roster.find(p=>p.age<=24)||roster[5];const role=t.role(star);if(!['FRANCHISE PLAYER','STARTER'].includes(role.role))throw new Error('top player role expectation unreasonable');const coach=t.coach(star);if(coach<20||coach>98)throw new Error('coach relationship out of range');const chem=t.chem('BOS');if(chem.score<25||chem.score>96)throw new Error('chemistry out of range');const outlook=t.outlook(star);if(!outlook.status)throw new Error('extension outlook missing');const c=t.createConversation(young,'playing_time','role',{blocking:true});if(!c||!t.pending().length)throw new Error('conversation not created');t.respond(c.id,'minutes');const promise=t.promise(young);if(!promise||promise.type!=='minutes')throw new Error('minutes promise not created');const c2=t.createConversation(star,'player_concern','stability',{blocking:false});if(!c2)throw new Error('second conversation missing');t.respond(c2.id,'no_trade');const restriction=t.restriction(star);if(!restriction||!String(restriction.reason).includes('NO-TRADE'))throw new Error('no-trade promise not enforced');const s=t.getState(),nt=t.promise(star);s.date='2027-02-21';const keepDelta=t.evaluatePromise(star,s.date);if(keepDelta!==9||t.promise(star))throw new Error('kept promise not resolved correctly');t.updateAll(s.date,true);const html=t.view();for(const needle of ['PLAYER<br>RELATIONS.','FRONT OFFICE CONVERSATIONS','ROSTER RELATIONSHIPS','TEAM CHEMISTRY'])if(!html.includes(needle))throw new Error('relations UI missing '+needle);console.log(JSON.stringify({status:'PASS',version:R.version,roster:roster.length,topPlayer:star.name,topRole:role.role,coachTrust:coach,chemistry:chem.score,chemistryStatus:chem.status,extension:outlook.status,pendingAfterResponses:t.pending().length,minutesPromise:promise.type,noTradeRestriction:restriction.reason,keptPromiseDelta:keepDelta},null,2));
