const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let src=read('app-v0.33.js');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__v33={
 getState:()=>state,getLL:()=>ll(),getGames:()=>games,teamDirection,frontOfficeProfile,ownerDirectiveV33,coachModelV33,evaluatePackageV33,generateFindTrades,generateIncomingTrade,frontOfficeDayV33,maybeCpuTrade,
 setUserTeam:a=>{userTeam=a;state.userTeam=a;tradePartner=teams.find(t=>t.abbr!==a).abbr;},setSeason:(date='2026-12-15')=>{state.date=date;state.phase='regular_season';state.seasonStarted=true;state.seasonComplete=false;},
 setTradeMine:ks=>{tradeMine=new Set(ks);tradeTheirs.clear();tradeOffer=null;},setGoal:g=>{ll().findTradeGoal=g;ll().findTradeResults=[];},getFind:()=>ll().findTradeResults,getPlayers:a=>teamPlayers(a,{activeOnly:true}),getPicks:a=>pickAssets(a,{tradeableOnly:true}),
 packageOk:(r)=>evaluatePackageV33(r.user_keys,r.cpu_keys,r.team).ok,generateCounter:()=>buildCpuCounterV33(),getCpuTradeLog:()=>state.cpuTradeLog||[]
};\n})();`)
.replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}')
.replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}')
.replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}');
function cls(init=[]){const s=new Set(init);return {add(...x){x.forEach(v=>s.add(v))},remove(...x){x.forEach(v=>s.delete(v))},contains:v=>s.has(v)}}
function el(){return {innerHTML:'',textContent:'',dataset:{},style:{setProperty(){},removeProperty(){}},classList:cls(),onclick:null,hidden:false,disabled:false,setAttribute(){},removeAttribute(){},getAttribute(){return null},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},contains(){return true},appendChild(){},offsetParent:{}}}
const store={nbaCourtsideTeam:'BOS'};const document={documentElement:{style:{setProperty(){}}},head:{appendChild(){}},body:el(),activeElement:el(),querySelector(){return null},querySelectorAll(){return[]},getElementById(){return null},createElement(){return el()},addEventListener(){},contains(){return true}};
const ctx={console,structuredClone,Date,URLSearchParams,Math,document,location:{search:'',reload(){}},navigator:{},scrollTo(){},confirm:()=>true,setTimeout:f=>f(),clearTimeout(){},requestAnimationFrame:f=>f(),MutationObserver:function(){this.observe=()=>{}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},window:{}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data-v0.33.js','data/source-certification-v0.33.js','data/future-pick-ledger-v0.33.js','data/schedule-v0.33.js','data/schedule-template-v0.33.js','cba-v0.33.js','data/organizations-v0.33.js'])vm.runInContext(read(f),ctx,{filename:f});
vm.runInContext(src,ctx,{filename:'app-v0.33.js'});const t=ctx.__v33;if(!t)throw new Error('v33 hooks missing');t.setUserTeam('BOS');t.setSeason();const st=t.getState(),L=t.getLL();if(L.version!==33)throw new Error('Living League did not migrate to 33');
for(const a of ['BOS','DAL','UTA','OKC']){const d=t.teamDirection(a),f=t.frontOfficeProfile(a),o=t.ownerDirectiveV33(a),c=t.coachModelV33(a);if(!d.label||!f.label||!o.label||!c.rotation)throw new Error('organization model incomplete '+a)}
const bos=t.getPlayers('BOS').sort((a,b)=>b.ratings.overall-a.ratings.overall);const shop=bos.find(p=>p.ratings.overall>=75&&p.ratings.overall<=86)||bos[3];if(!shop)throw new Error('no BOS shop player');t.setTradeMine(['P|'+shop.id]);const goalCounts={};for(const goal of ['best_value','win_now','draft_capital','young_talent','cap_relief']){t.setGoal(goal);t.generateFindTrades();const rows=t.getFind();goalCounts[goal]=rows.length;if(rows.length!==5)throw new Error(`Find Me Trades ${goal} returned ${rows.length}, expected 5`);for(const r of rows)if(!r.cpu_accepts||!t.packageOk(r))throw new Error(`Find Me Trades ${goal} returned non-acceptable framework`)}const found=t.getFind(),allFoundAccept=found.every(t.packageOk);
const extraPick=t.getPicks('BOS').find(x=>x.round===2)||t.getPicks('BOS')[0];let multiAssetResults=null;if(extraPick){t.setTradeMine(['P|'+shop.id,'K|'+extraPick.id]);t.setGoal('best_value');t.generateFindTrades();const multi=t.getFind();multiAssetResults=multi.length;if(multi.length!==5)throw new Error(`multi-asset Find Me Trades returned ${multi.length}, expected 5`);for(const r of multi)if(!r.cpu_accepts||!t.packageOk(r))throw new Error('multi-asset Find Me Trades returned non-acceptable framework')}
const p=t.generateIncomingTrade(st.date,{force:true});if(p&&p.status!=='pending')throw new Error('incoming proposal status invalid');t.frontOfficeDayV33(st.date);if(!Array.isArray(L.leagueRumors)||!L.leagueRumors.length)throw new Error('front office day generated no rumor');
function addDays(s,n=1){const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}const strong=new Set(['OKC','CLE','NYK','HOU','DEN','SAS']),weak=new Set(['BKN','WAS','UTA','CHA','POR','NOP']);for(const g of t.getGames().filter(g=>g.date<'2027-01-02')){let homeWin;if(strong.has(g.home)&&!strong.has(g.away))homeWin=true;else if(strong.has(g.away)&&!strong.has(g.home))homeWin=false;else if(weak.has(g.home)&&!weak.has(g.away))homeWin=false;else if(weak.has(g.away)&&!weak.has(g.home))homeWin=true;else homeWin=(g.id.charCodeAt(g.id.length-1)%2===0);st.results[g.id]=homeWin?{home_score:112,away_score:101}:{home_score:101,away_score:112}}let md='2027-01-02';for(let i=0;i<35&&!t.getCpuTradeLog().length;i++){st.date=md;t.maybeCpuTrade(md);md=addDays(md)}if(!t.getCpuTradeLog().length)throw new Error('active CPU trade market completed no trade across January/early February probe');
console.log(JSON.stringify({status:'PASS',livingLeagueVersion:L.version,findTradeResults:found.length,goalCounts,multiAssetResults,allCpuAccept:allFoundAccept,incomingProposal:!!p,rumors:L.leagueRumors.length,cpuTrades:t.getCpuTradeLog().length,gmModel:t.frontOfficeProfile('DAL').label,coachRotation:t.coachModelV33('DAL').rotation},null,2));
