const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),noop=()=>{};const dummy=()=>({innerHTML:'',classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},onclick:null,onchange:null,style:{},dataset:{},disabled:false,hidden:false,offsetParent:{},appendChild:noop,prepend:noop,querySelector:()=>null,querySelectorAll:()=>[],setAttribute:noop,removeAttribute:noop,getAttribute:()=>null,addEventListener:noop,focus:noop,insertAdjacentHTML:noop,insertAdjacentElement:noop});
const store={nbaCourtsideTeam:'PHI'};const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},confirm:()=>true,scrollTo:()=>{},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{activeElement:null,contains:()=>false,addEventListener:noop,documentElement:{style:{setProperty:noop}},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild(){}}},location:{reload(){},search:''},navigator:{}};sandbox.window=sandbox;vm.createContext(sandbox);
for(const f of ['data/data-v0.44.js','data/source-certification-v0.44.js','data/future-pick-ledger-v0.44.js','data/schedule-v0.44.js','data/schedule-template-v0.44.js','cba-v0.44.js','data/organizations-v0.44.js','data/staff-careers-v0.44.js','data/g-league-v0.44.js','data/college-draft-v0.44.js','data/contract-market-v0.44.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(root+'/app-v0.56.js','utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};refreshSeasonConfig();userTeam='PHI';state.userTeam='PHI';state.seasonStarted=true;state.phase='regular_season';state.date='2027-01-15';ensureAllProjectionRatings();staff38();staffCoaching50();playerDevelopment51();refreshLeaguePlansV52(true);
const plans=teams.map(t=>teamPlanV52(t.abbr));if(plans.length!==30)throw new Error('not 30 plans');for(const P of plans){if(!P.label||!P.horizon||!P.pickPosture||!Array.isArray(P.core)||!P.balance)throw new Error('plan incomplete '+P.team);if(!Number.isFinite(P.spendCeiling))throw new Error('spend ceiling invalid')}
const bal=rosterBalanceV52('PHI');if(!Number.isFinite(bal.score)||!Array.isArray(bal.holes)||!Array.isArray(bal.logjams))throw new Error('balance model invalid');const p=teamPlayers('BOS',{activeOnly:true})[0];if(!p||!Number.isFinite(cpuFitV52(p,'BOS')))throw new Error('fit invalid');
// Draft behavior: create a fictional class and let a CPU team make one pick.
state.seasonStarted=false;state.phase='draft';state.seasonYear=2027;state.date='2027-06-24';state.draft={year:2027,stage:'ready',order:['BOS',...teams.filter(t=>t.abbr!=='BOS').map(t=>t.abbr),'BOS',...teams.filter(t=>t.abbr!=='BOS').map(t=>t.abbr)],originOrder:['BOS',...teams.filter(t=>t.abbr!=='BOS').map(t=>t.abbr),'BOS',...teams.filter(t=>t.abbr!=='BOS').map(t=>t.abbr)],pickIndex:0,selections:[],generated:false};generateDraftClass();const before=state.draft.pickIndex;cpuDraftOne();if(state.draft.pickIndex!==before+1||state.draft.selections.length!==1)throw new Error('cpu draft did not pick');if(!leagueAi52().decisions.some(x=>x.type==='DRAFT'))throw new Error('draft decision not logged');
// Extension behavior: make one CPU core player expiring and confirm the planner can retain him.
const ext=teamPlayers('BOS',{activeOnly:true}).sort((a,b)=>overall(b)-overall(a))[0];state.contractOverrides[ext.id]={...contractMeta(ext),team:'BOS',years:[{season_start:2027,season:'2027-28',amount:Math.max(1000000,salaryOf(ext)),option:'guaranteed'}]};refreshLeaguePlansV52(true);const pre=contractYears(ext).length;cpuExtensionSweepV52(2027);const post=contractYears(ext).length;if(post<pre)throw new Error('extension sweep corrupted contract');
// Audit and 8-season planning stress: plans must stay finite across future season labels.
const audits=[];for(let y=2027;y<2035;y++){state.seasonYear=y;refreshLeaguePlansV52(true);const a=leagueAuditV52();if(a.rows.length!==30||a.rows.some(r=>!Number.isFinite(r.balance)||!Number.isFinite(r.payroll)))throw new Error('stress audit invalid '+y);audits.push({y,issues:a.issues.length})}
const board=leagueAiBoardV52();if(!board.includes('30 Front Offices')||!board.includes('MULTI-YEAR PLANS'))throw new Error('AI board missing');console.log(JSON.stringify({status:'PASS',plans:plans.length,balance:bal,draft:state.draft.selections[0],extension:{player:ext.name,pre,post},stress:audits,decisions:leagueAi52().decisions.slice(0,5)},null,2));})();`);
vm.runInContext(code,sandbox,{filename:'app-v0.52-runtime.js',timeout:120000});
