from pathlib import Path
import re, subprocess, sys
ROOT=Path(__file__).resolve().parents[1]
app=(ROOT/'app-v0.47.js').read_text()
index=(ROOT/'index.html').read_text()
game=(ROOT/'gameday.html').read_text()
ex=(ROOT/'exhibition.html').read_text()
checks=[]
def ck(n,c): checks.append((n,bool(c)))
ck('v47 branding','V0.47 LEAGUE HISTORY + WORLD PERSISTENCE' in index)
ck('continue career','CONTINUE CAREER' in index)
ck('v47 app pin','app-v0.47.js' in index)
ck('v47 gameday pin','gameday-v0.47.js' in game)
ck('v47 exhibition pin','exhibition-v0.47.js' in ex)
ck('exhibition query v47','exhibition.html?v=0.47' in index)
ck('schema 25','const SAVE_SCHEMA=25;' in app)
ck('save key','nbaCourtsideSaveV25' in app)
ck('career additive state','state.gmCareerV46' in app)
ck('career initializer','function career46()' in app)
ck('contract lifecycle','careerContractLabelV46' in app and 'endSeason' in app)
ck('job security','function careerSecurityV46' in app and all(x in app for x in ['EXCELLENT','SAFE','WATCH','HOT SEAT','CRITICAL']))
for k in ['winning','team_building','drafting_development','negotiation','player_relations','financial_management']:
    ck('reputation '+k,k in app)
ck('employment review','function createEmploymentReviewV46' in app and 'gm_employment_review' in app)
ck('season end wrapper','createEmploymentReviewV46(\'season_end\')' in app)
ck('rare in season firing','function maybeInSeasonCareerEventV46' in app and "gp<55" in app and "sec.score<=28" in app)
ck('retention','OWNERSHIP RETAINS YOU' in app)
ck('dismissal','YOU HAVE BEEN DISMISSED' in app)
ck('non renewal','CONTRACT WILL NOT BE RENEWED' in app)
ck('extension offer','EXTENSION OFFER' in app)
ck('renewal offer','NEW CONTRACT OFFER' in app)
ck('vacancy market','function generateVacanciesV46' in app and 'v46Vacancies' in app)
ck('philosophy selection',all(x in app for x in ['win_now','patient_build','draft_develop','flexible']))
ck('interviews','function interviewJobV46' in app)
ck('club rejection',"status:offer?'offer':'rejected'" in app)
ck('job offers','C.offers[a]' in app)
ck('accept job','function acceptGMJobV46' in app)
ck('team switch preserves state','userTeam=a;state.userTeam=a' in app)
ck('no newState on job accept','function acceptGMJobV46' in app and 'acceptGMJobV46(a){\n const C=career46()' in app)
ck('career resume','function careerResumeV46' in app and 'Employment History' in app)
ck('owner meetings','function syncCareerOwnerMeetingsV46' in app)
ck('more destination','<b>GM Career</b>' in app)
ck('home career strip','function careerSummaryCardV46' in app)
ck('direction employment card','v46DirectionCareer' in app)
ck('job market continuity copy','accepting a job changes only the franchise you control' in app)
ck('v45 retained','function offseasonCommandCenterV45' in app and 'state.offseasonV45' in app)
ck('v44 retained','function deadlineCommandCenter44' in app and 'state.tradeDeadlineV44' in app)
ck('v43 retained','function franchiseDirectionViewV43' in app and 'gmEvaluationV43' in app)
ck('v441 action hierarchy','v441ActionZone' in app and 'promotePrimaryActionsV441' in app)
ck('cert file',(ROOT/'data/gm-career-employment-certification-v0.46.json').exists())
for f in ['app-v0.47.js','gameday-v0.47.js','exhibition-v0.47.js']:
    ck('asset '+f,(ROOT/f).exists())
passed=sum(v for _,v in checks)
for n,v in checks: print(('PASS' if v else 'FAIL')+' | '+n)
print(f'\nRESULT: {passed}/{len(checks)} checks passed')
if passed!=len(checks):
  print('FAILED:');[print('- '+n) for n,v in checks if not v];sys.exit(1)
