const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'); const noop=()=>{};
function dummy(){return {innerHTML:'',classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},onclick:null,style:{},dataset:{},disabled:false,querySelector:()=>null,querySelectorAll:()=>[],appendChild:noop,setAttribute:noop,addEventListener:noop,insertAdjacentHTML:noop}}
const store={nbaCourtsideTeam:'PHI'};
const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},confirm:()=>true,scrollTo:()=>{},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:()=>null,setItem:noop,removeItem:noop},document:{documentElement:{style:{setProperty:noop}},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},head:{appendChild:noop},body:{style:{},appendChild:noop}},location:{reload(){},search:''},navigator:{}};sandbox.window=sandbox;
vm.createContext(sandbox);
for(const f of ['data/data.js','data/source-certification.js','data/future-pick-ledger.js','data/schedule.js','data/schedule-template.js','cba.js','data/organizations-v0.44.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(root+'/app-v0.47.js','utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};updateNavigationV42=()=>{};enhanceAccessibility=()=>{};
refreshSeasonConfig();userTeam='PHI';state.userTeam='PHI';ensureAllProjectionRatings();autoTrimCpu();autoFillCpu();ensureAllRotations();
const roster47Test=teamPlayers('PHI').slice(0,2);state.seasonStarted=true;state.seasonComplete=true;state.phase='champion';state.date=DATES.regular_season_end;state.seasonStats={};state.seasonStats[roster47Test[0].id]={gp:82,gs:82,min:2800,pts:2050,reb:500,ast:610,stl:90,blk:40};state.seasonStats[roster47Test[1].id]={gp:80,gs:80,min:2600,pts:1600,reb:720,ast:250,stl:55,blk:100};state.awards={mvp:roster47Test[0].id,dpoy:roster47Test[1].id,roy:null,smoy:null,mip:null};state.postseason={champion:'PHI',finalsMvp:roster47Test[0].id,finals:{a:'PHI',b:'DEN'},rounds:[{round:4,a:'PHI',b:'DEN',winner:'PHI',aWins:4,bWins:2}],east:{},west:{}};state.postseasonResults={'F1':{winner:'PHI',home_score:111,away_score:103}};
beginOffseason();if(state.phase!=='gm_employment_review')throw new Error('career review gate lost');const hist47Test=league47();const season47Test=hist47Test.seasons.find(x=>x.season===2026);if(!season47Test||season47Test.legacy)throw new Error('detailed season not archived');if(season47Test.champion!=='PHI'||season47Test.finalsMvp!==roster47Test[0].id)throw new Error('champion/finals mvp archive failed');if(!season47Test.players[roster47Test[0].id]||season47Test.players[roster47Test[0].id].stats.pts!==2050)throw new Error('player stats archive failed');if(season47Test.standings.length!==30)throw new Error('standings snapshot failed '+season47Test.standings.length);if(!season47Test.teams.PHI||!Array.isArray(season47Test.teams.PHI.roster))throw new Error('team snapshot failed');
state.seasonYear=2027;state.phase='lottery';state.seasonStarted=false;state.offseasonSummary={retirements:[{id:roster47Test[1].id,name:roster47Test[1].name,team:'PHI',age:39}],development:[],released:[]};state.draft={selections:[{pick:1,team:'PHI',origin:'PHI',player_id:roster47Test[0].id}],order:['PHI'],originOrder:['PHI']};syncLeagueHistoryV47();if(!hist47Test.retirements.length||!season47Test.retirements.length)throw new Error('retirement persistence failed');if(!hist47Test.drafts[2027]||hist47Test.drafts[2027].selections.length!==1)throw new Error('draft persistence failed');
const totals47Test=careerTotalsV47(roster47Test[0].id);if(totals47Test.pts!==2050||totals47Test.gp!==82)throw new Error('career totals failed');historyTabV47='overview';if(!historyView().includes('THE LEAGUE'))throw new Error('overview render failed');historyTabV47='franchises';historyTeamV47='PHI';if(!historyView().includes('SAVE-ERA FRANCHISE HISTORY'))throw new Error('franchise render failed');historyTabV47='drafts';historyDraftV47=2027;if(!historyView().includes(roster47Test[0].name))throw new Error('draft history render failed');
const before=JSON.stringify(state.leagueHistoryV47);userTeam='BOS';state.userTeam='BOS';if(JSON.stringify(state.leagueHistoryV47)!==before)throw new Error('history mutated on team control switch');
console.log(JSON.stringify({historyVersion:hist47Test.version,seasons:hist47Test.seasons.length,champion:season47Test.champion,standings:season47Test.standings.length,playerSeasons:totals47Test.rows.length,retirements:hist47Test.retirements.length,draftYears:Object.keys(hist47Test.drafts).length,teamSwitchPreserved:true,saveSchema:state.version},null,2));
})();`);
vm.runInContext(code,sandbox,{filename:'app-test-v47-history.js',timeout:220000});
