const fs=require('fs'),vm=require('vm');const root='/mnt/data/NBA-Courtside-Injuries-v0.9';
const data=fs.readFileSync(root+'/data/data.js','utf8'),sched=fs.readFileSync(root+'/data/schedule.js','utf8');let src=fs.readFileSync(root+'/app.js','utf8');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__test={getState:()=>state,getGames:()=>games,getPlayers:()=>players,ensureAllRotations,startSeason,simulateGame,rotationPlayers,processMedicalDay,generateAwards,confTeams};\n})();`).replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}').replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}').replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}');
const store={};const noop=()=>{},ctx={console,structuredClone,Date,setTimeout:(f)=>f(),confirm:()=>true,scrollTo:noop,location:{reload:noop},window:{},document:{documentElement:{style:{setProperty:noop}},querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({classList:{add:noop,remove:noop}}),body:{appendChild:noop,style:{}}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]},Math};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(data,ctx);vm.runInContext(sched,ctx);vm.runInContext(src,ctx);const t=ctx.__test,st=t.getState();st.userTeam='TOR';
// Set userTeam internal from legacy key isn't exposed, but startSeason doesn't need UI userTeam for simulation setup; rotations all teams explicitly.
t.ensureAllRotations();st.seasonStarted=true;st.phase='regular_season';st.date='2026-10-20';st.results={};st.seasonStats={};st.gameLogs={};
let minAvail=99;for(const g of t.getGames()){st.date=g.date;t.processMedicalDay(g.date);t.simulateGame(g);for(const a of [g.home,g.away]){const n=t.rotationPlayers(a).length;minAvail=Math.min(minAvail,n);if(n<5)throw new Error('fewer than five available '+a+' '+g.date+' '+n)}}
if(Object.keys(st.results).length!==1230)throw new Error('not 1230');t.generateAwards();if(!st.awards?.mvp)throw new Error('no MVP');
console.log(JSON.stringify({games:Object.keys(st.results).length,medicalEvents:st.injuryHistory.length,activeAtEnd:Object.keys(st.injuries).length,minRotationPlayers:minAvail,mvp:t.getPlayers().find(p=>p.id===st.awards.mvp)?.name},null,2));
