const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let src=read('app-v0.38.js');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__v35={
 getState:()=>state,getCollege:()=>college35(),setUserTeam:a=>{userTeam=a;state.userTeam=a;},setSeason:(date='2026-12-15')=>{state.date=date;state.phase='regular_season';state.seasonYear=2026;state.seasonStarted=true;state.seasonComplete=false;},simCollege:simulateCollegeToV35,board:collegeBoardV35,mock:mockDraftV35,range:prospectRangeV35,scout:scoutProspectSeasonV35,group:scoutGroupV35,prepDraft:()=>{state.seasonStarted=false;state.phase='draft';state.seasonYear=2027;state.draft={generated:false,prospectIds:[]};generateDraftClass();return state.draft.prospectIds.map(id=>byId.get(id));}
};\n})();`)
.replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}')
.replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}')
.replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}');
function classList(init=[]){const s=new Set(init);return {add(...x){x.forEach(v=>s.add(v))},remove(...x){x.forEach(v=>s.delete(v))},contains:v=>s.has(v),toggle(){return false}}}
function el(){return {innerHTML:'',textContent:'',dataset:{},style:{setProperty(){},removeProperty(){}},classList:classList(),onclick:null,hidden:false,disabled:false,setAttribute(){},removeAttribute(){},getAttribute(){return null},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},contains(){return true},appendChild(){},insertAdjacentHTML(){},offsetParent:{}}}
const store={nbaCourtsideTeam:'BOS'};const document={documentElement:{style:{setProperty(){}}},head:{appendChild(){}},body:el(),activeElement:el(),querySelector(){return null},querySelectorAll(){return[]},getElementById(){return null},createElement(){return el()},addEventListener(){},contains(){return true}};
const ctx={console,structuredClone,Date,URLSearchParams,Math,document,location:{search:'',reload(){}},navigator:{},scrollTo(){},confirm:()=>true,setTimeout:f=>f(),clearTimeout(){},requestAnimationFrame:f=>f(),MutationObserver:function(){this.observe=()=>{}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},window:{}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data-v0.38.js','data/source-certification-v0.38.js','data/future-pick-ledger-v0.38.js','data/schedule-v0.38.js','data/schedule-template-v0.38.js','cba-v0.38.js','data/organizations-v0.38.js','data/staff-careers-v0.38.js','data/g-league-v0.38.js','data/college-draft-v0.38.js'])vm.runInContext(read(f),ctx,{filename:f});
vm.runInContext(src,ctx,{filename:'app-v0.38.js'});const t=ctx.__v35;if(!t)throw new Error('v35 hooks missing');
t.setUserTeam('BOS');t.setSeason('2026-12-15');t.simCollege('2026-12-15');const C=t.getCollege();if(C.version!==35)throw new Error('college save branch version');if(!C.results.length)throw new Error('college simulation produced no results');const board=t.board();if(board.length!==30)throw new Error('2027 board should contain 30 sourced watch prospects');if(board[0].name!=='Tyran Stokes' && !board.slice(0,5).some(p=>p.name==='Tyran Stokes'))throw new Error('Tyran Stokes missing from top board range');const before=t.range(board[0]).confidence;t.scout(board[0].id);const after=t.range(board[0]).confidence;if(after<=before)throw new Error('individual scouting did not improve confidence');const mock=t.mock();if(mock.length!==30||new Set(mock.map(x=>x.prospect.id)).size!==30)throw new Error('mock draft should produce 30 unique first-round prospects');const drafted=t.prepDraft();if(drafted.length!==60)throw new Error('draft class should contain 60 players');if(drafted.slice(0,30).filter(p=>String(p.id).startsWith('source-2027-')).length!==30)throw new Error('first 30 draft prospects did not persist from source-backed watch class');if(drafted.slice(30).some(p=>!String(p.rating_source).includes('fictional_2027_second_round_depth')))throw new Error('second-round boundary labeling missing');const top=drafted.find(p=>p.name==='Tyran Stokes');if(!top||top.college?.program!=='Kansas')throw new Error('college identity did not persist to draft player');console.log(JSON.stringify({status:'PASS',version:C.version,collegeResults:C.results.length,board:board.length,mock:mock.length,scoutBefore:before,scoutAfter:after,draftPlayers:drafted.length,sourceBackedFirstRound:30,secondRoundFictional:30,topProspect:top.name,topProgram:top.college.program},null,2));
