const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),noop=()=>{};
function dummy(){return {innerHTML:'',textContent:'',classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},onclick:null,oninput:null,onchange:null,style:{setProperty:noop,removeProperty:noop},dataset:{},disabled:false,hidden:false,offsetParent:{},appendChild:noop,prepend:noop,insertAdjacentHTML:noop,insertAdjacentElement:noop,setAttribute:noop,removeAttribute:noop,getAttribute:()=>null,querySelector:()=>null,querySelectorAll:()=>[],addEventListener:noop,focus:noop,contains:()=>true,scrollIntoView:noop,remove:noop};}
const store={};
const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},requestAnimationFrame:f=>f(),confirm:()=>true,scrollTo:()=>{},MutationObserver:function(){this.observe=noop},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{activeElement:null,contains:()=>false,addEventListener:noop,documentElement:{style:{setProperty:noop}},head:{appendChild:noop},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild:noop,addEventListener:noop}},location:{reload(){},search:''},navigator:{},URLSearchParams};sandbox.window=sandbox;vm.createContext(sandbox);
for(const f of ['data/data-v0.44.js','data/source-certification-v0.44.js','data/future-pick-ledger-v0.44.js','data/schedule-v0.44.js','data/schedule-template-v0.44.js','cba-v0.44.js','data/organizations-v0.44.js','data/staff-careers-v0.44.js','data/g-league-v0.44.js','data/college-draft-v0.44.js','data/contract-market-v0.44.js','data/historical-universes-v0.56.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(path.join(root,'app-v0.60.js'),'utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};
state=newState();userTeam='TOR';state.userTeam='TOR';state.seasonStarted=true;state.seasonComplete=false;state.phase='regular_season';rebuildPlayerIndex();refreshSeasonConfig();ensureCbaState();ensureFuturePickHorizon();ensureAllRotations();
// Find a regular-season Toronto off day with a future game.
let d='2026-10-20';for(let i=0;i<40;i++){state.date=d;if(!userGameToday()&&nextGame(userTeam))break;d=addDays(d,1);}if(userGameToday())throw new Error('could not find off day');
let L=ll();L.dailyActions[state.date]={id:'recovery',date:state.date,label:'Recovery Day'};if(!L.dailyActions[state.date])throw new Error('legacy training setup failed');L=ll();if(L.dailyActions[state.date])throw new Error('current-day legacy training was not retired');if(activeDailyAction())throw new Error('activeDailyAction should be retired');
const today=String(teamToday());if(today.includes('TRAINING')||today.includes('data-daily-action')||today.trim()!=='')throw new Error('off-day training UI still renders');
const stat=String(v42TodayStatus());if(stat.includes('TRAINING'))throw new Error('off-day status still mentions training');if(!stat.startsWith('OFF DAY'))throw new Error('off-day status not clear: '+stat);
const next=String(v57NextGameCard());if(!next.includes('NEXT GAME'))throw new Error('next game card missing');
const home=String(homeView());if(home.includes('TRAINING CENTER')||home.includes('data-daily-action'))throw new Error('training controls leaked into home HTML');if(!home.includes('NEXT GAME'))throw new Error('home lacks next-game context');
const story=leadStory();if(String(story?.dek||'').includes('Training,'))throw new Error('off-day editorial copy still promotes training');
const before=state.date;simNextDay();if(state.date===before)throw new Error('off day did not advance without training');
console.log(JSON.stringify({status:'PASS',offDay:before,advancedTo:state.date,trainingRetired:true,nextGameVisible:true,statsNewsOrder:['digest','sportscenter','wire','nba_today'],saveSchema:state.schemaVersion||state.schema_version||25},null,2));})();`);
vm.runInContext(code,sandbox,{filename:'app-v0.60-games-stats-news-runtime.js',timeout:120000});
