const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let src=read('app-v0.40.js');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__v40={
 getState:()=>state,setUserTeam:a=>{userTeam=a;state.userTeam=a;},players:()=>players,teams:()=>teams,cm:contractMarketV39,agent:agentForV39,expect:contractExpectationV39,priorities:playerPrioritiesV39,ask:marketAsk,heat:marketHeatV39,startFA:startFreeAgencyPeriod,faEnsure,submit:faSubmitOffer,acceptCounter:acceptCounterV39,declineCounter:declineCounterV39,neg:negotiationV39,offers:faTopOffers,resolve:faResolvePlayer,waive:waivePlayer,currentTeam,capHit,overall,home:freeAgencyLiveV39,route:faUserRoutePreview,rights:faRightsRecord,match:faResolveMatch,extensionFramework:extensionFrameworkV39,extensionScore:extensionScoreV39,hyp:offerHypotheticalV39
};\n})();`)
.replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}')
.replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}')
.replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}')
.replace(/function closeSheet\(\)\{[^\n]*\}/,'function closeSheet(){}');
function classList(init=[]){const s=new Set(init);return {add(...x){x.forEach(v=>s.add(v))},remove(...x){x.forEach(v=>s.delete(v))},contains:v=>s.has(v),toggle(){return false}}}
function el(){return {innerHTML:'',textContent:'',dataset:{},style:{setProperty(){},removeProperty(){}},classList:classList(),onclick:null,hidden:false,disabled:false,setAttribute(){},removeAttribute(){},getAttribute(){return null},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},contains(){return true},appendChild(){},insertAdjacentHTML(){},offsetParent:{}}}
const store={nbaCourtsideTeam:'BOS'};const document={documentElement:{style:{setProperty(){}}},head:{appendChild(){}},body:el(),activeElement:el(),querySelector(){return null},querySelectorAll(){return[]},getElementById(){return null},createElement(){return el()},addEventListener(){},contains(){return true}};
const ctx={console,structuredClone,Date,URLSearchParams,Math,document,location:{search:'',reload(){}},navigator:{},scrollTo(){},confirm:()=>true,setTimeout:f=>f(),clearTimeout(){},requestAnimationFrame:f=>f(),MutationObserver:function(){this.observe=()=>{}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},window:{}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data-v0.40.js','data/source-certification-v0.40.js','data/future-pick-ledger-v0.40.js','data/schedule-v0.40.js','data/schedule-template-v0.40.js','cba-v0.40.js','data/organizations-v0.40.js','data/staff-careers-v0.40.js','data/g-league-v0.40.js','data/college-draft-v0.40.js','data/contract-market-v0.40.js'])vm.runInContext(read(f),ctx,{filename:f});
vm.runInContext(src,ctx,{filename:'app-v0.40.js'});const t=ctx.__v40;if(!t)throw new Error('v40 hooks missing');
t.setUserTeam('BOS');const s=t.getState(),P=t.players();if(t.cm().version!==39)throw new Error('contract market state version');
const extCandidate=P.find(x=>x.name==='Payton Pritchard');if(!extCandidate)throw new Error('extension test player missing');s.contractOverrides[extCandidate.id]={years:[{season_start:2026,amount:9000000,option:'guaranteed'},{season_start:2027,amount:9500000,option:'guaranteed'},{season_start:2028,amount:10000000,option:'guaranteed'}],expiry:'UFA',signed:'2024-07-01',route:'standard',team:'BOS'};const extFrame=t.extensionFramework(extCandidate);if(!extFrame||!extFrame.maxYears||!extFrame.maxFirst)throw new Error('extension framework invalid');
// Give Boston artificial room only inside this isolated negotiation probe.
s.otherCap.BOS=-170000000;s.phase='free_agency';s.seasonStarted=false;s.date='2027-07-01';s.freeAgency=null;const fa=t.startFA();if(!fa||fa.day!==1)throw new Error('FA did not initialize');
const p=P.find(x=>x.name==='LeBron James');if(!p)throw new Error('test player missing');s.assignments[p.id]=null;s.statusOverrides[p.id]='free_agent';s.freeAgentRights[p.id]={team:'PHI',type:'UFA',level:'non_bird',last_salary:10000000,cap_hold:0,renounced:true};
// Remove all pending CPU offers to prove market cooling is independent of competing bids.
s.freeAgency.offers[p.id]=[];s.freeAgency.day=1;const ask1=t.ask(p);s.freeAgency.day=6;const ask6=t.ask(p);if(!(ask6<ask1))throw new Error(`market ask did not cool ${ask1} -> ${ask6}`);s.freeAgency.day=2;
const a1=t.agent(p),a2=t.agent(p);if(a1.name!==a2.name||!a1.simulated)throw new Error('agent identity not stable/simulated');if(t.priorities(p).length!==3)throw new Error('priorities missing');
const ask=t.ask(p),weak=Math.max(3000000,Math.round(ask*.55/1000)*1000);if(!t.route(p,weak))throw new Error('test team still lacks cap route');const submitted=t.submit(p,2,weak,'guaranteed');if(submitted)throw new Error('weak offer should have countered');const n=t.neg(p);if(n.status!=='countered'||!n.counter||n.history.length<2)throw new Error('persistent counter missing');
t.acceptCounter(p);const mine=t.offers(p).find(o=>o.team==='BOS');if(!mine)throw new Error('accepted counter did not become formal pending offer');
// Remove competing offers and force the decision through the normal FA resolver.
for(const o of s.freeAgency.offers[p.id]||[])if(o.team!=='BOS')o.status='lost';if(!t.resolve(p,true))throw new Error('forced negotiated signing did not resolve');if(t.currentTeam(p)!=='BOS')throw new Error('negotiated player did not sign');if(!t.cm().agreements.some(x=>x.player_id===p.id&&x.team==='BOS'))throw new Error('agreement history missing');
const html=t.home();for(const needle of ['FREE AGENCY<br>LIVE','YOUR TALKS','Shams · Free Agency Wire','Top Available'])if(!html.includes(needle))throw new Error('FA Live UI missing '+needle);
console.log(JSON.stringify({status:'PASS',version:t.cm().version,agent:a1,askDay1:ask1,askDay6:ask6,counter:n.history.find(x=>x.type==='agent_counter'),signedTo:t.currentTeam(p),agreements:t.cm().agreements.length,extensionProbe:{player:extCandidate.name,maxYears:extFrame.maxYears,maxFirst:extFrame.maxFirst}},null,2));
