from pathlib import Path
import re, subprocess, json, sys
root=Path(__file__).resolve().parent.parent
app=(root/'app-v0.50.js').read_text()
gd=(root/'gameday-v0.50.js').read_text()
idx=(root/'index.html').read_text(); ghtml=(root/'gameday.html').read_text(); exhtml=(root/'exhibition.html').read_text()
checks=[]
def ck(name, cond): checks.append((name,bool(cond)))
ck('index pins app v0.50','app-v0.50.js' in idx)
ck('main menu labels v0.50','V0.50 STAFF, COACHING + ORGANIZATIONAL IDENTITY' in idx)
ck('gameday pins v0.50','gameday-v0.50.js' in ghtml)
ck('exhibition pins v0.50','exhibition-v0.50.js' in exhtml)
ck('schema 25 retained',"SAVE_KEY='nbaCourtsideSaveV25'" in app and 'SAVE_SCHEMA=25' in app)
ck('additive v50 state','state.staffCoachingV50' in app and 'version:50' in app)
for tok in ['tactics','development','playerManagement','adaptability','scouting','reputation']: ck('staff trait '+tok,tok in app)
for tok in ['LEAD ASSISTANT','OFFENSIVE ASSISTANT','DEFENSIVE ASSISTANT','PLAYER DEVELOPMENT','SHOOTING + SKILLS']: ck('assistant role '+tok,tok in app)
ck('staff chemistry','function staffChemistryV50' in app and "'ELITE'" in app and "'CLASHING'" in app)
ck('coach tendencies','function coachTendenciesV50' in app and 'rotationDepth' in app and 'youthTrust' in app and 'usage' in app)
ck('coach roster fit','function coachRosterReadV50' in app and 'COACH ↔ ROSTER FIT' in app)
ck('organizational identity','function organizationalIdentityV50' in app and 'ORGANIZATIONAL IDENTITY' in app)
for tok in ['shooting','playmaking','defense','strength','conditioning','finishing']: ck('development focus '+tok, re.search(rf'\b{tok}:\{{label:',app) is not None)
ck('development plans stored','developmentPlans' in app and 'setDevelopmentPlanV50' in app)
ck('role development targets','3-AND-D WING' in app and 'PRIMARY CREATOR' in app and 'STRETCH FIVE' in app)
ck('probabilistic development','chance=clamp' in app and 'if(rng()<chance)' in app and 'staff_focused_gain' in app)
ck('coach relationship integration','v50CoachRelPrev' in app and 'playerManagement' in app)
ck('assistant simulation impact','coachingV50' in app and 'offAssistant' in app and 'defAssistant' in app)
ck('interview hiring demands','hiringReadV50' in app and 'CONTROL OVER LEAD ASSISTANT' in app and 'INTERVIEW READ' in app)
ck('offseason assistant depth','fillAssistantsV38(t.abbr,5)' in app)
ck('league-history coaching snapshots','row.staffCoachingV50' in app and 'Coaching + Identity Eras' in app)
ck('team workspace identity','v50TeamIdentity' in app and 'COACHING + DEVELOPMENT' in app)
ck('action-first staff tabs preserved','v38Tabs' in app and 'v50StaffPage' in app)
ck('v49 draft intelligence retained','v49RecommendationList' in app and 'selectionSnapshots' in app)
ck('v48 action hierarchy retained','v48AuditView' in app and 'action-context-supporting-detail' in app)
ck('v47 history retained','leagueHistoryV47' in app and 'archiveSeasonV47' in app)
ck('v46 career retained','gmCareerV46' in app)
ck('v45 offseason retained','offseasonV45' in app)
ck('v44 deadline retained','tradeDeadlineV44' in app)
ck('delegate label',"COACH_MODES_V41.full_auto.label='DELEGATE'" in gd)
ck('delegate coach-specific rotation','runtimeRotationV50Base' in gd and 't.depth' in gd and 'rebalanceTargetsV41' in gd)
ck('delegate coach-specific tactics','schemeDefaultsV50Base' in gd and 'pace_space' in gd and 'more_threes' in gd)
ck('coach-specific timeout threshold','threshold=gm>=86?8:gm>=76?9:10' in gd)
ck('coach adaptability live adjustment','COACH IDENTITY' in gd and 't.adaptability' in gd)
ck('delegation snapshot persisted','coaching_v50' in gd and 'delegated' in gd)
ck('gameday links v0.50','v=0.50' in gd and 'v=0.49' not in gd)
ck('no app runtime stale pin','app-v0.49.js' not in idx)
ck('no gameday stale pin','gameday-v0.49.js' not in ghtml)
ck('no exhibition stale pin','exhibition-v0.49.js' not in exhtml)
for f in ['app-v0.50.js','gameday-v0.50.js','exhibition-v0.50.js']:
 p=subprocess.run(['node','--check',str(root/f)],capture_output=True,text=True);ck('syntax '+f,p.returncode==0)
# Every direct local script reference in the three runtime HTML files exists.
for html_name,text in [('index.html',idx),('gameday.html',ghtml),('exhibition.html',exhtml)]:
 refs=re.findall(r'<script[^>]+src="([^"]+)"',text)
 ck('runtime refs '+html_name, all((root/r.split('?')[0]).exists() for r in refs))
failed=[n for n,ok in checks if not ok]
print(json.dumps({'passed':len(checks)-len(failed),'total':len(checks),'failed':failed},indent=2))
sys.exit(1 if failed else 0)
