const fs=require('fs'),vm=require('vm');
const root='/mnt/data/NBA-Courtside-Postseason-v0.14';
const ctx={window:{}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'/cba.js','utf8'),ctx);
const C=ctx.NBA_COURTSIDE_CBA;
if(!C)throw new Error('CBA module missing');
const cap=164961000,first=209015000,second=221686000,tax=200428000;
const e=C.exceptionAmounts(cap);
const close=(a,b,t=2000)=>{if(Math.abs(a-b)>t)throw new Error(`${a} != ${b}`)};
close(e.non_taxpayer_mle,15044000);close(e.taxpayer_mle,6064000);close(e.room_mle,9366000);close(e.biannual,Math.round(cap*.0332));
const bird={level:'bird',last_salary:20000000};
let routes=C.signingRoutes({teamSalary:150000000,cap,tax,firstApron:first,secondApron:second,amount:12000000,usage:{},ownRights:bird,player:{age:28,years_service:8}});
if(!routes.some(x=>x.id==='bird'&&x.years===5))throw new Error('Bird route missing');
if(!routes.some(x=>x.id==='cap_room'))throw new Error('cap room route missing');
routes=C.signingRoutes({teamSalary:198000000,cap,tax,firstApron:first,secondApron:second,amount:8000000,usage:{},player:{age:27}});
if(!routes.some(x=>x.id==='nt_mle'))throw new Error('NTMLE route missing below first apron');
routes=C.signingRoutes({teamSalary:207000000,cap,tax,firstApron:first,secondApron:second,amount:5000000,usage:{},player:{age:27}});
if(!routes.some(x=>x.id==='tax_mle'))throw new Error('Tax MLE route missing above first apron');
routes=C.signingRoutes({teamSalary:195000000,cap,tax,firstApron:first,secondApron:second,amount:5000000,usage:{bae_last_year:true},player:{age:27}});
if(routes.some(x=>x.id==='bae'))throw new Error('BAE consecutive-year lock failed');
let tr=C.tradeLegal({teamSalary:180000000,outSalary:10000000,inSalary:18000000,outCount:1,cap,tax,firstApron:first,secondApron:second});
if(!tr.ok||tr.id!=='expanded'||tr.hardCap!==first)throw new Error('expanded TPE route failed '+JSON.stringify(tr));
tr=C.tradeLegal({teamSalary:214000000,outSalary:20000000,inSalary:20200000,outCount:1,cap,tax,firstApron:first,secondApron:second});
if(!tr.ok||tr.id!=='standard')throw new Error('first-apron standard TPE failed '+JSON.stringify(tr));
tr=C.tradeLegal({teamSalary:225000000,outSalary:20000000,inSalary:20100000,outCount:1,cap,tax,firstApron:first,secondApron:second});
if(tr.ok)throw new Error('second apron salary increase should fail');
tr=C.tradeLegal({teamSalary:225000000,outSalary:20000000,inSalary:19000000,outCount:2,cap,tax,firstApron:first,secondApron:second});
if(tr.ok||!String(tr.reason).includes('NO SALARY AGGREGATION'))throw new Error('second apron aggregation lock failed');
tr=C.tradeLegal({teamSalary:205000000,outSalary:12000000,inSalary:16100000,outCount:1,cap,tax,firstApron:first,secondApron:second,existingHardCap:first});
if(tr.ok)throw new Error('existing first-apron hard cap not respected');
const built=C.buildContract({seasonYear:2026,years:4,firstSalary:20000000,raise:.05,lastOption:'player_option',source:'test'});
if(built.length!==4||built[3].option!=='player_option'||built[1].amount!==21000000)throw new Error('contract builder failed');
console.log(JSON.stringify({exceptions:e,expandedMax:C.expandedTpeMax(10000000,cap),birdMaxYears:C.maxYears({bird:true}),status:'CBA MODEL PASS'},null,2));
