const fs=require('fs'),vm=require('vm');
const root='/mnt/data/NBA-Courtside-Postseason-v0.14';
const noop=()=>{};const dummy=()=>({innerHTML:'',classList:{add:noop,remove:noop,toggle:noop},onclick:null,style:{},dataset:{}});
const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},confirm:()=>true,scrollTo:()=>{},window:{},localStorage:{_d:{nbaCourtsideTeam:'PHI'},getItem(k){return this._d[k]??null},setItem(k,v){this._d[k]=String(v)},removeItem(k){delete this._d[k]}},document:{documentElement:{style:{setProperty:noop}},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild(){}}},location:{reload(){}},navigator:{}};sandbox.window=sandbox;
vm.createContext(sandbox);
for(const f of ['data/data.js','data/schedule.js','cba.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(root+'/app.js','utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};
refreshSeasonConfig();userTeam='PHI';state.userTeam='PHI';ensureAllProjectionRatings();autoTrimCpu();autoFillCpu();ensureAllRotations();state.seasonStarted=true;state.phase='regular_season';state.date=DATES.opening_day;state.results={};state.seasonStats={};
for(const g of games)simulateGame(g);
state.seasonComplete=true;generateAwards();const firstRecord=record('PHI');beginPostseason();let waves=0;while(state.phase!=='champion'&&waves++<140){reconcilePostseason();const pending=activePostseasonGames();if(!pending.length){reconcilePostseason();continue}const d=pending[0].date;for(const g of pending.filter(x=>x.date===d))simulatePostseasonGame(g);reconcilePostseason()}
if(state.phase!=='champion')throw new Error('postseason did not finish');const champ=state.postseason.champion;const finalsMvp=byId.get(state.postseason.finalsMvp)?.name;if(!finalsMvp)throw new Error('no Finals MVP');const postGames=Object.keys(state.postseasonResults).length;
beginOffseason();const released=state.offseasonSummary?.released?.length||0;while(state.draft.pickIndex<60){if(currentDraftTeam()===userTeam){const p=draftAvailable()[0];signDraftPick(p,userTeam,state.draft.pickIndex+1)}else cpuDraftOne()}finishDraft();const picks=state.draft?.pickIndex||60;const faStart={available:freeAgents().length,offers:Object.values(state.freeAgency?.offers||{}).flat().length};for(let i=0;i<8&&state.freeAgency&&!state.freeAgency.complete;i++)advanceFreeAgencyDay();const faEnd={decisions:state.freeAgency?.decisions?.length||0,available:freeAgents().length,complete:!!state.freeAgency?.complete};while(signedCount(userTeam)>15){const cut=teamPlayers(userTeam).sort((a,b)=>assetScore(a)-assetScore(b))[0];waivePlayer(cut,userTeam,{cpu:true})}
startNextSeason();const nextSeason=CAP.season;for(const g of games)simulateGame(g);console.log(JSON.stringify({version:state.version,firstSeasonGames:1230,firstRecord,postseasonGames:postGames,champion:champ,finalsMvp,released,draftPicks:picks,faStart,faEnd,nextSeason,nextGames:Object.keys(state.results).length,nextRecord:record('PHI'),postseasonReset:state.postseason===null,playoffStatsReset:Object.keys(state.playoffStats||{}).length===0},null,2));
})();`);
vm.runInContext(code,sandbox,{filename:'app-test-v14-loop.js',timeout:220000});
