const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..');const noop=()=>{};const dummy=()=>({innerHTML:'',classList:{add:noop,remove:noop,toggle:noop},onclick:null,style:{},dataset:{},addEventListener:noop,disabled:false});const store={nbaCourtsideTeam:'PHI'};const ctx={console,structuredClone,Date,Math,URLSearchParams,setTimeout:()=>{},clearTimeout:()=>{},confirm:()=>true,scrollTo:noop,location:{reload:noop,search:''},navigator:{},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{documentElement:{style:{setProperty:noop}},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild(){}}}};ctx.window=ctx;vm.createContext(ctx);for(const f of ['data/data.js','data/source-certification.js','data/future-pick-ledger.js','data/schedule.js','data/schedule-template.js','cba.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),ctx,{filename:f});let src=fs.readFileSync(root+'/app.js','utf8');src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`refreshSeasonConfig();userTeam='PHI';state.userTeam='PHI';ensureCbaState();renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};window.__tx={getState:()=>state,getPlayers:()=>players,installContract,currentTradeRestriction,createTpe,activeTpes,consumeTpe,recordPlayerTrade,reacquisitionLocked,signingRoutesFor,waivePlayer,waiverEntry,clearWaivers,waivedHighSalaryRestricted,signAndTradeFramework,signDraftPick,oneYearConsentRequired,capHit,minimumTradeEligible,tradeLegalFor,setAggregationRestriction,aggregationRestricted,cpuTradeCbaCheck,CBA:window.NBA_COURTSIDE_CBA,cap:()=>CAP,dates:()=>DATES};\n})();`);vm.runInContext(src,ctx,{filename:'app-v22-test.js'});const T=ctx.__tx,s=T.getState(),ps=T.getPlayers(),assert=(x,m)=>{if(!x)throw new Error(m)};
// External signing starts a new Bird clock and receives the forward-certified waiting period.
const ext=ps.find(p=>p.roster_status!=='restricted_free_agent_unsigned'&&p.team&&p.contract?.years?.length);const old=ext.team;s.assignments[ext.id]=null;s.statusOverrides[ext.id]='free_agent';delete s.freeAgentRights[ext.id];s.date='2026-08-20';T.installContract(ext,old==='PHI'?'BOS':'PHI',{years:2,firstSalary:5000000,route:'minimum'});assert(s.birdClock[ext.id]===0,'external signing Bird clock');assert(T.currentTradeRestriction(ext)?.until>='2026-12-15','new-signing wait');
// CPU-to-CPU trade evaluation uses the same transaction locks/CBA gate.
const extTeam=s.assignments[ext.id],cpuBuyer=extTeam==='BOS'?'NYK':'BOS',cpuFiller=ps.find(p=>s.assignments[p.id]===cpuBuyer);const cpuLocked=T.cpuTradeCbaCheck(extTeam,cpuBuyer,ext,cpuFiller);assert(!cpuLocked.ok&&cpuLocked.reason.includes('NEW SIGNING'),'CPU trade respects new-signing lock');
// Persistent TPE: partial use, one-year expiry metadata.
const t=T.createTpe('PHI',12000000,{player:ext,sourceType:'standard'});assert(t.expires==='2027-08-20'&&T.activeTpes('PHI').length,'TPE creation/expiry');T.consumeTpe('PHI',t.id,5000000);assert(T.activeTpes('PHI').find(x=>x.id===t.id).remaining===7000000,'TPE partial use');
// Two-year minimum signings use the official minimum table rather than a generic 5% raise.
const minP=ps.find(p=>p.id!==ext.id&&p.roster_status!=='restricted_free_agent_unsigned'&&p.team&&p.contract?.years?.length);const minTeam=minP.team==='PHI'?'BOS':'PHI';s.assignments[minP.id]=null;s.statusOverrides[minP.id]='free_agent';delete s.freeAgentRights[minP.id];s.date='2026-08-21';T.installContract(minP,minTeam,{years:2,firstSalary:T.CBA.minimumSalary(T.cap().salary_cap,minP),route:'minimum'});const minRows=s.contractOverrides[minP.id].years;assert(minRows.length===2&&minRows[0].amount===T.CBA.minimumSalary(T.cap().salary_cap,minP,1)&&minRows[1].amount===T.CBA.minimumSalary(T.cap().salary_cap,minP,2),'minimum table contract');assert(T.minimumTradeEligible(minP),'minimum trade eligibility');
// Sign-and-trade framework exists for the source-certified unsigned RFA rights cases.
const rfa=ps.find(p=>p.roster_status==='restricted_free_agent_unsigned');const sat=T.signAndTradeFramework(rfa,rfa.rights_team||rfa.team);assert(sat&&sat.years===3&&sat.raise===.05&&sat.legal.ok,'S&T framework');
// One-year Bird/Early Bird contracts carry player consent.
s.contractOverrides[ext.id]={years:[{season_start:s.seasonYear,amount:5000000,option:'guaranteed'}],expiry:'UFA',signed:s.date,route:'bird',team:s.assignments[ext.id]};delete s.tradeRestrictions[ext.id];assert(T.oneYearConsentRequired(ext),'one-year Bird consent');
// Recently acquired contracts cannot be salary-aggregated for two months, except the current deadline carve-out.
s.date='2026-11-01';T.setAggregationRestriction(minP,s.date);assert(T.aggregationRestricted(minP)?.until==='2027-01-01','two-month aggregation wait');s.date='2026-12-20';assert(T.aggregationRestricted(minP),'aggregation wait remains before expiry');s.date='2026-12-15';T.setAggregationRestriction(minP,s.date);s.date=T.CBA?T.dates().trade_deadline:'';assert(!T.aggregationRestricted(minP),'deadline aggregation carve-out for pre-Dec-17 acquisition');
// Former assignor cannot immediately reacquire a traded player in free agency.
T.recordPlayerTrade(ext,'PHI','BOS');assert(T.reacquisitionLocked(ext,'PHI'),'reacquisition lock');const reacquisitionUntil=T.reacquisitionLocked(ext,'PHI').until;s.assignments[ext.id]=null;s.statusOverrides[ext.id]='free_agent';assert(T.signingRoutesFor(ext,'PHI',2000000).length===0,'reacquisition signing blocked');
// Regular-season high-salary waiver invokes the First Apron transaction restriction.
const hi=ps.find(p=>p.id!==minP.id&&s.assignments[p.id]==='BOS'&&((p.contract?.years||[]).find(y=>y.season_start===2026)?.amount||0)>16000000);assert(hi,'high salary BOS player');s.seasonStarted=true;s.date='2026-12-01';T.waivePlayer(hi,'BOS',{cpu:true});assert(T.waivedHighSalaryRestricted(hi),'high-salary waiver flag');T.clearWaivers(hi,T.waiverEntry(hi));const c=T.cap();s.otherCap.PHI=(s.otherCap.PHI||0)+Math.max(0,c.first_apron-(ctx.__tx.getState().otherCap.PHI||0))+250000000;assert(T.signingRoutesFor(hi,'PHI',T.CBA.minimumSalary(c.salary_cap,hi)).length===0,'first-apron buyout block');
// Second-round picks receive the four-year Second Round Pick Exception and a 30-day rookie lock.
s.seasonStarted=false;s.date='2027-06-20';s.seasonYear=2027;refresh=undefined;s.draft={selections:[],originOrder:Array(60).fill('PHI'),pickIndex:0};const rookie={id:'TEST-ROOKIE-V22',name:'Test Rookie',age:20,positions:['G'],roster_status:'draft_prospect',contract:{years:[]},ratings:{overall:70}};ps.push(rookie);T.signDraftPick(rookie,'PHI',45);assert(s.contractOverrides[rookie.id].route==='second_round_exception'&&s.contractOverrides[rookie.id].years.length===4,'SRPE rookie deal');assert(s.tradeRestrictions[rookie.id].until==='2027-07-31','rookie 30-day wait');const rookieTradeDate=s.tradeRestrictions[rookie.id].until;
// SRPE contracts signed before July 31 are deferred from Team Salary until July 31.
s.date='2027-07-30';const preJul=T.capHit('PHI');s.date='2027-07-31';const onJul=T.capHit('PHI');const rookieSalary=s.contractOverrides[rookie.id].years[0].amount;assert(onJul-preJul>=rookieSalary-2000,'SRPE July 31 Team Salary inclusion');
console.log(JSON.stringify({status:'PASS',tpeRemaining:7000000,minimumDeal:minRows.map(x=>x.amount),signAndTrade:rfa.name,reacquisitionUntil,rookieRoute:s.contractOverrides[rookie.id].route,rookieTradeDate,srpeDeferred:rookieSalary,aggregationWait:'2027-01-01'},null,2));
