const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),noop=()=>{};
function dummy(){return {innerHTML:'',textContent:'',classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},onclick:null,oninput:null,onchange:null,style:{setProperty:noop,removeProperty:noop},dataset:{},disabled:false,hidden:false,offsetParent:{},appendChild:noop,prepend:noop,insertAdjacentHTML:noop,insertAdjacentElement:noop,setAttribute:noop,removeAttribute:noop,getAttribute:()=>null,querySelector:()=>null,querySelectorAll:()=>[],addEventListener:noop,focus:noop,contains:()=>true,scrollIntoView:noop};}
const store={};
const sandbox={console,structuredClone,Date,Math,setTimeout:()=>{},clearTimeout:()=>{},requestAnimationFrame:f=>f(),confirm:()=>true,scrollTo:()=>{},MutationObserver:function(){this.observe=noop},window:{},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},document:{activeElement:null,contains:()=>false,addEventListener:noop,documentElement:{style:{setProperty:noop}},head:{appendChild:noop},querySelectorAll(){return[]},querySelector(){return dummy()},getElementById(){return dummy()},createElement(){return dummy()},body:{style:{},appendChild:noop,addEventListener:noop}},location:{reload(){},search:''},navigator:{},URLSearchParams};sandbox.window=sandbox;vm.createContext(sandbox);
for(const f of ['data/data-v0.44.js','data/source-certification-v0.44.js','data/future-pick-ledger-v0.44.js','data/schedule-v0.44.js','data/schedule-template-v0.44.js','cba-v0.44.js','data/organizations-v0.44.js','data/staff-careers-v0.44.js','data/g-league-v0.44.js','data/college-draft-v0.44.js','data/contract-market-v0.44.js','data/historical-universes-v0.56.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),sandbox,{filename:f});
let code=fs.readFileSync(path.join(root,'app-v0.59.js'),'utf8');
code=code.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`renderView=()=>{};setTop=()=>{};toast=()=>{};persist=()=>{};closeSheet=()=>{};
state=newState();userTeam='TOR';state.userTeam='TOR';state.seasonStarted=true;state.seasonComplete=false;state.phase='regular_season';state.date='2026-10-21';rebuildPlayerIndex();refreshSeasonConfig();ensureCbaState();ensureFuturePickHorizon();ensureAllRotations();ll();
let p=null;for(let i=0;i<8&&!p;i++){p=generateIncomingTrade(state.date,{force:true});if(!p){state.date=addDays(state.date,1);ll().lastProposalDate='';}}
if(!p)throw new Error('could not generate incoming proposal');
const uk=proposalKeysV33(p,'user'),ck=proposalKeysV33(p,'cpu');if(!uk.length||!ck.length)throw new Error('proposal missing assets');
const items=v42ActionItems(),item=items.find(x=>x.offerId===p.id);if(!item)throw new Error('proposal missing from action center');if(item.view!=='trade_offer')throw new Error('trade action does not route to dedicated proposal view');if(!item.detail.includes(keysSummaryV33(ck))||!item.detail.includes(keysSummaryV33(uk)))throw new Error('action row does not summarize exact package');
const inbox=v42ActionCenter({compact:true});if(!inbox.includes('data-v58-offer-id="'+p.id+'"'))throw new Error('action center lacks proposal id routing');
v58FocusedOfferId=p.id;const html=v58ProposalView();for(const key of ['INCOMING<br>TRADE OFFER.','YOU RECEIVE','YOU SEND','ACCEPT TRADE','COUNTER OFFER','DECLINE','CBA CHECK'])if(!html.includes(key))throw new Error('proposal review missing '+key);for(const k of [...uk,...ck]){const a=decodeTradeAsset(k);const label=a?.type==='player'?a.player.name:a?.type==='pick'?pickLabel(a.pick):'';if(label&&!html.includes(label))throw new Error('proposal review missing asset '+label)}
if(v42PrimaryFor('trade_offer')!=='transactions')throw new Error('Deals nav does not remain active');
resolveOffer(p.id,'modify');if(currentView!=='trade')throw new Error('counter did not open Trade Center');if(p.status!=='modified')throw new Error('counter did not resolve pending inbox status');if([...tradeMine].join('|')!==uk.join('|')||[...tradeTheirs].join('|')!==ck.join('|'))throw new Error('counter did not carry exact terms into builder');
console.log(JSON.stringify({status:'PASS',team:userTeam,from:p.from,offer:p.id,userSends:keysSummaryV33(uk),userReceives:keysSummaryV33(ck),route:item.view,dealsNav:v42PrimaryFor('trade_offer'),counterLoaded:true},null,2));})();`);
vm.runInContext(code,sandbox,{filename:'app-v0.59-trade-proposal-runtime.js',timeout:120000});
