const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const files=n=>fs.readFileSync(path.join(root,n),'utf8');
const dataJs=files('data/data-v0.42.js'),schedJs=files('data/schedule-v0.42.js'),templateJs=files('data/schedule-template-v0.42.js');
const pre={console,structuredClone,Date,URLSearchParams};pre.window=pre;vm.createContext(pre);vm.runInContext(dataJs,pre);vm.runInContext(schedJs,pre);
const assignments={};for(const p of pre.NBA_COURTSIDE_DATA.players)assignments[p.id]=p.roster_status==='restricted_free_agent_unsigned'?null:p.team;
const seed={version:25,userTeam:'TOR',seasonYear:2026,date:'2026-10-20',phase:'regular_season',seasonStarted:true,seasonComplete:false,assignments,statusOverrides:{},salaryOverrides:{},otherCap:{},deadCap:{},results:{},seasonStats:{},gameLogs:{},rotations:{},generatedPlayers:[],playerOverrides:{},injuries:{},injuryHistory:[],injuryRotationBackups:{},transactions:[],rng:20260819,scheduleMode:'official_2026'};
let store={nbaCourtsideSaveV25:JSON.stringify(seed),nbaCourtsideTeam:'TOR'};
// Complete a real Game Day result first.
let gd=files('gameday-v0.42.js');
gd=gd.replace(/function render\(scrollTop=false\)\{[^\n]*\}/,'function render(){}').replace(/function bind\(\)\{[^\n]*\}/,'function bind(){}').replace(/window\.addEventListener\('beforeunload',stopLive\);[\s\S]*?\}\)\(\);$/m,`window.__post={startGame,simGame,getSave:()=>save};\n})();`);
const gctx={console,structuredClone,Date,URLSearchParams,setInterval:()=>0,clearInterval:()=>{},setTimeout:f=>f(),window:{},location:{search:'?game=G0088&mode=watch'},document:{documentElement:{style:{setProperty(){}}},querySelector(){return null},querySelectorAll(){return[]}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v)},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v)},Math};gctx.window=gctx;vm.createContext(gctx);for(const s of [dataJs,files('data/source-certification-v0.42.js'),files('data/future-pick-ledger-v0.42.js'),schedJs,templateJs])vm.runInContext(s,gctx);vm.runInContext(gd,gctx);gctx.__post.startGame(false);gctx.__post.simGame();store.nbaCourtsideSaveV25=JSON.stringify(gctx.__post.getSave());
const saved=JSON.parse(store.nbaCourtsideSaveV25);if(!saved.results.G0088||saved.userTeam!=='TOR'||!saved.seasonStarted)throw new Error('postgame fixture invalid');
// Boot Franchise from the exact postgame save and verify menu bindings survive.
function cls(init=[]){const s=new Set(init);return {add(...x){x.forEach(v=>s.add(v))},remove(...x){x.forEach(v=>s.delete(v))},toggle(v,on){if(on===undefined){s.has(v)?s.delete(v):s.add(v)}else on?s.add(v):s.delete(v);return s.has(v)},contains(v){return s.has(v)}}}
function elem(init=[]){return {innerHTML:'',textContent:'',disabled:false,dataset:{},style:{setProperty(){},removeProperty(){}},classList:cls(init),onclick:null,setAttribute(){},removeAttribute(){},getAttribute(){return null},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},contains(){return true},offsetParent:{}}}
const els={'#continueFranchise':elem(['hidden']),'#continueTeam':elem(),'#newFranchise':elem(),'#backMainMenu':elem(),'#gameApp':elem(['hidden']),'#startScreen':elem(),'#teamSelectPanel':elem(['hidden']),'#mainMenuPanel':elem(),'#teamGrid':elem(),'#sheet':elem()};
const doc={documentElement:{style:{setProperty(){}}},head:{appendChild(){}},body:elem(),activeElement:elem(),querySelector:s=>els[s]||elem(),querySelectorAll:s=>[],getElementById:id=>els['#'+id]||elem(),createElement:()=>elem(),addEventListener(){},contains(){return true}};
const actx={console,structuredClone,Date,Math,URLSearchParams,setTimeout:f=>f(),clearTimeout(){},requestAnimationFrame:f=>f(),MutationObserver:function(){this.observe=()=>{}},confirm:()=>true,scrollTo(){},location:{reload(){},search:''},navigator:{},document:doc,localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},window:{}};actx.window=actx;vm.createContext(actx);for(const f of ['data/data-v0.42.js','data/source-certification-v0.42.js','data/future-pick-ledger-v0.42.js','data/schedule-v0.42.js','data/schedule-template-v0.42.js','cba-v0.42.js','data/organizations-v0.42.js','data/staff-careers-v0.42.js','data/g-league-v0.42.js','data/college-draft-v0.42.js'])vm.runInContext(files(f),actx,{filename:f});vm.runInContext(files('app-v0.42.js'),actx,{filename:'app-v0.42.js'});
if(typeof els['#newFranchise'].onclick!=='function')throw new Error('New Franchise not bound after postgame boot');
if(typeof els['#continueFranchise'].onclick!=='function')throw new Error('Continue not bound after postgame boot');
if(els['#continueFranchise'].classList.contains('hidden'))throw new Error('Continue hidden despite valid postgame franchise');
if(!files('gameday-v0.42.js').includes('index.html?continue=1&v=0.42'))throw new Error('Game Day does not route back into franchise');
console.log(JSON.stringify({status:'PASS',postgameResult:'G0088',seasonStarted:true,continueVisible:true,newFranchiseBound:true,directReturn:true},null,2));
