const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let src=read('app-v0.40.js');
src=src.replace(/\/\/ Initialise\.[\s\S]*?\}\)\(\);\s*$/m,`window.__v38={
 getState:()=>state,setUserTeam:a=>{userTeam=a;state.userTeam=a;},staff:staff38,teamStaff:teamStaffV38,security:staffSecurityV38,fit:coachFitV38,pool:staffCandidatePoolV38,fire:fireStaffV38,hire:hireStaffV38,interview:interviewStaffV38,fill:fillVacancyV38,process:processStaffDayV38,offseason:processStaffOffseasonV38,view:staffViewV38,portal:staffPortalV38,org,metrics,coachModel:coachModelV33,history:()=>staff38().history,action:staffActionRequiredV38,teams:()=>teams,players:()=>players,games:()=>games
};\n})();`)
.replace(/function setTop\(\)\{[^\n]*\}/,'function setTop(){}')
.replace(/function renderView\(\)\{[^\n]*\}/,'function renderView(){}')
.replace(/function toast\(text\)\{[^\n]*\}/,'function toast(){}');
function classList(init=[]){const s=new Set(init);return {add(...x){x.forEach(v=>s.add(v))},remove(...x){x.forEach(v=>s.delete(v))},contains:v=>s.has(v),toggle(){return false}}}
function el(){return {innerHTML:'',textContent:'',dataset:{},style:{setProperty(){},removeProperty(){}},classList:classList(),onclick:null,hidden:false,disabled:false,setAttribute(){},removeAttribute(){},getAttribute(){return null},addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},contains(){return true},appendChild(){},insertAdjacentHTML(){},offsetParent:{}}}
const store={nbaCourtsideTeam:'BOS'};const document={documentElement:{style:{setProperty(){}}},head:{appendChild(){}},body:el(),activeElement:el(),querySelector(){return null},querySelectorAll(){return[]},getElementById(){return null},createElement(){return el()},addEventListener(){},contains(){return true}};
const ctx={console,structuredClone,Date,URLSearchParams,Math,document,location:{search:'',reload(){}},navigator:{},scrollTo(){},confirm:()=>true,setTimeout:f=>f(),clearTimeout(){},requestAnimationFrame:f=>f(),MutationObserver:function(){this.observe=()=>{}},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},sessionStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]},window:{}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['data/data-v0.40.js','data/source-certification-v0.40.js','data/future-pick-ledger-v0.40.js','data/schedule-v0.40.js','data/schedule-template-v0.40.js','cba-v0.40.js','data/organizations-v0.40.js','data/staff-careers-v0.40.js','data/g-league-v0.40.js','data/college-draft-v0.40.js'])vm.runInContext(read(f),ctx,{filename:f});
vm.runInContext(src,ctx,{filename:'app-v0.40.js'});const t=ctx.__v38;if(!t)throw new Error('v38 hooks missing');
t.setUserTeam('BOS');const s=t.getState();s.seasonYear=2026;s.phase='regular_season';s.seasonStarted=true;s.seasonComplete=false;s.date='2027-01-15';s.results={};
// Give the universe a deterministic midseason record environment.
for(const g of t.games().filter(g=>g.date<=s.date)){let h=0;for(const c of g.id)h=(h*33+c.charCodeAt(0))>>>0;const homeWin=(h%100)<55;s.results[g.id]={home_score:homeWin?116:105,away_score:homeWin?104:117,winner:homeWin?g.home:g.away};}
const S=t.staff();if(S.version!==38)throw new Error('staff state version');if(Object.keys(S.teamStaff).length!==30)throw new Error('not 30 org staff states');
const bos=t.teamStaff('BOS');if(bos.coach?.name!=='Joe Mazzulla'||bos.exec?.name!=='Brad Stevens')throw new Error('Boston staff seed mismatch');if((bos.assistants||[]).length<3)throw new Error('assistant seed missing');
if(Object.keys(bos.coach.ratings||{}).length!==7||Object.keys(bos.exec.ratings||{}).length!==7)throw new Error('staff rating dimensions');if(!bos.coach.contract?.simulated||!bos.exec.contract?.simulated)throw new Error('simulated contracts missing');
const sec=t.security('BOS','coach'),fit=t.fit('BOS',bos.coach);if(!(sec.score>=5&&sec.score<=96)||!(fit>=52&&fit<=94))throw new Error('security/fit range');const m=t.metrics('BOS');if(!m.coachImpact||m.coachImpact.coach!=='Joe Mazzulla')throw new Error('bounded coach game impact missing');
// User vacancy must block the calendar and be resolvable through interview + hire.
if(!t.fire('BOS','coach',{cpu:true,reason:'runtime probe'}))throw new Error('fire failed');if(!t.action())throw new Error('vacancy did not become required');const pool=t.pool('coach','BOS');if(pool.length<5)throw new Error('coach market too small');const internal=pool.find(x=>x.currentTeam==='BOS'&&x.role==='assistant');if(!internal)throw new Error('internal assistant promotion path missing');const pick=internal;t.interview(pick.id,'BOS');if(!S.interviews[pick.id])throw new Error('interview not persistent');if(!t.hire('BOS',pick.id,'coach',{cpu:true}))throw new Error('hire failed');if(t.action())throw new Error('vacancy not resolved');if(t.teamStaff('BOS').coach?.id!==pick.id)throw new Error('dynamic org coach not updated');
// CPU vacancy must auto-fill from unemployed/assistant/generated market.
t.fire('ATL','coach',{cpu:true,reason:'runtime probe'});if(t.teamStaff('ATL').coach)throw new Error('ATL vacancy not created');if(!t.fill('ATL','coach'))throw new Error('CPU coach market fill failed');if(!t.teamStaff('ATL').coach)throw new Error('ATL vacancy remained');
// Front-office market also functions independently.
t.fire('CHI','executive',{cpu:true,reason:'runtime probe'});if(!t.fill('CHI','executive')||!t.teamStaff('CHI').exec)throw new Error('CPU executive search failed');
const html=t.view();for(const needle of ['BUILD THE<br>ORGANIZATION.','COACHES','EXECUTIVES','LEAGUE','HISTORY'])if(!html.includes(needle))throw new Error('staff UI missing '+needle);if(!t.portal().includes('STAFF + ORGANIZATION'))throw new Error('daily hub portal missing');if(t.history().filter(x=>['fired','hired','interview'].includes(x.type)).length<5)throw new Error('staff history not recording movement');
console.log(JSON.stringify({status:'PASS',version:S.version,teams:Object.keys(S.teamStaff).length,boston:{coach:t.teamStaff('BOS').coach.name,security:t.security('BOS','coach'),fit:t.fit('BOS',t.teamStaff('BOS').coach)},market:pool.length,atlCoach:t.teamStaff('ATL').coach.name,chicagoExec:t.teamStaff('CHI').exec.name,history:t.history().length,coachImpact:t.metrics('BOS').coachImpact},null,2));
